### ISSUE TITLE
[Feature] Make categories & resources in detail view clickable to return to list view filtered by category/resource

### ISSUE THREAD

**Issue by patrickunterwegs** [TechbeeAT/jtxBoard#100]

**Comment by rogercreagh** [comment]
I like the idea of clicking a category in detail view to filter the list. Presumably it would clear any existing filter? or add to it?

**Comment by patrickunterwegs** [comment]
That's what I'm actually struggling with when thinking that through.

The filter criteria is basically saved, but when clicking on a category, I would rather reset the filters, but without saving them. But what when further filter criteria is changed, shouldn't it be saved then?

Another idea that I thought of was providing a different list, that would even merge journals, notes and tasks, so you can really see all entries with that specific category... But I'm not sure if this is really a good idea...
