### ISSUE TITLE
[BUG] Alarm notification appears even though the related task was moved to the future

### ISSUE THREAD

**Issue by graue70** [TechbeeAT/jtxBoard#1002]
**Describe the bug**
See title above and reproduction below.

**To Reproduce**
1. Create a task with an alarm linked to the due date of the task. Put the due date to a time in the future (let's call the time t1).
2. When the alarm notification opens at t1, click on the notification and edit the task's due date to a point in time in the future (t2). Don't change the alarm settings. (The alarm setting should still be linked to the due date.)
3. At some point in time before t2, open the app and edit the task's due date to a point in time further in the future (t3).
4. At t2, there will be an alarm notification related to the task. If you open it and check the due date and the alarm settings of the task, they are both correctly showing t3.

(Note that t1 < t2 < t3.)

(It's possible that the second step is not necessary to reproduce the problem. I didn't try without it.)

**Expected behavior**
If I change a task's due date to the future before the task's due date is reached, there should be no alarm notification at the previous due date.

**Device and version:**
 - Device: Samsung Galaxy S10
 - Android version: Android 13
 - jtx Board version: 2.6.1
 - Downloaded from: f-Droid

**Comment by patrickunterwegs** [comment]
Hi @graue70 , did this happen regularly or only once?

Okay, sorry, I understand from your description that you tried it multiple times.

**Comment by graue70** [comment]
It has happened multiple times but unfortunately, it doesn't seem to be consistently reproducible with only the steps detailled above. There seem to be additional relevant factors that I haven't found yet.

**Comment by patrickunterwegs** [comment]
Hi @graue70 , sorry that this took so long, I have refactored the alarm handling. I was always struggling to reproduce this problem, but I would expect that this should also be solved now (with #1317). I will publish the new version soon.
