### ISSUE TITLE
[BUG] Alarm notification does not disappear when moving the task to the future

### ISSUE THREAD

**Issue by graue70** [TechbeeAT/jtxBoard#1008]
**Describe the bug**
See title above and reproduction below.

**To Reproduce**
1. Create a task with an alarm related to the task's due date and wait until the alarm notification appears.
2. Do not act on the notification, but instead open the app and move the task's due date to the future.
3. The alarm notifications is still there.

**Expected behavior**
Moving a task's due date to the future should remove the related notification (just like #4).

**Device and version:**
 - Device: Samsung Galaxy S10
 - Android version: Android 13
 - jtx Board version: 2.6.1
 - Downloaded from: f-Droid

(I thought I reported this already but couldn't find an issue for it.)

(This is somewhat related to #1002.)

**Comment by patrickunterwegs** [comment]
Hi @graue70 , how does your alarm look like? 
If you choose a fixed date and time, the alarm wouldn't move when moving the start date, only when you have set a duration like x minutes after start

**Comment by graue70** [comment]
Hi,
I always choose 'Bei Fälligkeit' (the third option, probably 'when due' or something similar in English). I thought that would link it to the due date. Is the assumption wrong? Does it only take the current due date, sets the alarm to that date and then it's fixed? (This is also relevant to #1002 I assume.)

(And because you mentioned the start date: I almost never put a start date. I only put a due date and this is also the date that I move to the future.)

**Comment by patrickunterwegs** [comment]
Hi @graue70 , ok thank you! No, your understanding is right, the "on due" option would set it to the current due date. Do you also have the sticky alarms option activated?

**Comment by graue70** [comment]
I do not have the option 'sticky alarms' activated. (But it sounds interesting. I might try it.)

**Comment by patrickunterwegs** [comment]
Sorry @graue70  that it took a while to come back to this. But what I would like to do now is to make it consistent with the sticky alarm setting: 
- When sticky alarms are activated, the notification will stay anyway until the task is done
- When sticky alarms are deactivated, the notification should disappear when you open the entry (no matter if you open it from the notification (which would make the notification disappear already now) or through the app.

Would this cover your request?

**Comment by graue70** [comment]
> Would this cover your request?

For non-sticky, your approach sounds great. Thanks!
