### ISSUE TITLE
[BUG] Can't proceed to in-app purchase

### ISSUE THREAD

**Issue by dalecooper** [TechbeeAT/jtxBoard#1024]
**Describe the bug**
Hey there, when I finally realised that sync was a paid only featured (no problem with it at all) I tried to purchase a license but I get the error message "Please check your internet collection or try again later!".
Tried on 2 different phones with 2 different OSes, installing jtx Board from f-Droid and Google Play with both phones, the result is always the same.

**To Reproduce**
1. Open menu
2. Touch "Buy Pro"
3. Touch "Upgrade to jtx Board Pro"
4. Get the error message "Please check your internet collection or try again later!"

**Expected behavior**
Be available to pay to unlock the feature!

**Screenshots**
![Screenshot_20231117-114010](https://github.com/TechbeeAT/jtxBoard/assets/16813929/d98c5e92-9dfa-4817-b34b-5ac9fc7161d2)

**Device and version**
 - Device: Pixel 7a / Oneplus 5
 - Android version: CalyxOS latest / LineageOS latest
 - jtx Board version: 2.06.03.ose / 2.06.03.gplay
 - Downloaded from: f-Droid / Google Play (via Aurora store)

**Comment by patrickunterwegs** [comment]
Hi @dalecooper !
The Aurora store doesn't support In-App-Purchases, I don't know what concept they follow because all apps with In-App-Purchases that rely on Google Play have this problem.

But the version from f-Droid shouldn't even have such an option, it's just the unlocked version with a donation page. Could you please try again to install it from f-Droid, but make sure to delete the Aurora store version before!

**Comment by dalecooper** [comment]
Thank you for the swift reply!
I must admit that I never made in-app purchase and didn't know how they work, so I thought it would open a simple web link...
Indeed there's no way to make any in-app purchase with Aurora or f-Droid.
I initially installed jtx Board from Aurora because I had no clue it was available on f-Droid. Later I reinstalled it from f-Droid but i seems that it didn't really overwrite the previous installation. Completely uninstalling + reinstalling did the trick.
Many thanks for the help and the amazing app! Sync works like a charm with Nextcloud (crossing fingers for Infomaniak support soon), it's exactly what I needed, I still can't understand VJOURNAL is still not a de-facto standard everywhere.
Be sure I'll make a donation as soon as it's payday :)

**Comment by patrickunterwegs** [comment]
Thank you also for your feedback :)
