### ISSUE TITLE
[BUG] Text date field disappears during editing

### ISSUE THREAD

**Issue by graue70** [TechbeeAT/jtxBoard#1035]
**Describe the bug**

When editing a date in the date textbox (as opposed to the date picker), the textbox disappears, the date is unset (checkmark removed) and it says 'Nicht gesetzt'.

**To Reproduce**
1. Go to a task and click on the due date.
2. Set the checkmark for the date if it isn't already set.
3. Click on the pen icon to the right of the currently selected date. This will hide the date picker and show the date in a textbox instead.
4. Delete any character of the date string.
5. See error

**Expected behavior**

I expect to be able to edit the date in the textbox.

**Screenshots**

Before deleting a character:
![Screenshot_20231122-190851_jtx Board](https://github.com/TechbeeAT/jtxBoard/assets/23035329/73989f66-72c7-4fca-8fc4-5aa6421d3d51)

After deleting a character:
![IMG_20231122_191310](https://github.com/TechbeeAT/jtxBoard/assets/23035329/f8a36caa-c2af-4e39-9076-52c0e7d2cdb5)

**Device and version**
 - Device: Samsung Galaxy S10
 - Android version: Android 13
 - jtx Board version: 2.6.3
 - Downloaded from: f-Droid

**Comment by patrickunterwegs** [comment]
Thanks, I just reproduced it, I'll check a fix soon
