### ISSUE TITLE
[Feature] Show calendar in full with domain when select

### ISSUE THREAD

**Issue by MaDill** [TechbeeAT/jtxBoard#1039]
**Is your feature request related to a problem? Please describe.**
When I create a task for a certain calendar, I want so select the calendar. The selected calendar is displayed like "name (name@uri)", but in the drop down it show only the name. I have some calendars where I can not change the names and they have a default name like "Mein Kalender". This is the case at gmx.net or web.de. When see the drop down I have no idea which one I select. I have to select one and then find out which I have selected, and maybe do it again.

**Describe the solution you'd like**
Maybe it can be displayed like later in the field with the uri and also include the color of the calendar.

**Describe alternatives you've considered**

**Additional context**
Here a screenshot:
![Screenshot_20231125-155229](https://github.com/TechbeeAT/jtxBoard/assets/7298934/1bf91cd2-053e-45d2-86e5-28a43df14171)

**Comment by patrickunterwegs** [comment]
Hi @MaDill , 
thanks, I'll add the url in the next version.
