### ISSUE TITLE
[BUG] After search the app is only half size

### ISSUE THREAD

**Issue by MaDill** [TechbeeAT/jtxBoard#1041]
**Describe the bug**
The app stay in the size when hide the keyboard.

**To Reproduce**
1. Go to notes
2. Click on the search field
3. Type some keys that some entries will be found
4. Remove the typed keys so that the search filed is empty again by pressing the backspace
5. Press the down arrrow from android (bottom left) to hide the keyboard
6. The app stay half size with just empty space above and below

**Expected behavior**
Show the app like it was before display the keyboard

**Screenshots**
![1Screenshot_20231125-161702](https://github.com/TechbeeAT/jtxBoard/assets/7298934/1f3c1074-ee8d-4b7b-960d-dbd3dde283e7)

![2Screenshot_20231125-161711](https://github.com/TechbeeAT/jtxBoard/assets/7298934/e79cc41b-13ae-42d3-8af6-bfe7c27cf096)

![3Screenshot_20231125-161717](https://github.com/TechbeeAT/jtxBoard/assets/7298934/603c8f0b-6934-4b5b-ba03-1fba044d81f2)

![4Screenshot_20231125-161722](https://github.com/TechbeeAT/jtxBoard/assets/7298934/a2ce98b2-1ebd-4518-b3ae-61b3067f3e0e)

**Device and version**
 - Device: Sony Xperia 10-III cellphone and Lenovo M8 Gen4 tablet
 - Android version: both 13
 - jtx Board version: 2.06.03.ose
 - Downloaded from: f-Droid

**Comment by patrickunterwegs** [comment]
Hi @MaDill , 
thanks, this is regrettably again something, that comes out of the official, buggy Material 3 library by Google. For me this basically works and doesn't cause any problem in the current version. But I can imagine that the problem is caused by another keyboard. Which keyboard are you using?

**Comment by MaDill** [comment]
I use the standard google keyboard Gboard. It show the version number 13.5.04.566637127.

**Comment by patrickunterwegs** [comment]
I still couldn't reproduce the issue, but I did two library upgrades now that have caused similar issues before. Now I can't reproduce any of the older issues anymore. I expect that this will solve the issue also for you.
