### ISSUE TITLE
[BUG] Widget initialisation not complete

### ISSUE THREAD

**Issue by itsbrody** [TechbeeAT/jtxBoard#1045]
**Describe the bug**
I've first installed JTF, bound by davx5 to my calendar provider equipped with all rights that its working on any device and synchronizing. Second ai've installed the jtx widget, configured it with filter criteria, which show some of the tasks entered.
Checked that they are shown.

Nightly I switch of the devices (it happens on both with different a droid versions)

**To Reproduce**
1. start device, login or whatever is needed to see its "desktop"
2. switch to page, where the widget is on: while e.g. the calender widget in the meantime has initialized showing entries the jtx "tasks" widget is shown with "Keine Einträge gefunden, die den Filterkriterien entsprechen"
3. Click on the "widget setup" to go into the setup dialog
4. Immediately leave that dialog by "<--" button
5. Result: now the widget is initialized, showing the tasks.

**Expected behavior**
The startup of the device should also completely startup and initialize the widget (as other widgets do)

**Screenshots**
![before 3](https://github.com/TechbeeAT/jtxBoard/assets/19346144/b0a19358-9f6e-4131-9938-408e47180e9a)
![after 4](https://github.com/TechbeeAT/jtxBoard/assets/19346144/69770ab4-1eaa-423f-87c9-4f8392527473)

**Device and version**
device 1:
 - Device: huawei mediapad m5
 - Android version: 9
 device 2:
 - Device: fairphone FP3
 - Android version: 11
 
both:
 - jtx Board version: 2.06.03.ose
 - Downloaded from: f-Droid

**Comment by patrickunterwegs** [comment]
Hi @itsbrody , 
thank you for the bug report. 
I couldn't reproduce the issue on my device, maybe it's also something related to Android 9. 
However, I have added a line that the widget explicitly gets refreshed after boot, I hope that will also solve your problem.

**Comment by patrickunterwegs** [comment]
To be correct: I have seen the problem, but it was like for 2 seconds, then the content appeared. 
I think the line will help, but it's still up to the system to decide what process is taken first (which could still cause delays)
