### ISSUE TITLE
[BUG] Reminder for Task on wrong day

### ISSUE THREAD

**Issue by poulpoulsen** [TechbeeAT/jtxBoard#1052]
**Describe the bug**
A Reminder between Start and due time is ignored and reminds a day after due day.

**To Reproduce**
<!-- Steps to reproduce the behavior:
1. create a task with Start and due date+time. For example: 01.12.2023 08:00 until 16:00. 
2. set a reminder to 08:30
3. on 01.12 no reminding. On 02.12. reminds in the morning

**Expected behavior**
Reminds at given time.

**Screenshots**

**Device and version**
 - Device: [Motorola g7plus]
 - Android version: [10]
 - jtx Board version:2.06.03.ose (206030001)
 - Downloaded from: [ f-Droid]

**Comment by patrickunterwegs** [comment]
Hi @poulpoulsen , please fill out all the elements of the bug template. I don't have enough information how to reproduce this issue from the description.
