### ISSUE TITLE
[Feature] Filter by no category / no resource

### ISSUE THREAD

**Issue by Djey51** [TechbeeAT/jtxBoard#107]
Hi @patrickunterwegs ,

Could you add the possibility, in the global settings, to add by defaut an etiquette, at journal or note or task creation please?

Why?
As I'm using filter by etiquette, in fact I can't see the  tasks without etiquette. As the new one don't have etiquette by defaut (especially with quick creation feature), I can't see them.
So each time I create a task, I must modify my filter to be able to see it, then modify the etiquette of the task, and modify again my filter to have my previous behavior.

Thanks

**Comment by patrickunterwegs** [comment]
Hey @Djey51 , 
I'm not so sure about how to solve this problem best. 
I am not a big fan of a global setting to apply a specific category to a subtask. What I can imagine is to make the subtask inherit the categories on creation from its main task. But then the question is if the subtasks' categories should also get updated when the main tasks categories get updated. And then there's also the question if maybe the subtasks' category should be read only to always be in sync with the main task...

What's your opinion on this?

**Comment by Djey51** [comment]
Hi @patrickunterwegs,

My request is not about the subtasks but on the main ones (i.e at creation of a note, a journal and a main task).
For your question about the subtasks, yes I think it is a good idea to inherit from a mother tasks.
But I don't like the idea to have only read access rights on subtasks etiquette. 
Perahps the following behavior :
If you modify the etiquettes of a main task which have at least one subtask --> open a message box to ask to the user "Do you want to propagate this modification to the subtask(s)?
If you modify the etiquettes of a subtask --> open a message box to ask to the user "Becarrefull : Do you want to propagate this modification to [choice 1 : the main task; And/OR ;choice 2 : the other subtask(s)]?

I'm not sure to be very clear...

**Comment by patrickunterwegs** [comment]
Hmmm, I will think about the logic for subtasks.


But then returning to main tasks: I'm not sure if it is the right approach to use categories for that. In your case, wouldn't it be better to create different collections and put the entries in the right collection where you can also easily filter them?

**Comment by Djey51** [comment]
> Hmmm, I will think about the logic for subtasks.
> 
> But then returning to main tasks: I'm not sure if it is the right approach to use categories for that. In your case, wouldn't it be better to create different collections and put the entries in the right collection where you can also easily filter them?

Definitively not. I can have the same etiquette to use for several collections.
And my original issue is that I can't see my new tasks because they are automatically filtered.

If I use categories to filter my tasks, I will have the same issue by using a specific collection for my new tasks.
And if I use collection to filter my tasks I can't use categories to do it and it becomes a too much limited

**Comment by patrickunterwegs** [comment]
I am still not convinced by the idea. Having a default category would then also mean that you have to delete the category every time you don't need it... So you could just as well add it, right?

But what I could imagine is to create a template option. For example that you can make a new entry and use an option "Set as template". When you create a new entry, the template is automatically applied with the categories, resources, attendees...

**Comment by Djey51** [comment]
I think the default option should be in the same spirit than the default date/time option. So no mandatory for people who don't want to use it.
And if you use it and have to modify it, it is the same think that the date/time mechanism.
But in fact if you use the categories, it is to filter your tasks. So you have to modify the category to had one at least to be able to use the categories filter. So with this option, you just avoid to perform the tasks when the categorie is filled by default. And additionnally it is more easy yo find it is not hidden by default.

Or if you don't like the idea. Just add the possibility to add also the "none" category in the categories filter. Like this, the task is not hidden by default and I can easily find it to make moifications😉.

The template is a good idea, but it is to answer to a larger need. But I think develop it should be very interesting too.

**Comment by patrickunterwegs** [comment]
> Just add the possibility to add also the "none" category in the categories filter. Like this, the task is not hidden by default and I can easily find it to make moifications😉.

That's something that I like much more 😉
