### ISSUE TITLE
Widget: apply selected theme to widget

### ISSUE THREAD

**Issue by AS-dh** [TechbeeAT/jtxBoard#108]
It would be great to have a dark theme for the widget. Since I have a dark background on the start screen white letters on a transparent widget would be ideal (similar to OpenTasks and aCalender+).
Thanks for the great work!

**Comment by patrickunterwegs** [comment]
Hey @AS-dh , thanks for your feedback :)
Basically there is a dark theme for the widget, it's adapting according to the system settings. Are the colors not updating for you when you switch from light to dark mode and the other way round? 
Can you tell me which version of Android and jtx Board you are using?

**Comment by AS-dh** [comment]
Hi Patrick, 
thanks for your swift response and sorry for me ignoring the basics of an issue report / feature request :-).  I've tried the newest released version of jtx board 2.01.05-rc08.gplay (201050008) on both 

- first an old Samsung S8 running Android-Version 9 with Security Patch 1. April 2021 (One-UI-Version 1.0)
--> here there is apparently no way to set a global dark mode and thus the widget looks like the first screenshot attached
![Screenshot_20221230-152456_One UI Home-Android-9](https://user-images.githubusercontent.com/2658232/210081308-2feb35d4-a09b-4718-8e13-16283bf70eb3.jpg)

- then a new Samsung S22 running Android-Version 13 / Google Play-Systemupdate 1. Sep 2022 with Security Patch 1. Dec 2022 (One-UI-Version 5.0)
--> here switching to the global dark mode achieves the desired effect and I get white letters on a black background as seen in this second screenshot
![Screenshot_20221230_152612_One UI Home_Android-13](https://user-images.githubusercontent.com/2658232/210081597-e9f147ae-2ee0-4472-9c94-a06196c4514b.jpg)

Since I'm moving to the new phone the issue is "solved for me".

**Comment by patrickunterwegs** [comment]
Hey  @AS-dh , thanks for the update 😉 
I didn't think of that problem, that older phones might not have the option to automatically change to the dark theme. So I'll take this ticket to make sure that the app setting for the theme (dark, light) is also applied to the widget 👍

**Comment by AS-dh** [comment]
Hi Patrick,
  great, I think that would be a better solution even for newer phones as it might be the case that only the background of the start screen is dark and the user doesn't want to set a global dark theme for all apps.

**Comment by patrickunterwegs** [comment]
Hey @AS-dh , 
I was a bit too fast with my proposal, I thought it would be easy to implement, but it seems to be impossible without major workarounds. 
The app itself uses a compatibility library which allows the app to override the system setting for day and night mode (or allows setting it if the Android version does not support it yet). For the widget I am using the new method for widgets in Android (Glance), but there is no option to override the colours for day and night. A workaround could be to really define each color and programmatically decide what to apply, but this might then be conflicting with the existing day/night behaviour and with the dynamic colours. So I'd rather leave this now as it is and maybe come back to this issue when new versions of the Glance library are released!
