### ISSUE TITLE
[Feature] task repeating with relative number from end

### ISSUE THREAD

**Issue by itsbrody** [TechbeeAT/jtxBoard#1091]
I setup a subtask with repeatings. After finding the start date (which is here the 31st of May) I tried to find an adequate repeating (all six month on last day of that month is the right rule), but failed:

using the real 31st (of may) I only get repeats offered, which fit to have a 31st day in month
using the unreal 30st, I get every repetition, but that's wrong as stated above.

**Describe the solution you'd like**
Having on this case at least an entry "last day of month" would help and needs to be internally calculated to the right day of month

**Additional context**
relativity of repetitions can be also not only last day of month, but also first, second, third, forth, last special weekday (of a month) as appointsments could have as repetition rule.

**Comment by patrickunterwegs** [comment]
Thanks @itsbrody , I'll have a look.

Note for myself: https://stackoverflow.com/questions/35757778/rrule-for-repeating-monthly-on-the-31st-or-closest-day

**Comment by patrickunterwegs** [comment]
Hi @itsbrody , 
I'm struggling a bit to find a good way to display this, I thought about just extending the list (instead of making new UI elements): 

![image](https://github.com/TechbeeAT/jtxBoard/assets/72232737/fece1ea6-fb2c-44be-aee3-daef7d2ff6b5)

What do you think? Would that be clear enough for the users to say just last, last - 1, last - 2, ... ?

**Comment by itsbrody** [comment]
Hi Patrick,

because my foremost request is on "last day of month" I suggest to add "last day" behind the 31st into the day selector. Only days of month IMO phase out differently.
A broader usage could need another ui; I guess that calendar apps should give ideas.

Does that help?

Regards
Wolfgang

**Comment by itsbrody** [comment]
Have just checked my calendar APP finding this approach useful:
[cid:eu.faircode.email.23091]
what do you think?

23.12.2023 11:11:03 Wolfgang B. ***@***.***>:

> Hi Patrick,
>
> because my foremost request is on "last day of month" I suggest to add "last day" behind the 31st into the day selector. Only days of month IMO phase out differently.
> A broader usage could need another ui; I guess that calendar apps should give ideas.
>
> Does that help?
>
> Regards
> Wolfgang

**Comment by itsbrody** [comment]
> Have just checked my calendar APP finding this approach useful: [cid:eu.faircode.email.23091] what do you think? 23.12.2023 11:11:03 Wolfgang B. ***@***.***>:
> […](#)
> Hi Patrick, because my foremost request is on "last day of month" I suggest to add "last day" behind the 31st into the day selector. Only days of month IMO phase out differently. A broader usage could need another ui; I guess that calendar apps should give ideas. Does that help? Regards Wolfgang

adding the sorrily missing picture
![Screenshot_20231223-130153~2](https://github.com/TechbeeAT/jtxBoard/assets/19346144/06ff6b6f-e1f5-40d0-8e19-799ccf1921f4)

**Comment by patrickunterwegs** [comment]
Hi @itsbrody , thanks!
But that's anyway how it is already shown in the UI, it just needs to be read like a sentence. jtx Board would show: "Repeats every [month] on the [last] day of the month..."

So I'd keep it like this for now and put it in the current beta.

**Comment by itsbrody** [comment]
I guess you refer to your linked image, I was not able to open and see. Neither from the notification email nor in the GitHub Web, while checking my lost image. The solution seems fine for me - thanks and a Merry Christmas

**Comment by patrickunterwegs** [comment]
Thank you and Merry Christmas to you too! 🤗
