### ISSUE TITLE
[BUG] remove clutter - Spurious unusable data in item heading

### ISSUE THREAD

**Issue by rogercreagh** [TechbeeAT/jtxBoard#1099]
**Describe the bug**
Not really a bug as I remember you intended to do this (and at least part of it was requested as a feature)

Around v2.6.3 (or possibly 2.6.2 or before - it has taken me a while to get around to commenting on this 'cos it is irritating rather than a problem) you added the account name and the full unique url of the item to the header where the icon & colour and name of the collection is displayed when viewing or editing an item 

The account name (usually email address) is not a problem and marginally useful, but the url is making the whole bar very cluttered and is of no use whatsover since no phone or tablet that I have tried is capable of displaying the full url without ellipsis. The text is not selectable so if you if you did want to use it you can't copy and paste it and since part of it is hidden off screen you can't even copy it down manually because it is not fully displayed

I'm unclear what the intention of adding the url was, but at present it is just useless clutter and needs to be removed pending consideration of a better place to display it in a more useable way.

For example using a nextcloud server the url is of the form `https://cloud.domainname.co.uk/remote.php/dav/calendars/username/ITEMUIDLONGCODESTRINGWHICHGOESOFFTHETABLETSCREEN`

A tablet typically truncates this in the UID part and a phone doesn't even display the username part.

I can't imagine what the reason for a user wanting to know this is - but if there is a use case it could be broken down into parts and the wanted part(s) only be displayed, but the parts will differ depending what type of server it is. Personally I think if this info is useful to anyone then it could be a menu option to see it (possibly the 3 dots menu in edit mode only). Since none of it can be used in jtxB then it doesn't need to be displayed.

If it is just the server part of the url and the username (which may not be the same as the davx5 account user email) which is useful then only display them and ditch the protocol, path and UID and make them copyable.

**Comment by patrickunterwegs** [comment]
Hi @rogercreagh , 
the change was requested here: #1039 
So basically the point was that on some services the names of the collections cannot be changed and the url is a way to differentiate. 
I was thinking about only showing the domain, but as the url gets truncated with ellipsis anyway, it would be almost the same outcome. So I just left it. 

I still think it was a valid request and I wouldn't consider it as unnecessary clutter.

**Comment by rogercreagh** [comment]
Ah thank you, I couldn't find the original request.
So in the original (@MaDill)[https://github.com/MaDill] was only requesting the change in the drop down list not in the header bar. 

However since the problem is that you might have two calendars/collections with the same name I see the need for putting some additional identifier in the heading.

There is no requirement to show the full UID of the entry, and it does spoil the clean look of the UI having a lot of text that is incomplete and of no use. Would it not be very simple to extract the domain part of the url and just display that - it would be a lot easier on the eye and more meaningful and easier for the brain to process.

In the drop down list on a phone not much more than the domain gets displayed, but on a tablet and/or in the header the full text really spoils the look. If it is simple to do (?one line function call) could you try it and let us see how it looks on a tablet screen.

Maybe in Android there is no built-in function to extract the domain from a url?

As a final thought what I would find more useful to display in the heading is the time and date of the last sync.

**Comment by patrickunterwegs** [comment]
Alright, so let's try showing only the Domain 👍
