### ISSUE TITLE
[Feature]  Display time and date of last sync completion somewhere

### ISSUE THREAD

**Issue by rogercreagh** [TechbeeAT/jtxBoard#1100]
**Is your feature request related to a problem? Please describe.**
I'm still getting problems with the ui slowing right down on occasions. It seems to be associated with sync happening in the background and does not seem to affect more than a small number of users so there must be some other possibly non jtxB issue involved.

In the meantime I have to operate with sync disabled in jtxB and only allowed once an hour or less in Davx5.

It would be very useful to be able to check and see when the system last sync'd a particular collection.

This would also be useful even if sync was working flawlessly - there are occasions when you may be using jtxB offline and it would be useful to know when the last sync was.

**Describe the solution you'd like**
Ideally I would like the time and date as "`last sync HH:MM on DD-MM-YYYY`" in the header where the collection name is given on the item view/edit screen.

However that is already cluttered with other info so perhaps somewhere else could be found? Putting on the main menu under synchronisation would be some help but less than ideal as you'd have to go and look away to look at it, possibly in the middle of editing an entry. also you'd need to show the last sync time for all collections separately, whereas doing it on the item screen you'd only need to show the sync time for the current collection

**Comment by rogercreagh** [comment]
So I suppose an ideal compromise would be a setting to choose what info to show in the item header.

Display in item header
- [ ] Collection Name
- [ ] Account Name
- [ ] Collection Domain
- [ ] Last Sync Time
- [ ] ... other options that people might suggest

**Comment by patrickunterwegs** [comment]
Hi @rogercreagh , 
thanks for your proposal.
I would consider showing this information in the collections overview like this: 
![image](https://github.com/TechbeeAT/jtxBoard/assets/72232737/e8ad3931-87ad-4f6a-b7be-2f305a90473d)

I definitely won't add a setting for this and I also think the general collections selector on an entry is the wrong place for that information. But in the collections overview it would fit. It would also require a small change in DAVx5 though, so the change would create a version dependency.

**Comment by rogercreagh** [comment]
Ah yes, the collections overview would be a good place for it. I would find it very useful.

Can't see the image you linked as its in a private store, but collections overview looks like the best place.

**Comment by patrickunterwegs** [comment]
Hi @rogercreagh , just for information: 
I have made the change and I will release it with v2.7.0. But the change in jtx Board will just enable DAVx5 to set the last sync date (which is always set at the end of a sync) of a collection. This also means that the information will only get visible once also DAVx5 is updated to a version that supports this fields. I want to wait a bit for this to give everybody the chance to update jtx Board for some time, to reduce the number of users for which a version conflict would pop up.

**Comment by rogercreagh** [comment]
Excellent, thanks.
