### ISSUE TITLE
[BUG] Group journals by date groups them also by time

### ISSUE THREAD

**Issue by Kiwzi** [TechbeeAT/jtxBoard#1102]
**Describe the bug**
Group by date also group journals by time.

**To Reproduce**
Create a few journals of same date but different times.
Select in "Group/Sort" -> "Group by" -> "date".

**Expected behavior**
Entries should be grouped by date and not time.

**Screenshots**
![Screenshot_20231230-101828](https://github.com/TechbeeAT/jtxBoard/assets/143224712/65777ebb-21d7-4262-baec-bc32538a4349)

**Device and version**
 - Device: Pixel 7a
 - Android version: Android 14
 - jtx Board version: 2.6.4
 - Downloaded from: Google Play

**Comment by Kiwzi** [comment]
Also, if possible, remove "date" from "group by" and add "day", "week" and "month"  😇

**Comment by patrickunterwegs** [comment]
Hey @Kiwzi!  thanks for the bug report!
I will put the fix in the next version. If you like you can join the Beta-program on Google Play and check it out earlier (and give feedback if you like) 😉 
About your additional request, I have made #1102 to follow up on this.
