### ISSUE TITLE
[BUG] Clearing filters not working properly

### ISSUE THREAD

**Issue by Kiwzi** [TechbeeAT/jtxBoard#1133]
**Describe the bug**
Clearing filters dont show any entries. For that to happen you need to choose "No filter".

**To Reproduce**
Make some journals or notes.
Choose a filter to show only a few.
Clear filter using the "Clear filters" button behind the three dots.

**Expected behavior**
All entries should be visible again.

**Device and version**
 - Device: [Pixel 7a]
 - Android version: [Android 14, (GrapheneOS)]
 - jtx Board version: [Version: 2.06.05-beta09.gplay (206050023)]
 - Downloaded from: [Google Play]

**Comment by patrickunterwegs** [comment]
Thanks @Kiwzi !
2.6.5 is already released, I just made a fix, a small piece of code was missing there. I'll put it in 2.7.0 and I'll publish a new beta soon!
