### ISSUE TITLE
[Feature] Settings option to choose default alarm date

### ISSUE THREAD

**Issue by skwde** [TechbeeAT/jtxBoard#1142]
**Is your feature request related to a problem? Please describe.**

Not really but it takes time to always enter the same date twice (due date / alarm date).

**Describe the solution you'd like**

Often I set a due date and then again the same date for alarm.
It would be nice to have a setting which automatically sets the alarm date.
Maybe several options for settings the alarm date to a default are helpful, e.g.
- due date
- due date - 1 d
- ...

**Describe alternatives you've considered**

Up to now I always set it manually

**Additional context**

**Comment by patrickunterwegs** [comment]
Hi @skwde , 
please don't delete the device and version information from the template.
You can already set a default alarm from the settings when you activate automatic alarms "on due" in the alarms settings.
You can also combine this with the task-setting to have a default due date/time for new tasks. 
I think this pretty much covers your request, doesn't it?

**Comment by skwde** [comment]
Hi @patrickunterwegs 
I haven't deleted anything from the issue template, I just added the text.
Apparently, I just found the option.... sorry for that...

**Comment by patrickunterwegs** [comment]
Hey @skwde , 
> I haven't deleted anything from the issue template, I just added the text.
Indeed, sorry for that. I thought it was there and a lot of people actually delete it. It's just helpful to see if users might use an old version where the functionality was not there yet. 
I will update the template.

Anyhow, I'm glad the existing option works for you 🙂
