### ISSUE TITLE
[BUG] App not updatable on Android

### ISSUE THREAD

**Issue by phxyz12** [TechbeeAT/jtxBoard#1144]
**Describe the bug**
Since about two weeks, jtx board Android app doesn't update anymore. Google Play Store lists a newer version but the update fails just saying "Update failed."

**To Reproduce**
1. Open Play Store
2. Start update for all updatable apps

**Expected behavior**
Update works as in the past. 

**Screenshots**
NA

**Device and version**
 - Device: Google Pixel 7 with GrapheneOS
 - Installed jtx board from Google Play Store
 - Installed jtx board version: 2.06.04.ose (206040012)

**Comment by patrickunterwegs** [comment]
Hi @phxyz12 , 
if the installation fails for the package manager, there's nothing I can do. 
Generally if you're using Graphene OS it might be better to download the app from f-Droid as the Google Play version also uses Google Play services. Graphene OS doesn't have them on board, this can cause troubles. On f-Droid the latest version is not available yet, I assume they will package it within the next days.

**Comment by phxyz12** [comment]
Hi,

thanks a lot for the feedback, I agree to what you say. I'll try F-Deood.

Best, Pascal
