### ISSUE TITLE
[BUG] Missing Active filters text when filtering with date-range

### ISSUE THREAD

**Issue by Kiwzi** [TechbeeAT/jtxBoard#1146]
Describe the bug
When filtering with a date-range the "Active filters:" dosent show the name of the filter type.
Same goes for all the date-range filters on Tasks as well.

To Reproduce
Just filter by date-range.

Expected behavior
Should be something like "Active filters: Date: 1/7/24 - 1/8/24"

Screenshots
![cb5d5cc2-aaa5-4ad6-bec0-655c003feba4](https://github.com/TechbeeAT/jtxBoard/assets/143224712/382b21a5-7a48-4d79-904f-7672fccc0a33)

Device and version
Device: [Pixel 7a]
Android version: [Android 14, (GrapheneOS)]
jtx Board version: [Version: 2.07.00-beta02.gplay (207000005)]
Downloaded from: [Google Play]

**Comment by patrickunterwegs** [comment]
Thanks @Kiwzi ! Indeed I missed that!
Fix is on the way.
