### ISSUE TITLE
Limited compatibility due to negative COUNT value[BUG] 

### ISSUE THREAD

**Issue by burningT** [TechbeeAT/jtxBoard#1153]
**Describe the bug**
VTODO entries might contain negative COUNT values for RRULE. This is unexpected and leads to an error with other tools as CalDavSynchronizer 4.4.1.0, stating "<Error>System.ArgumentException: COUNT value -1 is out of range. Valid values are between 0 and 2147483647."

**To Reproduce**
The example causing the issue was created by creating an annually repeated task with subtasks which lead to the following entries:

BEGIN:VCALENDAR
VERSION:2.0
PRODID:DAVx5/4.3.12.1-gplay ical4j/3.2.14 (at.techbee.jtx)
BEGIN:VTODO
DTSTAMP:20240106T095918Z
UID:d6613125-6565-4bf9-be3f-15a3a136e8dc
SEQUENCE:12
CREATED:20231212T170206Z
LAST-MODIFIED:20240106T083915Z
SUMMARY:Test Task
CATEGORIES:Haushalt
DTSTART;VALUE=DATE:20231227
RRULE:FREQ=YEARLY;COUNT=-1
PRIORITY:0
DUE;VALUE=DATE:20240105
END:VTODO
END:VCALENDAR

**Expected behavior**
Positive integer values for COUNT to improve conformity with RFC2445.

**Device and version:**
 - Device: SHIFT6mq
 - Android version  Android 10
 - jtx Board version: 2.06.04.gplay
 - Downloaded from: Google Play

**Comment by patrickunterwegs** [comment]
hi @burningT , what was your intention with the recurring entry? To create a task that is never ending or did you set it to end after x recurrences?
Can you reproduce this issue?

**Comment by patrickunterwegs** [comment]
Ok, I found an issue where the count could be set to -1, obviously it happens when you set the recurrence rule to never ending and then you edit the entry again, the count gets set to -1. I'll provide a fix soon.
