### ISSUE TITLE
[BUG] Reappearing Description Content after deleting it

### ISSUE THREAD

**Issue by basings** [TechbeeAT/jtxBoard#1203]
**Describe the bug**

Content of Description reappears after deleting it.

Either the task is created within a widget or the app must be closed and reopened between creating the task and deleting the content for the effect.

I discovered the bug by using the auto category feature and trying to delete the description content in order to have a more compact list view.

**To Reproduce**

content stays deleted.

**Device and version**
 - Device: GrapheneOS
 - Android version: Android 13
 - jtx Board version: 2.07.00.ose (207000009)
 - Downloaded from: github / obtainium

**Comment by patrickunterwegs** [comment]
Hi @basings , you mean the quick add dialog from the list? And this would only happen when you close the dialog through the back-button? Or do you mean something else?

**Comment by basings** [comment]
![Screenshot_20240208-165623](https://github.com/TechbeeAT/jtxBoard/assets/92867705/bbb04b69-66d2-4743-abed-5fee966ae0dc)

**Comment by patrickunterwegs** [comment]
Hi @basings , I don't understand how you make the description re-appear, neither from the description, nor from the screenshot. Can you give more details or make a short video?

**Comment by basings** [comment]
https://github.com/TechbeeAT/jtxBoard/assets/92867705/cf2f9976-4b84-4850-b970-8bae176c9476

**Comment by basings** [comment]
You have to reopen the app between creating the task and deleting the content. It doesn't happen if you only reopen the task after creating it.
