### ISSUE TITLE
[Feature] New filter: Without due date

### ISSUE THREAD

**Issue by keunes** [TechbeeAT/jtxBoard#1208]
**Is your feature request related to a problem? Please describe.**

I have too many tasks so I need to filter. Tasks that are due far in future are the ones I want to hide, without losing sight on tasks which have no date (and would thus never ever appear in future).

**Describe the solution you'd like**

Add a 'Without due date' filter option, so that I can activate it alongside 'Overdue' and 'Due within 7 days'.

**Describe alternatives you've considered**

Allow filters to be negative, e.g. "NOT X (e.g. overdue), but thst would be complex to do in the UI plus I don't even think that would help me.

**Additional context**

**Your current device and version**
 - Device: [e.g. Samsung Galaxy S22]
 - Android version: [e.g. Android 11]
 - jtx Board version: 2.07
 - Downloaded from: F-Droid

**Comment by patrickunterwegs** [comment]
Hey @keunes , this is actually a bug, I have refactored the UI a bit lately and this filter got kind of lost in the UI. I will add it again.
