### ISSUE TITLE
[BUG] In some cases location is not automatically assigned

### ISSUE THREAD

**Issue by HendriXML** [TechbeeAT/jtxBoard#1209]
**Describe the bug**
In some cases gps location is not automatically assigned:
- Using widget to create a Jounal item
- Using (txt) url intent
both seem to use the same dialog.

P.S.
I would like create a Journal item using Tasker and an (url) intent with minimal effort in the "field". Both location and time (and a #category) are needed, details will be added back home.

**Comment by patrickunterwegs** [comment]
Thanks @HendriXML , I'll check

**Comment by patrickunterwegs** [comment]
I have made a fix for that. But now it would be required to  set the location permission to "when using this app", so the "ask every time" option would not work anymore. I hope that's okay.
