### ISSUE TITLE
[Feature] Filter / Hide Read-only / specific subscriptions

### ISSUE THREAD

**Issue by keraldi** [TechbeeAT/jtxBoard#1215]
**Is your feature request related to a problem? Please describe.**
I'm providing my calendar (including tasks and notes) to other people. Upon setting up a device for one such person, I noticed that the view is already cluttered with my personal tasks, notes and journal entries. While I don't mind them seeing my notes, I wanted to hide my entries in order for the view to not be overwhelming (and most tasks serve no purpose even if visible to other people). 
While it is possible to filter for specific categories (for example 'Local'), the filter would also exclude a new category made by the user (for example upon creating a new Calendar+Tasks in Nextcloud). 

**Describe the solution you'd like**
I can think of three viable solutions for my specific use case:
1. Allow the filter to explicitly exclude categories (Currently, if no criteria is set in the filter, there is no filter. Allowing to explicitly exclude my categories from showing would not impact future additions by the user) 
2. Filter read-only/writable (tasks, calendar entries and notes I'm sharing are usually but not always only writable by myself) 
3. Allow hiding specific subscriptions (similar how it is possible to hide categories/subscriptions in calendars, for example in Etar) 

**Describe alternatives you've considered**
See above. I can think of no other alternatives and proposed alternatives are equally useful in my opinion. 

**Additional context**
Not possible upon creation. Need to think up a good way to conceptualize an example. 

**Your current device and version**
 - Device: Google Pixel 5, Samsung Tab A7 (2020, SM-T500)
 - Android version: 13, 10
 - jtx Board version: 2.07.11.ose (207010011)
 - Downloaded from: f-Droid

**Comment by patrickunterwegs** [comment]
Hi @keraldi , 

> Allow the filter to explicitly exclude categories (Currently, if no criteria is set in the filter, there is no filter. Allowing to explicitly exclude my categories from showing would not impact future additions by the user)

You can do this already in the filter settings of the list. On the right side there's another button that switches between ALL, ANY or NONE of the selected entries.

> Filter read-only/writable (tasks, calendar entries and notes I'm sharing are usually but not always only writable by myself)

I will consider adding something like that

> Allow hiding specific subscriptions (similar how it is possible to hide categories/subscriptions in calendars, for example in Etar)

You can also do this in the filter settings by filtering specific collections or accounts!

**Comment by keraldi** [comment]
Thanks for the reply and explanation, that really helps!

**Comment by patrickunterwegs** [comment]
> Filter read-only/writable (tasks, calendar entries and notes I'm sharing are usually but not always only writable by myself)

Hi @keraldi , I thought about this one again. I'm not sure if it's worth it adding another filter option for this. Basically you can already filter collections and accounts. It would be easy to select only writeable collections or the other way round, this selection could also be saved in presets. 
What do you think? Or would you still see the need for such a filter option?

**Comment by keraldi** [comment]
Accounts being filterable elimiate the *need* for filtering read/write. I don't think that having multiple different accounts that someone wants to quickly filter for read/write access is a use case that occurs often.

Since I haven't met with the person I set jtxBoard up for since, I cannot evaluate whether I'd still have some personal considerations but I would be absolutely fine with closing the issue.

Personally however, I get way into over-engineering stuff and filtering out by read/write access is something I would definitely do if I had that specific use case with multiple accounts.

**Comment by patrickunterwegs** [comment]
Thanks @keraldi , let's close it for now. If you fee like the need gets stronger or other users have a valid use case, then let's re-open and check again 😉

**Comment by rasos** [comment]
I also was looking for a quick way to hide some task collections coming with calendars that I am syncing with DavX5. Tried wiping collections. Checked settings if there is an unsubscribe option. Finally found this issue explaining that it can be easily solved with filters. That works for me.
