### ISSUE TITLE
[Feature] Publish release notes such that they're picked up by F-Droid

### ISSUE THREAD

**Issue by keunes** [TechbeeAT/jtxBoard#1222]
**Is your feature request related to a problem? Please describe.**

Not really. I just curious with each update what is new.

**Describe the solution you'd like**

Save the release notes such that they are displayed in F-Doid's "what's new" section, like such:
![Screenshot_20240217-001436.png](https://github.com/TechbeeAT/jtxBoard/assets/11229646/27d2d374-3996-4969-a3ea-04ff76bf7cb9)

**Describe alternatives you've considered**

N/A

**Additional context**

Info about F-Droid metadata processinflg: All_About_Descriptions_Graphics_and_Screenshots

**Your current device and version**
 - Device: [e.g. Samsung Galaxy S22]
 - Android version: [e.g. Android 11]
 - jtx Board version: Version: 2.07.01.ose (207010011)
 - Downloaded from: F-Droid

**Comment by patrickunterwegs** [comment]
Hi @keunes , 
basically it is just a bit cumbersome to copy-paste the release notes all the time to a specific text file that f-Droid needs. So more than a year ago I stopped doing this and so far nobody else complained 😉 Additionally you can see the release notes within the app in the about screen. 
However, I'll check if there's maybe a better automation in the meantime and copy the release notes also in the f-Droid folder.

**Comment by patrickunterwegs** [comment]
Release notes are now provided for the upcoming release and hopefully processed correctly by f-Droid 👍

**Comment by keunes** [comment]
Awesome, thanks!
