### ISSUE TITLE
[Feature] Widget: option to apply filters & grouping from filter presets

### ISSUE THREAD

**Issue by keunes** [TechbeeAT/jtxBoard#1230]
**Is your feature request related to a problem? Please describe.**

I've just set up filter presets to my liking, and need to redo that for the widget that I'm adding to my home screen.

**Describe the solution you'd like**

At the top of the Filter and Group/Sort screen, add some way (e.g. a button) to apply existing presets.

**Describe alternatives you've considered**

N/a

**Additional context**

**Your current device and version**
 - Device: [e.g. Samsung Galaxy S22]
 - Android version: [e.g. Android 11]
 - jtx Board version: Version: 2.07.01.ose
 - Downloaded from: F-Droid

**Comment by patrickunterwegs** [comment]
Hi @keunes , this should already be possible, the filter presets also save the order/grouping. Or do I misunderstand something?
Just note that presets are saved per module (journals, notes, tasks).

**Comment by keunes** [comment]
DOH, I missed that, sorry. It's not clear/visible from the UI that it also covers grouping, but it's perfect it does.

Thanks!
