### ISSUE TITLE
[Feature] Group by sorting

### ISSUE THREAD

**Issue by balporig** [TechbeeAT/jtxBoard#1251]
**Is your feature request related to a problem? Please describe.**

Sometimes is useful to be able to sort the `Group by` grouping titles by the grouping property (category, resource ...) itself. Instead, right now, they are only sorted by items/subitems order from  `Order by` option

**Describe the solution you'd like**

Optional `Acending` `Descending` sorting options in `Group by`

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Your current device and version**
N/A

**Comment by patrickunterwegs** [comment]
Hi @balporig , 
sorry for the late reply. 
I will check this out. What I would like to do is to use the primary sort order and lock it to the grouping. Then you can always choose if you would like to order the groups ascending or descending. The entries can then still be sorted through the secondary sort order.
