### ISSUE TITLE
[Feature] Allow interaction 

### ISSUE THREAD

**Issue by logolive** [TechbeeAT/jtxBoard#1268]
**Is your feature request related to a problem? Please describe.**
I often write checklists (like shopping lists) in my notes. Then, when I am shopping, I would like to tick the items off. This is quite slow when editing the markdown source directly.

**Describe the solution you'd like**
I would like to be able to interact with the rendered markdown and tick/untick checkboxes. Ideally, this would update the underlying markdown and then save the note. The feature should be easy to use without accidentally opening the note for editing (which is what happens right now when tapping).

**Describe alternatives you've considered**
Currently, go over the lists repeatedly in my head until I am convinced that I have everything. Alternatively, I could delete the items from the checklist, which is however not an option if I have to retain the full list, thus requiring a copy of the note.

**Your current device and version**
 - Device: Fairphone 4 5G
 - Android version: 13
 - jtx Board version: 2.07.01.ose (207010011)
 - Downloaded from: f-Droid

**Comment by patrickunterwegs** [comment]
Hi @logolive , sorry for the late reply. 
Markdown support in jtx Board is meant to support some basic formatting, checkboxes are displayed, but not functional. 
The app follows a more structured approach, if you would like to add subtasks or notes to another entry, there is the specific functionality to create and link entries as subtasks. If I would now also allow checkboxes from Markdown, this would contradict with the structured approach and would cause more confusion than benefit. If Markdown is your preferred way, then I believe other apps are more suitable. 
I hope you understand!
Regards, 
Patrick

**Comment by mcepl** [comment]
Could you please reconsider this ticket?

1. My wife and I would like to use Fastmail and jtxBoard to share a shopping list (via a shared CalDAV list, for obvious convenience). The easiest solution we’ve found so far is to maintain an enormous list of over 170 items, toggling them on and off as needed. I’ve written a Python script to generate all these subtasks from a Markdown file, and it works technically, but managing a long-term task with 170+ subtasks is awkward. While I can hide completed items, the experience is still unpleasant. A single Markdown list with clickable checkboxes would be far more convenient.

   In fact, you’re almost there! The only change I’d need is a click handler to toggle the status of an item. The display works perfectly when the value is edited manually, but manually editing those tiny checkboxes in Markdown (especially via finger press) is a frustrating experience.

2. Even if you don’t add that click handler, could I request a feature to convert text from the clipboard into a list of subtasks when pasted? Trello offers this, and it’s incredibly convenient for situations like ours, where the list of subtasks often comes from unstructured sources. It would be *extremely* useful to have this functionality.
