### ISSUE TITLE
[BUG] Widget unable to create new task after boot

### ISSUE THREAD

**Issue by basings** [TechbeeAT/jtxBoard#1271]
**Describe the bug**

Right after boot I am unable to add a new task from the widget.

**To Reproduce**

The bug only happens on the first app launch after the device booted.

** Steps to reproduce the behavior **

- set jtx as widget

1. boot device
2. press on `+` to. "Summary/ Description"-box appears with a blinking cursor
3. Typing in the "Summary" box. No letter appears.

- You can circumvent it by clicking on the calendar box above first.
- The same behavior for notes.
- the second time the popup is opened, the bug does not happen.
- It does not happen in the app. And when the app was opened first, it does not happen either.

**Expected behavior**

Letters appear in box.

**Screenshots**
![Screenshot_20240315-074313](https://github.com/TechbeeAT/jtxBoard/assets/92867705/78e3eb8e-ce6f-4c76-bd4c-e6bdcfbef5ee)
The above screenshot shows the widget

**Device and version**
- Device: Pixel 6
- Android version: GrapheneOS - Android 14
- launcher: kvaesitso
- jtx Board version: 2.07.02-beta26.ose
- Downloaded from: Github

**Comment by patrickunterwegs** [comment]
Hi @basings , 
thank you for the bug report. 
Actually I couldn't reproduce this issue. Are you sure it happens on your device only when you restart your device? And it doesn't happen when you kill the app and then add a new entry from the widget (which would then recreate the whole app again)?
And to get it right, the dialog appears to enter a new entry, also the keyboard appears, also the cursor appears. It's only when you start typing on the virtual keyboard, that the entered characters don't appear in the text box. Is that right?

**Comment by basings** [comment]
@patrickunterwegs 

Yes, the bug happens each week as I have to reboot the device each week for updates (Grapheneos). I have confirmed it multiple times prior to reporting.

When I force stopp jtx, pressing a button of the widget does nothing. I have to start the app manually in order for the widget to function.

Your description is exactly what I experience.

**Comment by patrickunterwegs** [comment]
Hi @basings , thanks!
I have reviewed the code, I still can't figure out what could cause this issue. 
Which keyboard provider do you use? Do you have the chance to try another keyboard provider to check?

**Comment by basings** [comment]
Great idea. I wonder why I didn't think of changing keyboards. I use florisboard beta.
I changed it back to grapheneos keyboard. It works. And it works with florisboard beta. Bug is gone.

**Comment by patrickunterwegs** [comment]
Thanks for the update @basings !
I will still review to code to maybe find out why in some cases/on some devices the widget doesn't react after reboot.
