### ISSUE TITLE
[Feature] Icons have different heights

### ISSUE THREAD

**Issue by dilyanpalauzov** [TechbeeAT/jtxBoard#1288]
The surrounded areas at the top should all have the same height.  The read-only and URL icons are tinier in jtxBoard 2.07.01.ose. 

![Screenshot_20240324_163215](https://github.com/TechbeeAT/jtxBoard/assets/4992947/549bdd13-a9ad-4985-a365-e03ea128b5b2)

**Comment by patrickunterwegs** [comment]
Thanks, I'll check

**Comment by dilyanpalauzov** [comment]
Is it intentional that the date on the screenshot has a different colour?

**Comment by patrickunterwegs** [comment]
> Is it intentional that the date on the screenshot has a different colour?

Yes, the idea was to have the date information visually a bit distinct, so I assigned the "secondary container color" to the date fields.  It looks good, when the secondary color is more distinct to the primary color, but this is up to  the system (and the dynamic colors). 
It seems like in most cases there is no visual distinction and it just looks a bit off.
I will remove also the secondary container color for the dates.
