### ISSUE TITLE
[Feature] Bulk sub task creation

### ISSUE THREAD

**Issue by t-h-e** [TechbeeAT/jtxBoard#1312]
**Is your feature request related to a problem? Please describe.**

Creating multiple sub tasks can be tedious, especially if one is writing a shopping list and just copying one item at a time from a recipe.
It would be nice to copy a list of ingredients and a sub task is created for each one of them.

Currently when pasting a multi-line text into a text field that creates a sub task, a single sub task is created with the multi-line text as summary.

**Describe the solution you'd like**

When pasting text in a text field to create a sub task and if the text contains multiple lines, jtx board should offer an option to create a sub task per line.

**Describe alternatives you've considered**
🤷
I'm open for other suggestions.

**Additional context**
-

**Your current device and version**
 - Device: Google Pixel 8
 - Android version: Android 14
 - jtx Board version: 2.07.02.ose
 - Downloaded from: f-Droid

**Comment by t-h-e** [comment]
I have created a working sample implementation. Let me know what you think: https://github.com/TechbeeAT/jtxBoard/pull/1313

**Comment by patrickunterwegs** [comment]
Hi @t-h-e , thank you :-) I'll have a look soon, I'm a bit busy right now with a bug, but I'll check soon!
