### ISSUE TITLE
[Feature] Rename "Kanban view" as "Status view"

### ISSUE THREAD

**Issue by rogercreagh** [TechbeeAT/jtxBoard#132]
Currently the "Kanban view", which can apply to all item types, is using the STATUS property of the items for the columns. 

As noted in #94 and #127 this is limited to specific values which can't be changed. Also the view doesn't allow drag-dropping of items to change the status (column), or an alternative quick method of moving the item to a different column, which is pretty essential for a proper Kanban view.

Pending development of a proper Kanban view for ToDos only, I suggest renaming the current "Kanban View" as "Status View" to avoid confusion.

**Comment by patrickunterwegs** [comment]
Hello @rogercreagh , I don't agree with you here. The current board is a valid Kanban-Board based on the STATUS property. The current view allows drag and drop from one column to the next (but does not allow jumping over a column). The restriction to the existing STATUS property doesn't make it less Kanban. In the future we can rename the board maybe to "Kanban by status" when there is another option, but for now I really want to leave the naming as it is!

**Comment by rogercreagh** [comment]
Ok, we'll agree to differ on this one, I think my main concern is that Kanban doesn't seem a relevant term for Journals or Notes - people who use those have probably never heard of Kanban so it is a confusing term, whereas "Status view" is clearly going to organise the view by status, which is more comprehensible.

Could we leave the feature request open to see if it garners any support, with the caveat that "Kanban view" could remain for ToDos for now pending a better Kanban implementation.

**Comment by rogercreagh** [comment]
PS drag and drop didn't seem to work in Kanban view on my tablet, but trying it repeatedly I find that a fast swipe to the next column does work. Holding with you finger preparing to drag simply opens the item. So "Swipe to move item to adjacent column" rather than drag'n'drop (which perhaps works if you are using an emulator with a mouse instead of a finger)?

**Comment by patrickunterwegs** [comment]
Hey @rogercreagh , I don't want to leave issues open for discussion, but I have created a discussion with a poll so users can follow up on this: 
https://github.com/TechbeeAT/jtxBoard/discussions/145

Regarding the drag and drop: This will need a refactoring anyway sooner or later. I just hope that jetpack compose will provide a draggable container soon, that would for sure facilitate things a lot. So I'd like to wait a bit more and make a proper solution instead of implementing workarounds there...
