### ISSUE TITLE
[Feature] Set default tag for new tasks created via widget

### ISSUE THREAD

**Issue by alphaTECH-Aus** [TechbeeAT/jtxBoard#1338]
**Is your feature request related to a problem? Please describe.**
You can filter tasks for the Android widget by tag/category, however creating a new task does not allow a default tag/category to be applied to tasks created via the widget. You need to go save & edit then set the tag from within JTX Board.

**Describe the solution you'd like**
An option to set a default tag for tasks created via the Android widget.

**Describe alternatives you've considered**
None.

**Additional context**
This would be very handy because I could then have multiple JTX Board widgets showing different task categories across multiple home screens (eg. work tasks, shopping list, social club to-do, etc.)

**Your current device and version**
 - Device: Galaxy S20
 - Android version: Android 13
 - jtx Board version: 2.07.01
 - Downloaded from: Play Store

**Comment by patrickunterwegs** [comment]
Hi @alphaTECH-Aus , 
thanks for your proposal!
I get the idea. I'm just not sure yet how to make this configurable, I mean, how it could look like in the UI of the widget config. 
But would you prefer that a category is selected or maybe that the title of the widget gets set as a category?

**Comment by alphaTECH-Aus** [comment]
Hi Patrick,

It could be as simple as a toggle for "create new tasks with currently selected filters". So any category filters you've applied to the widget will be set as categories on any tasks created through the widget.

That may be quite limited for some people though, they might mix multiple categories together inside one widget. So maybe a "default category for new tasks created via this widget" selection under the General options would satisfy more users.

**Comment by patrickunterwegs** [comment]
Thanks @alphaTECH-Aus !
At the end, I guess a selection will be the same effort. On the UI would then still allow the selection of only one category (to not overcomplicate the thing). Or would you see the need for more?

**Comment by alphaTECH-Aus** [comment]
Hi Patrick,

Personally I do not have a need for more than one category assigned for new tasks per widget right now but I can see how someone else may find it useful.

**Comment by alphaTECH-Aus** [comment]
Thanks Patrick :)
