### ISSUE TITLE
[Feature ] Order done (sub-)tasks last when ordering by created date

### ISSUE THREAD

**Issue by bobykvv** [TechbeeAT/jtxBoard#1339]
There was a discussion on close topic already, however I think it didn't come to the end...

Problem is that I (like many others, I bet) use subtasks for creating something like shopping lists, and if one's been doing that for some time, usually newer positions are in a higher priority for the creator. And I find it convenient if they stay at the top of subtasks. But I'd prefer completed subtasks to be moved to the end of the list. OR be able to turn on a filter to make them disappear/appear like we have in the "main" tasks. 

For now I don't see a way to do that in the application. Or I missed something? 
Either I can sort them out in a way that I see newer subtasks on the top, but those completed also stay on the top, or all of them are sorted in a reverse order when oldest subtasks are on top and newest appear in the end together with completed.

P.S. Anyway, the app is absolutely great! Kudos to the author!

_Originally posted by @bobykvv in https://github.com/TechbeeAT/jtxBoard/discussions/1335_

**Comment by patrickunterwegs** [comment]
Hi @bobykvv !
Sorry for the late reply!
I'm super busy lately. 
Basically there is already such a segregation for done and open tasks when you order by start or due date (where done tasks always appear below the open ones). This is currently not done, when you order by created date. I can add this also there. This would change the behavior for all users, but I think it can be accepted. 
I assume this is exactly what you'd need, right?

**Comment by bobykvv** [comment]
Yes, I mean this, I think...  Just in case - not for tasks, but for subtasks actually. Please, do it - it seems pretty logic, isn't it? And both for "Notes" and "Tasks" modules.

**Comment by patrickunterwegs** [comment]
Yes, I'll make the change, but the logic will apply for all elements that are sorted by the created date. But still you can choose for each list individually how you'd like to sort the task, subtasks and linked noted!

**Comment by patrickunterwegs** [comment]
Hi @bobykvv !
If you would like to try the implementation, you can check it either from the Google Play beta channel or here from GitHub 😉

**Comment by bobykvv** [comment]
Works as expected. Thank You! Well done!
