### ISSUE TITLE
[Feature] Add quick add item function as alternative to search bar in list view

### ISSUE THREAD

**Issue by patrickunterwegs** [TechbeeAT/jtxBoard#135]

**Comment by rogercreagh** [comment]
Isn't there already a quick add item function in the list view - the pen'n'lightning icon? Why mess with the search bar?

**Comment by patrickunterwegs** [comment]
Yes, the functionality already exists though the quick add button. Actually I was thinking about removing this dialog, but it has a few additional functions (like speech to text, option to choose collection or module...)

I would still give the user the choose of the top app bar behavior to either act as a search bar or as a new entry bar, which can also quickly be changed in the overflow menu (above the options to choose the view modes). 

I think it does speed up things a little bit, especially if you want to add multiple entries in a row!
