### ISSUE TITLE
[Feature] Get alarms for tasks that have been synced to your device

### ISSUE THREAD

**Issue by t-h-e** [TechbeeAT/jtxBoard#1362]
**Is your feature request related to a problem? Please describe.**
If a task is created somewhere else and a start date is set (not sure about due date, though) and the task is synced to jtxBoard, no alarm is created, even though "Automatic alarm" is set to "On start".

**Describe the solution you'd like**
Alarms should be created for tasks that are synced to jtxBoard.

**Describe alternatives you've considered**
🤷 

**Additional context**
My relevant settings in jtxBoard
- `Automatic alarm` is set to `On start`
- `Sticky alarms` is activated
- `Tasks` is the only active module

**Your current device and version**
 - Device: Pixel 8
 - Android version: Android 14
 - jtx Board version: 2.07.04.ose
 - Downloaded from: f-Droid

**Comment by t-h-e** [comment]
@patrickunterwegs Please let me know if this should work already or if this request makes sense.
If you point me in the right direction, I can also implement it. Although I have seen that you are currently [refactoring alarms](https://github.com/TechbeeAT/jtxBoard/pull/1317), so maybe I should wait until the refactoring is merged.

**Comment by patrickunterwegs** [comment]
Hey @t-h-e ! 
Thanks for the bug report and offer to check it! Indeed I am not happy with how I implemented the alarm handling in the first place. Please let me further review this with the refactoring branch that I have started and then let's talk again!

**Comment by patrickunterwegs** [comment]
Just an addition: Basically I would have expected this to work. If it doesn't work for you, there might be a general issue...

**Comment by patrickunterwegs** [comment]
Hi @t-h-e , sorry that it took a bit, now I'm done with the refactoring, I also just tested if the alarms work also with your specific setting, all looks good. I'm going to merge this change now and provide a new beta-version soon. I'd be happy if you could also have a look at it and maybe give some feedback once it's available! =)
