### ISSUE TITLE
[BUG] Recurrent task appears as multiple tasks.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [TechbeeAT/jtxBoard#1363]
**Describe the bug**

When I synchronized my tasks from NextCloud, I expected my recurrent tasks to be rendered as such (like Tasks.org does). However, they were instead rendered as multiple tasks.

**To Reproduce**

1.  Install https://github.com/bitfireAT/davx5-ose/releases/download/v4.3.16.1-ose/davx5-ose-4.3.16.1-ose-release.apk
1.  Install https://github.com/TechbeeAT/jtxBoard/releases/download/v2.7.5/jtxBoard-v2.7.5.apk
1.  Synchronize https://wim.nl.tab.digital/remote.php/dav/calendars/rokejulianlockhart/3de72895-d345-4ac4-8eec-1418e857ba7e/

#### **Screenshots**

> ![Screenshot_20240424-203214](https://github.com/TechbeeAT/jtxBoard/assets/42837531/20f8243c-4423-4f09-b84d-aa1219266899)

#### **Device and version**

 - Device: Fairphone FP5
 - Android version: Android 13, build FP5.TT3L.A.106.20230918
 - jtx Board version: https://github.com/TechbeeAT/jtxBoard/releases/download/v2.7.5/jtxBoard-v2.7.5.apk from https://f-droid.org/repo/at.techbee.jtx_207040005.apk
 - Downloaded from: https://f-droid.org/packages/at.techbee.jtx/

**Comment by patrickunterwegs** [comment]
Yes, that's how it's implemented. As it's based on iCalendar, I have made recurring tasks like recurring events where you would also expect the repeating event to appear e.g. ever year or every day. I'm not sure how tasks.org did it, but if it suits your use cases better, then rather stick with tasks.org. I don't see why we should just do exactly the same here.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/TechbeeAT/jtxBoard/issues/1363#issuecomment-2075743007

@patrickunterwegs, the reason that I want repeating tasks to display as one task is because for a task which repeats indefinitely, I have a veritable multitude of duplicates present, rendering me unable to see any other tasks. I'm really surprised that that's expected behaviour.

**Comment by patrickunterwegs** [comment]
As I said, the standard is based on a calendar idea. When you have a birthday that recurs yearly, would you like to see only the next birthday or the birthday in every year in the future? It's the same for tasks, when you need to bring out the trash every week, it's still something you need to do every week, a new task just doesn't pop up. 
In your case you can still activate the option to show only the next upcoming task from the menu.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/TechbeeAT/jtxBoard/issues/1363#issuecomment-2131386699

@patrickunterwegs, that option should indeed work. Thanks.

Perhaps consider collapsing task entries for tasks which recur past an arbitrary frequency (or enable that option by default, although the issues there are forseeable).
