### ISSUE TITLE
[Feature] Enumerate all tasks during sync, not just the next few.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [TechbeeAT/jtxBoard#1364]
#### **Is your feature request related to a problem? Please describe.**

When I synchronized my tasks, the {synchronized}/{total} count was basically {synchronized}/{synchronized+5} the entire time, because it enumerated merely a few tasks ahead, then synchronized them, rather than the entire count.

#### **Describe the solution you'd like**

Instead of synchronously enumerating all tasks before synchronization (which would be a waste of time in many situations) asynchronously enumerate all whilst synchronizing, because the superior speed of enumeration means that the total value shall be enumerated before synchronization completes.

#### **Describe alternatives you've considered**

*Optional* synchronous enumeration before synchronization.

#### **Additional context**

I have 4692 tasks, according to JTX Board.

#### **Device and version**

 - Device: Fairphone FP5
 - Android version: Android 13, build FP5.TT3L.A.106.20230918
 - jtx Board version: https://github.com/TechbeeAT/jtxBoard/releases/download/v2.7.5/jtxBoard-v2.7.5.apk, from https://f-droid.org/repo/at.techbee.jtx_207040005.apk
 - Downloaded from: https://f-droid.org/packages/at.techbee.jtx/

**Comment by patrickunterwegs** [comment]
Hello @RokeJulianLockhart , the two numbers on the top right don't indicate the number of synchronized tasks vs. the number of total tasks, but rather the number of displayed tasks (with the current filter settings) vs. the number of total tasks.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/TechbeeAT/jtxBoard/issues/1364#issuecomment-2075737923

@patrickunterwegs, in which case, how were both counts increasing, as aforexplained?

**Comment by patrickunterwegs** [comment]
@RokeJulianLockhart I don't quite understand your description, what do you actually mean with enumerate here?
I have seen that the counter has a problem when dealing with many recurring tasks, I still need to investigate this.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/TechbeeAT/jtxBoard/issues/1364#issuecomment-2131385748

@patrickunterwegs, I have a lot of recurrent tasks, so that would make sense. In essence, all I mean is that the total shouldn't increase alongside the displayed task counter, otherwise the actual progress rate isn't increasing, which is confusing.
