### ISSUE TITLE
[Feature] Select color additionally from pool of already used colors

### ISSUE THREAD

**Issue by bobykvv** [TechbeeAT/jtxBoard#1368]
When coloring notes or tasks to distinguish them, I use colors to combine them in some groups. If there are many of them, default colors are not enough sometimes and we have to choose some additional colors from the colour wheel. In this case it's almost always not possible to choose exactly same color twice. I suggest to add a field with HEX color code near the wheel and, even better, then make chosen additional color appear in the list of default colors to use it again.

**Comment by patrickunterwegs** [comment]
Hey @bobykvv , thanks for your proposal. The color picker depends a bit on a good library, there are not so many. But showing the already used colors shouldn't be a problem. This would anyway also solve the problem, right?

**Comment by bobykvv** [comment]
> Hey @bobykvv , thanks for your proposal. The color picker depends a bit on a good library, there are not so many. But showing the already used colors shouldn't be a problem. This would anyway also solve the problem, right?

Yes, sure.
