### ISSUE TITLE
[BUG] Slow rendering of lists

### ISSUE THREAD

**Issue by ivan-avalos** [TechbeeAT/jtxBoard#138]
**Describe the bug**
When opening the app, it takes like six seconds for the to-do list to appear. And then, switching between tabs is slow because of the rendering overhead. I don't remember this happening before the Jetpack Compose refactoring four months ago. I'm not sure if this only happens in my almost five year old phone.

**Steps To Reproduce**
1. Open the app.
2. Wait six seconds for the list to appear, so you can see that it takes six seconds for the list to appear.
3. Switch between tabs and see the sluggishness. (In a GitLab issue you said it was an issue with the tab bar library, but I believe it's actually the lists.)

**Expected behavior**
List rendering is fast.

**Device and version:**
 - Device: Huawei P20 Lite
 - jtx Board version: 2.01.09-rc03.ose
 - Downloaded from: F-Droid

**Comment by patrickunterwegs** [comment]
Hey @ivan-avalos , how many entries do you have roundabout per tab?
I think the other issue that you mention was about the animation when changing the tabs, not about the loading of the list.

**Comment by ivan-avalos** [comment]
7 tasks and 5 notes. I have more tasks, but they are filtered out.

**Comment by patrickunterwegs** [comment]
Hmm, that's strange, and which Android version are you using?

**Comment by ivan-avalos** [comment]
That's missing in the bug template! I'm using Android 11.

**Comment by patrickunterwegs** [comment]
Thanks, I have updated the template, I'll have a look at that specifically with Android 11

**Comment by patrickunterwegs** [comment]
I couldn't reproduce the issue on the emulator, but on an older phone. 

I'll check soon if baseline profiles can help to improve performance:

https://developer.android.com/topic/performance/baselineprofiles/overview

**Comment by patrickunterwegs** [comment]
Hey @ivan-avalos , just a quick update for information: 
I have implemented those baseline-profiles which speeds up the app start in the benchmark on the old device a lot (from 8-10 seconds to less than 2). I hope that will also show a significant speed-boost on your side. I'd appreciate your feedback once the new version is ready to be released!
