### ISSUE TITLE
[Feature] Hide not used functions

### ISSUE THREAD

**Issue by kaulpa** [TechbeeAT/jtxBoard#139]
I don't use journals and notes. I use jtxBoard just for my tasks in combination with DAVx. So from my point of view, the app is overloaded with not used functions ;-)

It would be great, if not used functions, can be hided at least for the tabs journal, notes and tasks. Maybe it's possible to have an even more granular, user configurable input mask.

Hope this feature is easy to implement.

**Comment by patrickunterwegs** [comment]
Hey @kaulpa !
One of the ideas if the app was to support the standard as wholesome as possible. It's actually a constant struggle to find a good compromise between what to show where and how 😉

But can you be a bit more specific? What elements.do you think are too much or should be configurable?

**Comment by kaulpa** [comment]
I understand the need for an app with all posible features. Previously i used OpenTasks to handle my tasks. As it isn't maintained anymore, I gave jtxBoard a try and was I was satisfied.
Now I try to convince my wife to use it aswell, but i fear she'll use the notes instead of the task, which are not synced to my nextcloud.
In my case it would be great to disable and hide journals and notes.

**Comment by patrickunterwegs** [comment]
Ah, okay, so maybe I misunderstood a bit, you're really talking about only the tabs that should be configurable, like to enable and disable the tabs and if there's only one left, not to show it at all, right?

**Comment by rogercreagh** [comment]
Yep, I like this - I don't use ToDos so would welcome the ability to hide that tab leaving just Journals and Notes.

**Comment by patrickunterwegs** [comment]
The current implementation in the pull request would give yothe option to activate journals, notes and tasks in the settings separately. 
At least one option must be active. If only one option is active, the tab bar would not show up. If there are more, the tab bar appears.

Please be a bit patient, this pull request builds on another change that will go into testing soon, but that one needs to stay a while on the Google Play Beta Channel to be sure no major errors occur.

**Comment by kaulpa** [comment]
Thank you very much, that you have implemented this so fast.
I've registered for the google play store beta program. Should it be already available there or did I misunderstand you?

**Comment by patrickunterwegs** [comment]
Hey, I've just put it on the internal channel on Google Play, I'll do some final checks tonight, then it goes to the beta channel. It takes a bit to be approved by Google, but it should be there tomorrow some time during the day 😉
