### ISSUE TITLE
[Feature] Sticky notifications on Android 14+

### ISSUE THREAD

**Issue by max-baz** [TechbeeAT/jtxBoard#1390]
**Is your feature request related to a problem? Please describe.**

Persistent notifications, aka sticky alarms (https://github.com/TechbeeAT/jtxBoard/issues/442, https://github.com/TechbeeAT/jtxBoard/commit/7de336c00af531983bb05f70e3a1365f1b1a59e3) are no longer supported on Android 14+. 

It's super helpful to rely on the notifications to remain in the drawer until the task is done. I'd like a solution that can protect me from accidentally swiping the wrong notification away. 

**Describe the solution you'd like**

Tasks.org decided to treat swipe as "snooze", such that the notification will reappear after a configurable amount of time (one of the options being "instantly"). This sounds like a sane idea to me. 

https://github.com/tasks/tasks/issues/2753

**Describe alternatives you've considered**

It sounds like there's no way anymore to prevent notification from being swiped away, so retriggering notification is probably the only way to solve this.

**Your current device and version**
 - Device: Pixel 7a
 - Android version: Android 14
 - jtx Board version: 2.07.05.ose
 - Downloaded from: f-Droid

**Comment by patrickunterwegs** [comment]
Hi @maximbaz , thanks for the issue report! I will anyway refactor the alarm handling a bit (#1309), there I will also review what to do with the sticky alarms!

**Comment by patrickunterwegs** [comment]
Hi @maximbaz , I finally found the time to work on this. 
To be correct, alarms are still sticky, so if you click on the notification, the notification will stay. What was changed is that indeed you can cancel them. 
In the upcoming implementation I would just trigger all alarms again that were shown before immediately. I guess that will also do the trick, right? I mean, I don't see much sense in a delay like in Tasks.org

**Comment by max-baz** [comment]
Yeah I think that would do the trick, I suppose some people want to snooze a reminder if they know they can't complete this task right now anyway, but personally I don't have that use-case, I only want protection against accidental swipes that cancel notification without completing it, and your solution would be totally solving this problem. 

Thanks for looking into it!
