### ISSUE TITLE
[Feature] Markdown Editing Toolbar 

### ISSUE THREAD

**Issue by patrickunterwegs** [TechbeeAT/jtxBoard#14]
Transferred from https://gitlab.com/techbeeat1/jtx/-/issues/499

**Comment by rogercreagh** [comment]
> Hey ~~ [@rogerco](https://github.com/rogerco)~~ ,
I will follow this up in https://github.com/TechbeeAT/jtxBoard/issues/14
I have a bit of a different approach here (that will have kind of a similar result), so if you are editing the description field and markdown is enabled, I would replace the symbols in the bottom bar with markdown-formatting icons 🙂
Hi Patrick - I'm @rogercreagh on here by the way. What you suggest sounds very like what I saw and would work well I think.
Sorry I've been a bit offline this week for family issues. Will catch up on other issues shortly. Still on 2.00.10 but will update asap.
