### ISSUE TITLE
simplify ui

### ISSUE THREAD

**Issue by kotecky** [TechbeeAT/jtxBoard#1405]
The app does everything it can and covers all aspects of taking notes and managing tasks I could need. An issue is that for a phone the ui is overcrowded and it's rather cumbersome to create a task, for instance.

As a solution, the ui would make use of reordering of the fields (mandatory/always used on top, seldom used below or collapsed or in a collapsed section). 

Alternatively, some fields could be made hidden in the settings. I would make use of it as I never use: all date related, description, categories.

**Comment by patrickunterwegs** [comment]
Hi @kotecky , 
You can do this already, check the button on the bottom left when you edit an entry:

![Screenshot_20240510_081051_jtx Board.jpg](https://github.com/TechbeeAT/jtxBoard/assets/72232737/1f3e5262-b305-4588-87fc-61d32e618f17)
