### ISSUE TITLE
[BUG] unexpected behaviour when adding subtasks to a new task

### ISSUE THREAD

**Issue by burningT** [TechbeeAT/jtxBoard#1408]
**Describe the bug**
When adding subtasks to a new task, erratic behaviour occurs like:
- the subtask is not added at first
- entering it again makes no change
- the app closes unexpectedly
- the subtask appears after a while but its title is scattered over multiple subtasks

**To Reproduce**
1. Create a new task with the widget
2. Enter a name and select "save and edit"
3. Enter some subtasks
4. See the behavior

I am not sure if this is 100 % reliable, however for me it is pretty consistent as it happens pretty often lately.

**Expected behavior**
Subtasks are added fluently and without scattering there titles.

**Device and version**
 - Device: SHIFT6mq
 - Android version: Android 10
 - jtx Board version: 2.07.06.gplay
 - Downloaded from: Google Play

**Comment by patrickunterwegs** [comment]
Hi @burningT , can you tell me how many entries you have in total in the app? How do you add subtasks? Through the subtasks area or through the top app bar?

**Comment by burningT** [comment]
In total there are 804 tasks in my app. I add those subtasks in the subtasks area.

**Comment by thomasfrobieter** [comment]
Same here, but it doesn't matter if it's a new task or not. When I open an existing task and try to add a subtask using the text box at the top of the application, the application closes and the subtask is not added. When I re-open it and try again, it works.

This has happened a few times, but I have not been able to reproduce this reliably.

**Comment by patrickunterwegs** [comment]
Thanks  @thomasfrobieter , @burningT . 
The cause seems to be the scroll, so when a new subtask is entered the app should scroll to the section and the new task. I think something is going wrong in the background, it doesn't seem to be clearly reproducible. 
I will remove this functionality for now. At least this should fix the issue.

**Comment by patrickunterwegs** [comment]
Ok, so I checked it and it doesn't seem to be related to the scrolling, so I'll leave it for now and try something else. 
It is not clearly reproducible, so it seems to be something else. I have another idea that I'll try now.

**Comment by patrickunterwegs** [comment]
I will add it in the next beta and release it with 2.7.9, if you have any feedback after, please let me know.

**Comment by patrickunterwegs** [comment]
Hi, I'm about to upload the new beta on GitHub and Google Play. GitHub will be ready in a few minutes, Google Play probably approved some tomorrow. I'd appreciate if you could give some feedback if the new version fully solves the issue! Thank you!

**Comment by burningT** [comment]
Hi, 

looks like it is solved. Thank you!

 

 

Von: Patrick Lang ***@***.***> 
Gesendet: Mittwoch, 29. Mai 2024 22:43
An: TechbeeAT/jtxBoard ***@***.***>
Cc: burningT ***@***.***>; Mention ***@***.***>
Betreff: Re: [TechbeeAT/jtxBoard] [BUG] unexpected behaviour when adding subtasks to a new task (Issue #1408)

 

Hi, I'm about to upload the new beta on GitHub and Google Play. GitHub will be ready in a few minutes, Google Play probably approved some tomorrow. I'd appreciate if you could give some feedback if the new version fully solves the issue! Thank you!
