### ISSUE TITLE
[Feature] Make edit view options specific to journal/note/todo

### ISSUE THREAD

**Issue by rogercreagh** [TechbeeAT/jtxBoard#141]
Currently you can set which options appear in the edit view. So for example if you are not using resources and url then you can hide them to reduce clutter on the edit screen. This is good.

However the options apply to all edit screens - it might be that you want to hide some things from journal editing and others from todo's. (in fact "Resources" are technically not allowed for Journal entries (and Notes which are undated Jounrals) according to RFC5545 - they only apply for Calendar entries and ToDos)

It would be useful to separately customise the edit screen for each type of item.

**Comment by patrickunterwegs** [comment]
Hey @rogercreagh , yes, in fact that would be better. I'll check that soon!

**Comment by patrickunterwegs** [comment]
Ah, and indeed resources should not be allowed for journals, it seems like I've overlooked that. That's a bit strange in the standard though... However, I'll adapt this, but I'll open a dedicated bug ticket for this! 
Thanks for the heads-up!

**Comment by patrickunterwegs** [comment]
In fact, having different preferences for the modules was already foreseen, but there was a bug in the implementation causing the system to always take the same preferences (for journals). I have fixed that now (hopefully for good). 🙂
