### ISSUE TITLE
Widget never updates

### ISSUE THREAD

**Issue by spatnynick** [TechbeeAT/jtxBoard#1412]
Hi, nice app, unfortunatelly the widget never updates automatically on my device. I have to tap the widgets title, it opens the app and widget is then also updated.

DAVx5 Sync set to 2 hours, with OpenTasks the problem didn't occur. Battery optimizations disabled,

Galaxy S21 5G
Android 13
jtx Board 2.07.06.gplay

br Bohuslav

**Comment by patrickunterwegs** [comment]
Hi @spatnynick , thanks and sorry for the late reply, I'll have a look at it. Basically the widget should update itself, this is a functionality provided by the library. Additionally the widget update is triggered on sync. Are you working mainly in the widget and hardly ever open the app? (Using only synchronized entries from a server)

**Comment by spatnynick** [comment]
Hi Patrick, exactly, I maintain the tasks on my computer and want to have
the widget on handy mainly as a reminder, so I trigger jtxBoard app only
rarely. The tasks are synced every 30 min with DAVx5 - but this sync
doesn't trigger widget update in my case... otherwise it would be sufficient
br Bohuslav

Am Di., 28. Mai 2024 um 11:19 Uhr schrieb Patrick Lang <
***@***.***>:

**Comment by patrickunterwegs** [comment]
Thanks @spatnynick . 
To further narrow this down: When you open the app, does it at least work for some time or does the widget just never udpate?

**Comment by patrickunterwegs** [comment]
Hi @spatnynick !
I have made an upgrade of the widget library and I'll add it to the upcoming beta. As they have made a few improvements, I hope they also made some improvements on the refresh-mechanisms. The code basically looks good, the widget should always get refreshed when an entry gets changed by the sync. However, I have also seen in the emulator that things get stuck for no reason sometimes (which was also hard to reproduce). So I hope that this new widget library version will fix a few things. I'll close this ticket here. It would be great if you could observe this issue further once you have the new version and give some feedback!

**Comment by spatnynick** [comment]
Hi Patrick, thanks a lot! I would like to test it, unfortunatelly I don't
know how to compile it.. I need to install sdk und gradle, right? or could
you possibly compile the apk for me?

Am Di., 28. Mai 2024 um 22:40 Uhr schrieb Patrick Lang <
***@***.***>:

**Comment by patrickunterwegs** [comment]
Hey @spatnynick , sure, no worries, I have just uploaded a new beta: 
https://github.com/TechbeeAT/jtxBoard/releases/tag/v2.7.9-beta01
There you can find the apk to download and install. You could also use tools like Obtainium if you would like to take more apk-files from the developers repository in the future. 

And a hint: if you really want to compile a version, the easiest way is to install Android studio and connect a device. But if you're not familiar with that, I'd recommend to just stick with the apks from Github ;-)

Anyhow, it would be great if you could have a look and test a bit!

**Comment by spatnynick** [comment]
hi Patrick, tested, imho widget works very well in the 2.7.9-Beta01. it's updated regularly, thank you!

**Comment by patrickunterwegs** [comment]
Great, thank you for the feedback =)
