### ISSUE TITLE
[Feature] Option for 24 hour time format

### ISSUE THREAD

**Issue by segln** [TechbeeAT/jtxBoard#1426]
**Is your feature request related to a problem? Please describe.**

It will be great if there is 24 hour time format.

Thanks for your consideration!

**Describe the solution you'd like**

Add "Use 24 hour time format" option on settings.

**Your current device and version**
 - Device: Samsung Galaxy S24+
 - Android version: Android 14
 - jtx Board version: 2.07.08.ose (207080003)
 - Downloaded from: Github releases

**Comment by patrickunterwegs** [comment]
Hi @segln , 
basically jtx Board takes the format from the system setting and should therefore be consistent with all other apps that show a date and a time. Is that not the case for you? Or is there another reason for you why jtx Board should behave differently?

**Comment by segln** [comment]
Ohh... I thought they were separate problems.
Sorry for the confusion.
