### ISSUE TITLE
[BUG] app crashes when opened

### ISSUE THREAD

**Issue by burningT** [TechbeeAT/jtxBoard#1427]
**Describe the bug**
The app crashes reliably when opened. It is unusable.

**To Reproduce**
1. Open app from widget or via android app menu
4. See nothing or see android message about app crash

**Expected behavior**
App starts without crash.

**Screenshots**

**Device and version**
 - SHIFT6mq
- Android version: 10
- jtx Board version: 2.07.07.gplay
- Downloaded from: Google Play

**Comment by patrickunterwegs** [comment]
Hi @burningT , sorry for that issue, while testing I had overlooked that there was an issue on Android 10 and lower... I have uploaded a fix already on Google play already yesterday, just the approval by Google is pending. The beta-version is already fixed. May I ask you to join the beta-program on the Google play store and check if it's also fixed for you?

**Comment by burningT** [comment]
I joined beta and it indeed seems fixed.

**Comment by patrickunterwegs** [comment]
Thanks @burningT , the fixed version is now also on the public channel, feel free to leave the beta program again. Sorry again for the issue.
