### ISSUE TITLE
[Feature] Show notification when alarm is in the past

### ISSUE THREAD

**Issue by alxae** [TechbeeAT/jtxBoard#1462]
**Is your feature request related to a problem? Please describe.**
I set the settings to get a notification when a task starts. When I create a new task that starts today without a time or set an alarm in the past, no notification is triggered.

**Describe the solution you'd like**
I would like to get a notification for all unfinished tasks with an alarm set in the past or corresponding the automatic alarm settings with an alarm triggered in the past. This way I could create a new task and get a notification right away to remind me during the day. As it is now the notification will never get triggered.

**Describe alternatives you've considered**
Set an alarm anywhere in the future.

**Additional context**

**Your current device and version**
 - Device: Redmi Note 9S
 - Android version: Android 14
 - jtx Board version: 2.07.08
 - Downloaded from: Google Play

**Comment by patrickunterwegs** [comment]
Hi @alxae , thanks for your proposal and sorry for the late reply, I've had a bit of a tough time. I'll have a look at it soon!

**Comment by alxae** [comment]
Hi @patrickunterwegs ! Thanks for implementing this feature! I'll give feedback as soon as the release is available and I tested it!
