### ISSUE TITLE
[BUG] Task Color picker in RTL

### ISSUE THREAD

**Issue by alr86** [TechbeeAT/jtxBoard#1481]
**Describe the bug**
Task color picker has problem in devices with RTL system language

**Screenshots**

https://github.com/TechbeeAT/jtxBoard/assets/65030817/47737e9b-0925-492b-a302-a977d70f7f74

**Device and version**
 - Android version: Android 14
 - jtx Board version: 2.7.8.ose
 - Downloaded from: f-Droid
 - System language: Persian

**Comment by patrickunterwegs** [comment]
Hi @alr86 , thank you for the issue report and sorry for the late reply!
Inder that behavior is weird...
I will think about a solution. Basically I'm using another library for this color picker, but it wasn't updated in a while, so I might switch to another one.

**Comment by patrickunterwegs** [comment]
Hi @alr86 , sorry that it took a while, I just replaced the color picker with a new one, that should fix the issue. I'll add this change in the next version!
