### ISSUE TITLE
[BUG] Can't open Board via menu when in any of the other screens

### ISSUE THREAD

**Issue by keunes** [TechbeeAT/jtxBoard#1496]
**Describe the bug**

I can't open Board via the side menu when I'm in any of the other screens.

**To Reproduce**

1. Open the app via the widget 
2. Open the side menu via the hamburger icon
3. Tap on 'Presets'
4. Slide open the side menu
5. Tap on 'Board'

**Expected behavior**

The board opens (tasks in my case, as it's the only module I've enabled).

**Screenshots**

**Device and version**
 - Device: Fairphone 5
 - Android version: Android 13
 - jtx Board version: Version: 2.07.09.ose (207090015)
 - Downloaded from: F-Droid, I think

**Comment by patrickunterwegs** [comment]
Hey @keunes , thanks for the issue report. I've reproduced the problem, it's indeed a bit weird, I'll check how to fix it!
