### ISSUE TITLE
[BUG] Removing Start Date crashes app

### ISSUE THREAD

**Issue by xcy7e** [TechbeeAT/jtxBoard#15]
**Describe the bug**
 App crash when removing start date of a task. 

**To Reproduce**
1. Add or edit a task
2. click on the start date. 
3.untick the left most checkbox for the date.
4.Confirm ("ok") and the app crashes.

**Expected behavior**

**Screenshots**

**Device and version:**
 - Device. Samsung Galaxy a51
 - jtx Board version: 2.01.01.rc12.gplay

**Comment by patrickunterwegs** [comment]
Hello @xcy7e , I can't reproduce your issue according to your description. 
You you reproduce this all the time? Do you have any other dates set? What Android version are you using?

**Comment by xcy7e** [comment]
Hi @patrickunterwegs ,

 yes I can reproduce that all the time.
Android 12.

![2022-12-06-20-51-47-977.jpg](https://user-images.githubusercontent.com/5656573/206008901-42496224-6228-4bc8-b148-18b0b55c1b2d.jpg)

**Comment by patrickunterwegs** [comment]
Thats very strange, I can't reproduce it and I have no clue what could cause this crash. Are you using Google play or another store? Would you mind sharing the exported ics file of this entry? (If it doesn't contain any sensitive information). May I also ask in which timezone you are?

**Comment by xcy7e** [comment]
Hi,

 yes I can reproduce that all the time.
Android 12.

![2022-12-06-20-51-47-977.jpg](https://user-images.githubusercontent.com/5656573/206008901-42496224-6228-4bc8-b148-18b0b55c1b2d.jpg)

**Comment by xcy7e** [comment]
Hi @patrickunterwegs

I found out it also happens if I disable end date beforehand. End date disabling works fine, whereas after that disabling the start date results in crash.

No extra settings, just open the app, add a task, remove start date, crash.

The event itself however is being saved so its not gone when reopening the app.

I am on german timezone. Google play version.

I sent you the ics file via email. It shouldn't contain anything special. 

Hope this helps.
To me it appears to be an exception when calculating the dates, sth like that.
To this topic I had the suggestion, of giving the user more freedom when setting dates, because moving the start date on a later date always requires to set the end date after the desired start date beforehand, which is uncommon usage behaviour. I'd expect to have the end date automatically moved 1 day behind the start date if it's being moved. 

Maybe this bug is related to a missing date in a calculation?

**Comment by patrickunterwegs** [comment]
Hey @xcy7e , thank you! An exception also popped up on the Google Play console today, so probably it's this one and with your explanations it helped me identify the problem! 
So I assume that you have activated the option to automatically set an alarm on start, right? 
The error was, that the code still tries to set the alarm on an empty date - but a date is required - and crashes. 

It would be great if you could confirm that you have activated this option, so we can be sure it's really this issue.
I will upload a new beta-version on Google Play, so if you would like to join the beta-program there, you could see the fixed version already by tomorrow. Otherwise I will publish a new version around the end of the week.

**Comment by patrickunterwegs** [comment]
> To this topic I had the suggestion, of giving the user more freedom when setting dates, because moving the start date on a later date always requires to set the end date after the desired start date beforehand, which is uncommon usage behaviour. I'd expect to have the end date automatically moved 1 day behind the start date if it's being moved.

I have started this discussion/poll here on that topic: 
https://github.com/TechbeeAT/jtxBoard/discussions/19

**Comment by patrickunterwegs** [comment]
@xcy7e one side-note, I have checked your profile, if you are using Nextcloud and if you're maybe searching for an open source challenge, maybe you could consider making a notes/journals frontend for Nextcloud accessing the CalDAV backend (based on the existing tasks web-app for Nextcloud) 😉

**Comment by xcy7e** [comment]
@patrickunterwegs glad you found the bug.
Yes I can confirm the setting "automatic alarm" is enabled "on due".
