### ISSUE TITLE
[Feature] Sortable entries for list and subtasks/notes (drag&drop)

### ISSUE THREAD

**Issue by crahn** [TechbeeAT/jtxBoard#150]
**Is your feature request related to a problem? Please describe.**
The options for this software are pretty excellent.  The ability to nearly graphically construct a customized near sql query from buttons allow non-software engineers to get close to writing sql.

**Describe the solution you'd like**
A way to drag and release to to re-sort the elements in any order might also round out and provide an easy interface to yet one more feature.

**Describe alternatives you've considered**

**Additional context**

**Comment by patrickunterwegs** [comment]
Hey @crahn !
Thank you for your feedback 🙂 

Such an enhancement has been requested a few times. It's basically not that tricky, but jetpack compose (jtx Board uses this UI implementation method) does not offer a drag-and-drop container. That's why I'm hesitating all the time and hoping, that Google will provide such a container soon. 
I'll have a look at that soon once again!

**Comment by crahn** [comment]
I am not sure if this would help... especially if this is just for a surface tablet..  but I thought I would take a shot.

https://github.com/microsoft/surface-duo-compose-sdk/tree/main/DragAndDrop

https://www.rockandnull.com/jetpack-compose-drag-and-drop-list-reorder/

**Comment by patrickunterwegs** [comment]
Thanks for the links @crahn ! 
I have tried the library from the second link, regrettably it doesn't work as expected. The animation jumps around like crazy, it does the thing somehow, but it is not satisfactory at all. I assume the library works best with simpler elements and constructions. 

I will continue experimenting and keep the current experiment in a separate branch.

**Comment by patrickunterwegs** [comment]
Closed old Gitlab reference: 
https://gitlab.com/techbeeat1/jtx/-/issues/137
See also draft by @devvv4ever on Gitlab

Second old Gitlab reference: 
https://gitlab.com/techbeeat1/jtx/-/issues/231

**Comment by jojoob** [comment]
+1 for the manual sorting feature! :)

~Additionally it would be very nice when completed subtasks were displayed at the bottom of the list.~ Just found "order subtasks by... completed" but it always displays completed items at the top regardless of ascending/descending ordering. It would also be nice to have completed items at the buttom regardless of the otherwise selected sorting. Maybe similar to "order by", "then order by". Should I open a new issue for this? 

An idea to work around the drag and drop library problem is to implement up/down buttons. But they WOULD probably clutter the UI...

**Comment by JosephLucas** [comment]
+1 

It's a delight to use jtx Board with Davx5 and Radicale, thank you for developing this great app. However, not being able to sort tasks with vertical drag&drop in the Tasks board (especially the Kanban view) of the mobile phone app is what keeps me from using it. Sorting by editing the priority requires many clicks and it's also kind of tedious to insert a new task between tasks separated by only one level of priority: it seems that it's currently needed to decrement all tasks with lowest priorities.

**Comment by patrickunterwegs** [comment]
I understand the need 😉
For this one it's really about the missing library... I'm checking regularly if something new came up, but so far there is still only one library that is not maintained anymore...

I found this snippet though which I might give a try:
https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/foundation/foundation/integration-tests/foundation-demos/src/main/java/androidx/compose/foundation/demos/LazyColumnDragAndDropDemo.kt

**Comment by pacjo** [comment]
Hey, I found this: https://github.com/Calvin-LL/Reorderable. 

@patrickunterwegs, can you take a look?

**Comment by patrickunterwegs** [comment]
Hey @pacjo !
Thank you very much for the link, this library looks really promising!
I'll have a closer look soon!

**Comment by patrickunterwegs** [comment]
Alright, so this library looks really great. 

I've started now with subtasks, but I'm not sure about how to do it and I'm asking for your feedback. 

![Screenshot_20240110_225206](https://github.com/TechbeeAT/jtxBoard/assets/72232737/2a22f80a-4789-493b-98c1-82e301652278)

Here I have added a drag handle (I think a drag handle should be visible to clearly indicate that it can be dragged).

- When the progress bar is enabled, the text gets almost invisible, that's really not good. Do you see a good alternative?
- I have added the drag handle only for the edit mode, but not when you just display the entry. Would you find it necessary/useful to also drag and drop items in the view mode? Or maybe only there to avoid the first problem?

![Screenshot_20240110_225238](https://github.com/TechbeeAT/jtxBoard/assets/72232737/bfaf8acc-a06f-41f5-9ffe-8a15dd7827f8)


I'd appreciate your feedback!

**Comment by qoheniac** [comment]
I'm thinking that the edit mode is to set up the task and the view mode is to track and view the progress. Therefore, why not maybe hide the checkbox and the progress bar while in edit mode?

**Comment by skwde** [comment]
I do agree with @qoheniac, the checkbox as well as the progress bar are not needed in edit mode.
I also think that it is fine to only have the drag handle in edit mode.

**Comment by pacjo** [comment]
Latest release looks awesome, thanks a lot. Any plans to add drag and drop support for all tasks and not just subtasks? (well, I guess it's a different issue then this one)

**Comment by patrickunterwegs** [comment]
Thanks @pacjo ! =)
About reordering the list itself:
Yes, I just wanted to do it step by step. I'm still not sure how though. The drag handle takes up a lot of space. So I'm thinking if it should be an option to activate drag&drop? Or just make the whole card draggable? But then how would the user know...

**Comment by pacjo** [comment]
> So I'm thinking if it should be an option to activate drag&drop? Or just make the whole card draggable? 

Honestly for me just holding to activate drag&drop would be best, no need for the handle.

> But then how would the user know...

Maybe a one time popup when app is first opened (or in this cas after update). There was a library to do that, but I can't find it. Some alternatives:
- https://github.com/AppIntro/AppIntro
- https://github.com/rubengees/introduction

or something like this in Google clock:
![Screenshot_20240217-175551_Clock](https://github.com/TechbeeAT/jtxBoard/assets/56438628/cbd673d0-0ca5-4160-a98c-dccf1fa2d609)
