### ISSUE TITLE
[BUG] max limit of concurrent alarms 500 reached

### ISSUE THREAD

**Issue by applesoff** [TechbeeAT/jtxBoard#1504]
**Describe the bug**
App crashed after error is generated by DAVx5 regarding a max limit of concurrent 500 alarms being reached. Calling package: at.texhbee.jtx

**To Reproduce**
<!-- Steps to reproduce the behavior:
1. Install jtx board. Connect to radicale server in DAVx5. Wait for error

**Expected behavior**
No errors

**Screenshots**
![Screenshot_20240716_230617_Firefox](https://github.com/user-attachments/assets/7f3ce565-d9b0-4dbd-8a00-177803a5ca5c)

**Device and version**
 - Device: Samsung Galaxy S21
 - Android version: Android 14
 - jtx Board version: 2.9.0 beta 
 - Downloaded from: github

**Comment by patrickunterwegs** [comment]
Hello @applesoff , can you please provide the debug logs from DAVx5?

**Comment by applesoff** [comment]
[davx5-debug.zip](https://github.com/user-attachments/files/16270765/davx5-debug.zip)

**Comment by patrickunterwegs** [comment]
I can't reproduce this issue, but I'll add some code that hopefully catches the error and prevents the crash.

**Comment by applesoff** [comment]
Could it be because I have too many tasks? The count in jtx is 557.
________________________________

**Comment by patrickunterwegs** [comment]
The number of tasks shouldn't matter. jtx Board anyway only schedules the upcoming 10 tasks. So this message is very weird. The problem also hardly ever occurs, you are the second user that approaches me that is affected. 
It seems like it also has to do with specific Android versions... That's why it's also so hard to determine the problem and to provide a fix. I have changed already something and I'll add this change in the upcoming version 2.9.1

**Comment by applesoff** [comment]
Thank you for your help. I'll check back in when I try it. To clarify, I tried the non beta versions on the Google Play store and FDroid with the same results
________________________________

**Comment by patrickunterwegs** [comment]
Hi @applesoff , I have uploaded a new beta-version, you can find it on the Google Play beta channel or here in the releases section. It would be great if you could have a look.

**Comment by applesoff** [comment]
I tried it out. No errors like normal until I tried to edit a task. Before editing journals or notes caused the 500 error in all of my CalDAV instances, now it's a 400 error of only 1 instance. Attached is the logs file. 
[davx5-debug.zip](https://github.com/user-attachments/files/16318123/davx5-debug.zip)
