### ISSUE TITLE
[Feature] Collapse parents in list by default

### ISSUE THREAD

**Issue by BenByes** [TechbeeAT/jtxBoard#1520]
**Is your feature request related to a problem? Please describe.**

Well I have my setting "Expand subtasks in list by default" set to OFF so when I view my list I don't see the subtasks unless I press the subtasks chip. same goes for subnotes too as well as attachments. But the list is still cluttered by each item's parents and I have to collapse each one separately in order to view the matching items in the list only without their corresponding children OR parents.
I still, however, would like the option to expand it manually when needed, of course...

**Describe the solution you'd like**

I'd like having the default option of showing parents for each item to OFF as well as a new setting option "Expand parents in list by default".

**Describe alternatives you've considered**

I switched to the compact view but in the compact view I don't have the parents chip and I still want to be able to quickly view the parents if needed.

**Additional context**

I also think the parents chip should get a bit different decoration in order to quickly distinguish and identify what's a chikdren chip and what's a parents chip, because right now it looks nearly identical and it's hars ro quickly recognized which is which in a long list.

**Your current device and version**
 - Device: [e.g. Samsung Galaxy S22]
 - Android version: [e.g. Android 11]
 - jtx Board version: [e.g. 2.1.0]
 - Downloaded from: [e.g. Google Play, f-Droid, ...]

**Comment by patrickunterwegs** [comment]
Thanks, indeed that was just unfinished code 😉 
I did it now and I'll merge it in the next beta (after releasing the current one)
