### ISSUE TITLE
[Feature] export & import app configuration

### ISSUE THREAD

**Issue by Soakedcardinal** [TechbeeAT/jtxBoard#1537]
**Is your feature request related to a problem? Please describe.**
Okay. It's more like an inconvenience. When setting up a new Android device or transferring data, user is required to reconfigure all app settings which are quite comprehensive including filters, etc.

**Describe the solution you'd like**

I would like to back up the app configuration to a file on my next cloud to then restore my configuration on a new device. 

**Describe alternatives you've considered**
Other Android backup solutions for apps and App data. I don't have one. I have heard of Helium, but I'm not sure I really need it. Most apps that I use have a similar setting such as simple calendar.

**Additional context**
![Screenshot_20240810-093452](https://github.com/user-attachments/assets/9100041d-4786-46e2-bf09-449d2c14068f) See simple calendar export settings and import settings buttons.

**Your current device and version**
 - Device: pixel fold
 - Android version: Android 14
 - jtx Board version: 2.09.00.ose (209000011)
 - Downloaded from: f-Droid

Please forgive me if this feature already exists, i was not enable to locate it in that case. Cheers!

**Comment by patrickunterwegs** [comment]
Hi @Soakedcardinal !
Thank you for your proposal!
I already considered this in #1385, I just need to find to actually do it. Lately I'm just super busy with my regular job. But I hope I can do it soon. So I'm closing this issue here, please follow up in #1385 if you would like to discuss or observe it further!
