### ISSUE TITLE
[Feature] Add support to sync using etesync

### ISSUE THREAD

**Issue by nakibrayane** [TechbeeAT/jtxBoard#1576]
**Is your feature request related to a problem? Please describe.**

Yes, I want to sync my jts board tasks and notes using a self hosted etesync server.

**Describe the solution you'd like**

Implement a way to login to an [etesync](https://www.etesync.com/) server and using for syncing.

There is an [android app for etesync](https://github.com/etesync/android), Which is similar to DAVx<sup>5</sup>, But jtx board don't seem to pick up any collections from it.

**Describe alternatives you've considered**

The android app for etesync exposes your collections to the system CalDAV storage, Maybe jtx board can read from the system CalDAV storage.

**Additional context**

**Your current device and version**
 - Device: Samsung Galaxy A15
 - Android version: Android 14
 - jtx Board version: 2.09.01.ose
 - Downloaded from: APK from github repo (Obtainium)

**Comment by patrickunterwegs** [comment]
Hi @nakibrayan3 !
Thank you for your proposal. Basically jtx Board is open to any sync software to synchronize journals, notes and tasks, but it needs to be implemented on the side of the sync software. So there is a "contract" that defines how another app can communicate with jtx Board (and its database). I don't have the time and resources to work on something like that, but feel free to make such a request with etesync directly. 

The local calendar storage, which is also used by etesync, cannot be used for other components like journals, notes and tasks, there are too many constraints that are optimized for events while other options that the standard offers are just not supported - for which a workaround would be needed that then might not be compatible with other apps.

Regards, 
Patrick
