### ISSUE TITLE
[BUG] Sync Support with Mailcow / SoGo missing in website

### ISSUE THREAD

**Issue by DasKaybee** [TechbeeAT/jtxBoard#1578]
**Describe the Bug**
When I go to https://jtx.techbee.at/sync-with-davx5 and search the Compatibility List in the Bottom for Mailcow / SoGo (Mailcows default CalDAV Solution), I can't find an Entry for it.

**To Reproduce**
1. go to the Website
2. Search for Mailcow or SoGo Mentions

**Expected behavior**
Seeing an Entry for Mailcow vor SoGo Compatibility.
I testet it with my mailcow instance and unfortunately only Tasks are supported. (See attached Screenshot)

**Screenshots**
![Screenshot_20240930-171523_1_1](https://github.com/user-attachments/assets/503b0bb8-4a97-48d4-a0c4-4568f0921df0)

**Device and version**
 - Device: Pixel 4a
 - Android version: Android 14
 - jtx Board version: 2.09.01.ose
 - SoGo version: 5.11.0
 - Mailcow version: Recent Nightly Build
 - Downloaded from: f-Droid

**Comment by patrickunterwegs** [comment]
Hey @kb01guy !
Sorry for the late reply, the last weeks have been a bit too much for me because of my regular job and I had to step back a bit. 
Thanks for the heads-up! I'll update the website :-)

**Comment by patrickunterwegs** [comment]
Done, thanks again =)

**Comment by ToddCrimson** [comment]
Hello, I know this one is closed, but the documentation is still saying that it supports "**notes**" and "**journals**".
But in reality mailcow / SOGo only supports "**tasks**" using DavX and synced to a Calendar.

Feel free to test this.

Your documentation:
https://jtx.techbee.at/sync-with-davx5

![Screenshot_20250103_120613](https://github.com/user-attachments/assets/263f385e-573b-46c5-9f84-c3b90056e958)

**Comment by ilovelinux** [comment]
@ToddCrimson I'd suggest to open a new issue since maintainers may not read comments on closed issues. 

CC: @patrickunterwegs
