### ISSUE TITLE
[Feature] Add filter "Only show series entry with next due date"

### ISSUE THREAD

**Issue by bytewright** [TechbeeAT/jtxBoard#1586]
**Is your feature request related to a problem? Please describe.**
We use a todo list for household tasks with a lot of recurrent tasks. E.g. change bed sheet, clean fridge,... These are added as recurring without limit with different intervals. It is annoying if the board is spammed by tasks which are 10 years out.

**Describe the solution you'd like**
Adding a new filter which only shows one series element which is uncompleted and which start or due date is in the future.

**Describe alternatives you've considered**
The available options for filtering need more manual work like updating current date. No option works with _all_ intervals though.
A list showing the yearly fridge cleanup will always show all monthly tasks as well.

**Additional context**
Using JTXBoard with Davx5 and a selfhosted radicale server.

**Your current device and version**
 - Device: Several in household with a shared todo list
 - Android version: 14
 - jtx Board version: 2.09.01
 - Downloaded from: f-Droid

**Comment by bytewright** [comment]
https://github.com/TechbeeAT/jtxBoard/blob/develop/app/src/main/java/at/techbee/jtx/ui/list/ListOptionsFilter.kt I guess here would a starting point?

**Comment by nakibrayane** [comment]
Won't this still show allot of entries into the future? And you can always hide completed taks, or sort them to the buttom.

**Comment by bytewright** [comment]
Sorry if my wording was unclear: I only want to see the next relevant/open entry of a reoccurring task instead of all future tasks of that series.

**Comment by patrickunterwegs** [comment]
Hi @bytewright , 
in the menu on the top right you can activate the option "limit recurring" which then would only show you all past but only the next occurrence in the future. Isn't that anyway exactly what you're looking for?

**Comment by nakibrayane** [comment]
> Hi @bytewright , in the menu on the top right you can activate the option "limit recurring" which then would only show you all past but only the next occurrence in the future. Isn't that anyway exactly what you're looking for?

Yes, This is exactly what I was looking for.

**Comment by bytewright** [comment]
> Hi @bytewright , in the menu on the top right you can activate the option "limit recurring" which then would only show you all past but only the next occurrence in the future. Isn't that anyway exactly what you're looking for?

yes indeed it is, thanks :)
