### ISSUE TITLE
[BUG] Syncing status to another JTX

### ISSUE THREAD

**Issue by 86ul** [TechbeeAT/jtxBoard#1599]
**Describe the bug**

On my FairPhone 3 with LineageOS 21, I experience with syncing completed tasks to an e-tablet, that all tasks are indeed synced, but not their status. Somehow, these tasks are completed on both NextCloud, and Thunderbird, but not on the JTX app on my e-tablet.

Thus, somehow the syncing of the status happens between FP3 and NextCloud/Thunderbird, but not to my e-tablet.

**To Reproduce**

1. Complete a task
2. Sync it with a preferred server
3. Checking on the server that the item is indeed completed
4. Checking in Thunderbird that the item is indeed completed
5. Checking on the other JTX after syncing that tasks are not completed

**Expected behavior**

Syncing the status over all synced apps.

**Screenshots**

Nope

**Device and version**
 - Device: FairPhone 3 / Onyx Boox Tab Ultra
 - Android version: LOS21 / Android 11 (only soft updates from Onyx possible)
 - jtx Board version: 2.09.01
 - Downloaded from: Fdroid

**Comment by patrickunterwegs** [comment]
Hi @86ul , thanks for the issue report. Would you mind exporting one of those entries that are supposed to be marked as done and upload it here? (Please make sure it doesn't contain anything personal). 
There is actually no clear definition when a task is really done in the standard. It could be done when the progress is set to 100%, when the status is set to completed or when the completed date is set. So I'd have a look if in your case some other app caused a constellation that might not have been foreseen in jtx Board.

**Comment by 86ul** [comment]
Becasue this happens with all completed items within any series, it is maybe easier to recreate a serie yourself. This way, we can figure out if it is my setup (JTX on LOS21, NextCloud/Thunderbird, and JTX on TabUltra/A11) - thus it can not be reproduced, or it is JTX -and it can be reproduced. 

In the main time, I will reproduce this with a new serie without personal info, and share that file here, when it indeed persist.

**Comment by 86ul** [comment]
Although I have not yet been able to do the above, I found also out, that JTX is _not_ the issue, thus you may close this ticket, @patrickunterwegs...

This issue occurs during a syncing issue related to either NextCloud (of my email provider [up-to-date?]), or DAVx5 (uptodate!), or a combo (where?). Forcing both JTX and DAVx5 to resync several times, solves this issue (for now). Thus again, this issue is not an JTX issue.

EDIT: This above is for me true for both completing a task by ticking off the completed box, and sliding the progress bar up to a preferred percentage.
