### ISSUE TITLE
[BUG] Backspace deletes space in front of the word

### ISSUE THREAD

**Issue by b-m-f** [TechbeeAT/jtxBoard#160]
**Describe the bug**
Backspace deletes last char and a previously added space

**To Reproduce**
1. Add description to note
2. Backspace while writing 
3. Sometimes (more than 50%) the last space between words on the current line is deleted.

**Expected behavior**
Only the last char should be deleted

**Device and version:**
 - Device: Fairphone 4
 - Android version LineageOS 20 - Android 13
 - jtx Board version: 2.01.09-rc03.ose (201090003
 - Downloaded from: Fdeoid

**Comment by b-m-f** [comment]
Could be an issue with a listener that is attached?

**Comment by patrickunterwegs** [comment]
Hey @b-m-f , 
There is basically a logic on the text field, but this logic is only applied e.g. to make a new "-" after a return to start the new line also with a "-". The backspace does not have any logic.

I couldn't reproduce this issue. Is it possible that this is related to your keyboard provider? Which keyboard are you using? Some time ago there was also some weird behaviour for a user who used the Microsoft keyboard. Could you try it with another one and let me know if the problem also occurs there?

**Comment by b-m-f** [comment]
I am using the default AOSP keyboard. 

Here are some videos of the behaviour. It works normally when using the `Nextcloud Deck` app.

# NC Deck working

https://user-images.githubusercontent.com/2843450/212018663-a248411f-57ef-429b-a329-be77e83092d9.mp4

# JTX Board not working 

https://user-images.githubusercontent.com/2843450/212018692-3ff03b8c-049f-49f4-b89e-c1f726b5fc08.mp4


I will try another keyboard and update here

**Comment by b-m-f** [comment]
It does seem to work with a different keyboard. Thanks for the hint!

**Comment by patrickunterwegs** [comment]
Thanks for the update!
I think it is still related to jetpack compose (as it seems to work in Deck). But I don't think that I can do anything here anyway, either jetpack compose needs to update something, but more likely it is the keyboard provider.
Cheers, Patrick

**Comment by mcastillof** [comment]
I was about to report the same bug. 

I can confirm that it happens with ASOP Keyboard. If I disable Android Keyboard  Settings (AOSP) settings -> Text correction -> Show correction suggestions, the problem doesn't happen again, but you loose the suggestions.
