### ISSUE TITLE
[BUG] Sorting of categories descending does not work correctly

### ISSUE THREAD

**Issue by wernharder** [TechbeeAT/jtxBoard#1604]
**Describe the bug**

When grouping entries by category, the sorting does not work correctly. The alphabetical order is not maintained when sorting in ascending order.
When sorting in descending order, the result is correct.

**To Reproduce**

1. Group by "category"
2. Sort by "ascending"
3. See error --> categories not sorted alphabetically
4. Sort by "descending"
5. See result --> categories sorted alphabetically

**Expected behavior**

Categories are sorted alphabetically.

**Screenshots**

![Screenshot_001_jtx Board](https://github.com/user-attachments/assets/3eb3c871-618d-4e25-852b-79942ae02bdd)
![Screenshot_002_jtx Board](https://github.com/user-attachments/assets/c270f9e7-c6de-49a7-ab54-3bd740fa0c9e)

**Device and version**
 - Device: Sonx Xperia XA2
 - Android version: Android 13 (e-os 2.41)
 - jtx Board version: 2.09.01.ose (29010003)
 - Downloaded from: f-Droid

**Comment by patrickunterwegs** [comment]
Hey @wernharder !
Thank you for the issue report! I just reproduced it. 
I had to take a bit of a break from jtx Board due to personal issues and super high workload in my regular job, but I'll pick that up soon. Please be patient.

**Comment by patrickunterwegs** [comment]
I finally found the time to check this out, I'll provide a version with the fix soon =)
