### ISSUE TITLE
[BUG] Sorting of categories - Multiple categories per task sorting is broken

### ISSUE THREAD

**Issue by balporig** [TechbeeAT/jtxBoard#1620]
**Describe the bug**

Related to #1604. If a task has multiple categories, especially when having symbols (`/`,`-`...), categories are sorted only after the task they are defined

**To Reproduce**

Given

```
Task 1 categories: A B unit/a
Task 2 categories: C D unit/b
```

Results in

```
A
B 
unit/a
C
D 
unit/b
```

**Expected behavior**

```
A
B 
C
D 
unit/a
unit/b
```

**Screenshots**

![uYzb1IGBuGigE0QCjVW39Os7r97q8L9S](https://github.com/user-attachments/assets/67a85bd2-900d-4ab2-86cb-83b36edbd999)

**Device and version**
 - Device: N/A
 - Android version: Android 11
 - jtx Board version: 2.09.02.ose (209020004)
 - Downloaded from: github

**Comment by patrickunterwegs** [comment]
Hi @balporig , thanks for the issue report!
I just made the fix, as you download the version from GitHub, it would be great if you could check out the beta that I'm just uploading and give some feedback if the issue is also fixed for you! =)

**Comment by balporig** [comment]
Thanks @patrickunterwegs :) It's fixed

**Comment by patrickunterwegs** [comment]
Great, thank you for checking =) @balporig
