### ISSUE TITLE
[Feature] add an button to create a checkbox

### ISSUE THREAD

**Issue by MaDill** [TechbeeAT/jtxBoard#1637]
As described in issue #1636 I came from OpenTask. There it was very easy to create checkboxes in a task. My family use this frequently to create shopping lists for different stores.

I receive the complaint that the way it was in OpenTask was much easier. There are already buttons for bold, italic, ... maybe a check box button chould fit there also.

For example I create a shopping list.
**Your current device and version**
 - Device: Sony xperia 10, Lenovo Tab 8
 - Android version: Android 13
 - jtx Board version: 2.09.02
 - Downloaded from: Google Play

**Comment by patrickunterwegs** [comment]
See #1636
