### ISSUE TITLE
[Feature] filter by priority

### ISSUE THREAD

**Issue by MaDill** [TechbeeAT/jtxBoard#1642]
**Describe the solution you'd like**
The filter are very powerfull, but I miss to filter by priority. For example "show me all tasks with high priority". Or all task without any priority or ...

Maybe this is already there, but at the moment I can not see this.

**Your current device and version**
 - Device: Sony Xperia 10, Lenovo Tab 8
 - Android version: Android 13
 - jtx Board version: 2.09.03
 - Downloaded from: Google Play

**Comment by patrickunterwegs** [comment]
Hey @MaDill , thanks for the remark, in fact I'm wondering why I haven't done it yet, I'll check.

**Comment by patrickunterwegs** [comment]
@MaDill , I just did the change. =) If you like you can join the beta-program on Google Play and try it out. I'll upload a new version now (just note that it might take a few hours to get approved by Google)! =)
