### ISSUE TITLE
[BUG] preselection of the due date has double "Am darauffolgenden Tag"

### ISSUE THREAD

**Issue by MaDill** [TechbeeAT/jtxBoard#1656]
**Describe the bug**
When I pre select the due date of a task in the settings there is the "Am darauffolgenden Tag" double

**To Reproduce**

1. Go to the settings page
2. Click on the task settings
3. Click on the due date
4. See error as in the screenshot

**Screenshots**

![Screenshot_20241209-212810](https://github.com/user-attachments/assets/8d859d9b-6d54-4bbb-9606-759b2b1ad821)

**Device and version**
 - Device: Lenovo Tab M8
 - Android version: Android 13
 - jtx Board version: 2.09.03.gplay
 - Downloaded from: Google Play

**Comment by patrickunterwegs** [comment]
Thanks @MaDill , will be fixed in the next version.
