### ISSUE TITLE
[BUG] "Sync with DAVx5" screen doesn't scroll

### ISSUE THREAD

**Issue by rfc2822** [TechbeeAT/jtxBoard#225]
**Describe the bug**
When using an older phone (or an emulator with lower resolution), the full text of the "Sync with DAVx5" is not readable.

**To Reproduce**
1. Open jtx Board
2. Click on _Sync with DAVx5_ in the navigation drawer
3. Try to scroll down

**Screenshots**
![Screenshot_1674561653](https://user-images.githubusercontent.com/156167/214286649-a9178400-7d44-42ee-ade0-1f239613c232.png)

**Comment by patrickunterwegs** [comment]
Thanks! 🙂 
That was a bit weird, the scrollable modifier was actually there and I just had to change it to another one (.verticalScroll(...)). 
Anyhow, it's fixed now 🙂
