### ISSUE TITLE
[BUG] Content provider: SQL exception when querying icalobjects of a specific account (but without collection)

### ISSUE THREAD

**Issue by rfc2822** [TechbeeAT/jtxBoard#227]
**Describe the bug**
In the DAVx⁵ debug info, we show a per-account summary of synchronized entries. Currently, jtx Board is always 0 because of a DAVx5 debug info bug (bitfireAT/davx5#194 – basically that jtx Board doesn't support queries without syncAdapter yet).

While fixing this in bitfireAT/davx5#195, I noticed that jtx Board throws an SQL exception when I call
`query()` to get all rows of `JtxContract.JtxICalObject.CONTENT_URI.asSyncAdapter(account)`. The error is:

```
android.database.sqlite.SQLiteException: no such column: account_name (code 1): , while compiling: SELECT * FROM icalobject WHERE _id IN (SELECT icalobject._id FROM icalobject INNER JOIN collection ON icalobject.collectionId = collection._id AND collection.accountname = ? AND collection.accounttype = ? AND icalobject.recur_islinkedinstance = 0)  AND (account_name=? AND account_type=?) │
```

Looks like the query would always expect a collection ID; but in this case we only have the account name/type.

**Expected behavior**
Would be nice if jtx Board could return all entries of this account (regardless of the collection ID) in this case :)

**Comment by patrickunterwegs** [comment]
I think the problem here is the following: 

```
client.query(info.countUri, null, "account_name=? AND account_type=?", arrayOf(account.name, account.type), null)?.use { cursor ->nrEntries = "${cursor.count} ${info.countStr}" }
```
in app/src/main/java/at/bitfire/davdroid/ui/DebugInfoActivity.kt

account_name and account_type are hardcoded here, the actual column names from the contract should be 
JtxCollection.ACCOUNT_NAME  (which is "accountname")
JtxCollection.ACCOUNT_TYPE  (which is "accounttype")

I'd say the query there should either be made generic to work with any contract or I can make a dedicated method in ical4android...

**Comment by rfc2822** [comment]
> I think the problem here is the following:
> 
> ```
> client.query(info.countUri, null, "account_name=? AND account_type=?", arrayOf(account.name, account.type), null)?.use { cursor ->nrEntries = "${cursor.count} ${info.countStr}" }
> ```
> 
> in app/src/main/java/at/bitfire/davdroid/ui/DebugInfoActivity.kt
> 
> account_name and account_type are hardcoded here, the actual column names from the contract should be JtxCollection.ACCOUNT_NAME (which is "accountname") JtxCollection.ACCOUNT_TYPE (which is "accounttype")
> 
> I'd say the query there should either be made generic to work with any contract or I can make a dedicated method in ical4android...

Ah, of course… 🤦🏻 

I guess when adding `.asSyncAdapter(account)` to the content URI always restricts returned results to the given account?

**Comment by rfc2822** [comment]
Seems to work now, thanks, no need for changes on your side :)

**Comment by patrickunterwegs** [comment]
Yes, indeed, the query parameters for account name and type are not necessary, but the "asSyncAdapter" is mandatory, otherwise again jtx Board wouldn't return anything! 😉
