### ISSUE TITLE
Improve usability of Kanban view

### ISSUE THREAD

**Issue by burningT** [TechbeeAT/jtxBoard#236]
Since 2.02.00-rc12.gplay, the Kanban view is extended to 5 columns. The new columns lead to the following issues:
- due to the width of the screen held in portrait, the column width might become too tiny and the tasks become hard to read
- tasks are displayed in multiple columns simultaneously
- moving tasks between columns via drag and drop does not seem to work for all columns

This limits the usability of the Kanban board. As I am not sure about the reason for the added columns, I would propose making the columns configurable or hidable at least.

**Comment by patrickunterwegs** [comment]
Hey @burningT !
Thanks, in fact this was an effect that I forgot when refactoring three status handling in the background. I will correct that in the next version and remove the canceled column again. In the future I'll also make the columns configurable! 😊
