### ISSUE TITLE
[BUG] Attachment names get scrambled

### ISSUE THREAD

**Issue by StefanoWoerner** [TechbeeAT/jtxBoard#249]
**Describe the bug**
When downloading attachments from the server, jtx board scrambles the name. This has two significant drawbacks:
1. The file name may be a useful part of the attachment, which users might not want to lose. (I, for instance, would expect the name to remain the same.)
2. The file extension gets replaced by null, meaning that I can't easily open the attachment with an appropriate app.

I verified that the attachment name is correct on the server, meaning that it must get scrambled by DAVx5 or jtxBoard.

**To Reproduce**
1. Add an attachment to a VJOURNAL from another device, e.g. GNU/Linux desktop using Evolution Mail
2. Sync the other device with server
3. Sync jtxBoard with server
4. The VJOURNAL entry is updated and the attachment is downloaded and even has the correct size, but a scrambled name.

**Expected behavior**
The file name remains the same (at least in the UI). The extension also stays the same so that I can easily choose the appropriate app to open the file with, i.e. the gallery for images or a text editor for .txt and .md files.

**Device and version:**
 - Android version: 13
 - jtx Board version: 2.2.0
 - Downloaded from: f-Droid

**Comment by StefanoWoerner** [comment]
I understand it is probably useful to generate a unique identifier as a file name for saving the file in local storage. Maybe it could be a solution to just prepend the generated unique identifier to the original file name (as present in the VJOURNAL entry) instead of completely replacing it. That would automatically keep the extension intact as well. This is the way Evolution Mail handles attachments, by the way.

The UI should probably just show the original file name for better UX.

**Comment by patrickunterwegs** [comment]
Hey @StefanoWoerner , thanks for the issue report!
Yes, the unique filename is for the internal storage.
I actually thought I had fixed this some months ago, but maybe I have missed something.  I'll check again soon!

**Comment by patrickunterwegs** [comment]
Hey @StefanoWoerner , 
I have analysed the problem and also #293 brought me on the right track. I have written an explanation about the problem there if you are interested!
I am closing this issue here as it will be solved in the next DAVx5 version 4.3.1!
