### ISSUE TITLE
[Feature] Allow entering textual coordinates / catch intents with geo data 

### ISSUE THREAD

**Issue by HendriXML** [TechbeeAT/jtxBoard#261]
**Is your feature request related to a problem? Please describe.**
Notes/journals are very usefull in sharing information between devices. Exchanging POI information should be one of them. Using the map to enter location data is when precise coordinates are already known is a bit cumbersome. 

**Describe the solution you'd like**
Alternative ways (other than using the map) to enter location coordinates with the same functionality,  like open with location apps (send to/share with). 

**Describe alternatives you've considered**
- Textual cordinates
- Handeling "send to" or url events from other apps

**Comment by patrickunterwegs** [comment]
Hey @HendriXML , thanks, sounds reasonable and easily feasible. I'll check that soon!

**Comment by HendriXML** [comment]
Hey @patrickunterwegs,

Would be great! Nice to see the progress that's being made!

Wouldn't mind if "attachments notes" or even general urls could be implemented in a similar way. The nice thing about notes/journals is that there's always a local copy after syncing. So for small files very usefull to quickly add to global storage, without the need of processing it on another device at that moment. There're other ways of sharing data, but your app can include a lot of context.

**Comment by patrickunterwegs** [comment]
Hey, yeah, well, for attachments and links this is already implemented! 😉 You can share any link from a browser or any file with joy Board and it will be processed as an attachment or url!

**Comment by HendriXML** [comment]
Url's I hadn't tried and they indeed works nicely! Files seem to depend on the file type. Images I can share. But when sharing gpx or kml files jtxboard isn't listed. I tried sharing out of the standard filemanager and Locus Map Classic.

When clicking on an url the default handler is executed. It might be even more usefull to list more at a long press like the Chrome browser. That way the handling can be "transfered" to another device. For example a website gives a map url with location info.
I can open it in Locus Map classic and navigate offline. If I have such url on my tablet I would like to transfer it using a note to my phone. Currently it only opens on an online map app.

**Comment by patrickunterwegs** [comment]
Alright, thanks, I'll try it with different filetypes what's going wrong there. 

Regarding the URL field: Basically if the topic is not related to the original topic of the issue, please open another one to keep a clean overview. I'll have a look how this can be improved.

**Comment by patrickunterwegs** [comment]
Hey @HendriXML , 
this is done now and will be part of v2.3.1 (sorry that it will take a while, but 2.3.0 has a dependency on DAVx5 and needs to be aligned and tested thouroughly, as some sync-stuff was changed there and I don't want to mix that with further functional changes). 
The coordinates can then be entered manually or set through a button (to the current coordinates). 
If a link or text is shared with jtx Board, the text is parsed and checked for coordinates. If coordinates can be found, they will be added in the lat/long fields and the map and link will appear. :-)
One thing that does not work is when you take a Google Maps link that has only an ID and no coordinates readable in the link. But I'll leave it now as it is, if this is also a valid usecase for you in the future, let me know and I'll check it in an upcoming version 😉
