### ISSUE TITLE
[Feature] Time format according to System

### ISSUE THREAD

**Issue by unalignedcoder** [TechbeeAT/jtxBoard#264]
Currently the date next to items (for example in Journal entries) is indicates in m/d/y

It would be good if this information instead reflected whatever is the time format set on the phone, or even a custom format indicated by the user (with, for example, long or short format, day of the week, commas, etc).

**Comment by patrickunterwegs** [comment]
Hello @unalignedcoder , could you please add a screenshot of the place where the date format could be improved? All dates except the date in the journals last should be localized!

**Comment by unalignedcoder** [comment]
![photo_2023-02-05_23-28-55](https://user-images.githubusercontent.com/16850566/216835360-fca06261-1b09-45d4-9b05-ffce6f485ea6.jpg)

This is from the journal compact list. I must admit that this might be a problem on my end. I just noticed that the Nextcloud app shows the dates the same way. 

The date-time settings are set to use the local defaults, which would require the dd/mm/yy format. So I just assumed that's how dates are displayed on this phone. Hours, for example, are in the 24h format.

The first language however is English (US). Do date formats on Android follow the language rather than the local custom? I guess that's possible. 

If the problem turns out to be on my end, I apologize for a useless thread!

**Comment by patrickunterwegs** [comment]
Yes, indeed the format comes from the first locale set in the Android system preferences automatically. If you would like to keep your system in English but use another country (with other date or time formats), you can find a lot of countries with the english language, even though english might not be an official language in that country in the Android system settings 😉 
So I'll close this ticket here. 👍
