### ISSUE TITLE
[Feature] Multiple url handlers on a long press

### ISSUE THREAD

**Issue by HendriXML** [TechbeeAT/jtxBoard#266]
**Is your feature request related to a problem? Please describe.**
Pressing the url link opens the default handler of that url. In some cases an alternative handler is more usefull.

**Describe the solution you'd like**
The implementation of a long press, which let's the user choose out of all registered url handlers, like when using the Chrome browser (In which jtxBoard nicely can be choosen).

**Describe alternatives you've considered**
Currently map-links, open in maps which is not my preferred map application most of the time.

**Comment by patrickunterwegs** [comment]
Hey @HendriXML , when you're talking about map links, do you mean a link e.g. to Google Maps or a geo:// link?

I will review the code at that place, but I'd say basically this might also be a problem of the receiving app. Also Android is not making it clear for developers with a couple of options to forward the user with data to another app...

**Comment by HendriXML** [comment]
They come in all shapes and sizes, but this form (and others)  I can open in Locus Map Classic.
 https://maps.apple.com/?daddr=51.53941363621893,3.866636929370127
Google maps has some format too.
For those links Locus Map isn't the default handler, but a generic url one. (Just like your app is)
But still it can process the url in a meaningfull way. That's why choosing a handler (if needed) is very handy.
By long pressing a button on a website I can save the location of a Goose in Locus Pro instead of opening Google maps.
But for me this POI is then on the wrong device :)
The preferred workflow would be:
Make url-note in jtx-Board. Can already be done, quick and easy.
This then get synced to my phone.
In the field I could then open this link with Locus Map and have it as an actual POI.

**Comment by HendriXML** [comment]
If jtx-Board where to decode those location urls and place it in the location field as well that would be very nice to. Between geo oriented apps those url formats are a quite common way of sharing coordinates.

**Comment by HendriXML** [comment]
About the geo:// link, that might indeed be the way "navigation apps" get activated and receive their data. For me the mechanics are hidden. Would be nice to see jtx Board in that list as well.

**Comment by patrickunterwegs** [comment]
Alright, so I will do the following:
When sharing a link with jtx Board I will try to parse the geo data out of it and put it in the coordinates (the link itself will stay in the URL field). 
When you open the coordinates from the app, it uses the geo intent that should let you choose from your preferred maps provider. 

I wouldn't do the long click handling now. Also because for now it is consistent that a long click opens the edit view of an element!

**Comment by HendriXML** [comment]
Looking forward for that solution!
As a side note, I already like the possibility of different widgets, displaying different content. 

Your app could for example also be helpfull for people with early dementia. Where a caretaker/family member could remotely keep an eye on tasks that need to be done. Medicine intake, feeding the dog, etc.

Automatically checking tasks using a rfid tag scan may be handy then. This tag scanning is sometimes also used on security patrols, to make sure locations are actually checked (closing doors/windows). Just a thought...

**Comment by patrickunterwegs** [comment]
Thank you also for the feedback :-) 
I guess something with rfid goes a bit too far for now, but it's an interesting thought for the future!

I would close this ticket now as changes are done for 2.3.1 as described above. I'm not sure if it will cover all your mentioned cases, but I believe it's some steps in the right direction. So once 2.3.1 is available, I'd appreciate your feedback and if your needs are not fulfilled, feel free to open another ticket to discuss it further!
