### ISSUE TITLE
[Feature] Just like setting a default time, setting a default location might be usefull

### ISSUE THREAD

**Issue by HendriXML** [TechbeeAT/jtxBoard#267]
**Is your feature request related to a problem? Please describe.**
When taking notes or journal items in the field, for instance when birding. It would be nice if the location was taken from the current location automatically.

**Describe the solution you'd like**
A setting which allows for the location to be automatically be filled in.

**Describe alternatives you've considered**
Choosing the current location by hand. But that might be easy to forget.

**Comment by patrickunterwegs** [comment]
Sounds like a beautiful use case, I'll check that soon 🙂

**Comment by patrickunterwegs** [comment]
Done for v2.3.1
Added options for journals, notes and tasks so the user can choose independently for which type of entries the automatic location should be set.
