### ISSUE TITLE
[Feature]  import notes from other files

### ISSUE THREAD

**Issue by lgwapnitsky** [TechbeeAT/jtxBoard#269]
It would be great if there were a way to import the notes from Joplin (or similar) to JTX

**Comment by patrickunterwegs** [comment]
Hey @lgwapnitsky , 
Thanks for your request! 😊
I've also been discussing this a bit at FOSDEM and I'll check it soon (there are currently also a bunch of other things with higher priority). 

Just let me say about Joplin: it's a great tool for markdown note taking with many formatting options. With jtx Board I wouldn't go the full way to compete with such apps as I believe they are great for their specific use case. jtx Board works in the context of the iCalendar and I don't want to make Markdown a big focus. So I'm just saying that importing markdown formatted text is okay, but there shouldn't be the expectation that all markdown tags will be fully supported 😉

**Comment by patrickunterwegs** [comment]
Hey @lgwapnitsky !
I've been putting more thoughts into this now. I have checked Joplin and its export functionality. I would like to keep it as generalized as possible, so I don't want to process their own format that they created.
So my approach would be similar to the functionality where you import an ics file to a collection (in the collections overview), that you can select multiple .md or .txt files. The app would ask you if you'd like to import them as journal, note or task and then import them to the selected collection.

What do you think about this approach?

**Comment by lgwapnitsky** [comment]
This sounds great
