### ISSUE TITLE
[Feature] Widget: More customization options (color)

### ISSUE THREAD

**Issue by patrickunterwegs** [TechbeeAT/jtxBoard#286]
See #285

**Comment by nilskamm** [comment]
I've read through the linked discussion and have a question. 
After the first post there is no more about the "corner radius".
What does it mean.?

I wanted to suggest the widget becoming bigger. 
On my android 10 i have 5 tiles(?) width to spend for such a widget. 
Don't know if "corner radius" means the same. 
That would make it usable to me.

**Comment by patrickunterwegs** [comment]
Hello @nilskamm , this is actually a different topic. But why can't you just make the widget bigger? I just tried to resize it over the full screen with 5x6 tiles and it works without problems. Do you have an issue with that?

**Comment by nilskamm** [comment]
I didn´t know, that i can resize widgets on my phone. I thought that there are just as big as the size says while putting the widget in place. That blew my mind and i changed a lot of widgets after your message. So yes. It works. No issue. Just missing knowledge. ^^
