### ISSUE TITLE
Limited compatibility due to negative INTERVAL value 

### ISSUE THREAD

**Issue by burningT** [TechbeeAT/jtxBoard#301]
**Describe the bug**
VTODO entries might contain negative INTERVAL values for RRULE. This is unexpected as SHIFT6mq requires "The INTERVAL rule part contains a positive integer...". It leads to an error with other tools as CalDavSynchronizer 4.3.0.0, stating "<Error>System.ArgumentException: INTERVAL value -1 is out of range. Valid values are between 0 and 2147483647"

**To Reproduce**
Create a task with the following entries:

BEGIN:VCALENDAR
VERSION:2.0
PRODID:DAVx5/4.2.6-gplay ical4j/3.2.5
BEGIN:VTODO
DTSTAMP:20230131T054022Z
UID:ed7b4368-023a-4f6c-a5f7-15fc56038d25
SEQUENCE:33
CREATED:20221115T063050Z
LAST-MODIFIED:20230130T170642Z
SUMMARY:Test task
CLASS:PUBLIC
STATUS:NEEDS-ACTION
CATEGORIES:TestCategory
DTSTART:20221118T000000
RRULE:FREQ=WEEKLY;COUNT=25;INTERVAL=-1;BYDAY=FR
EXDATE:20221118T000000,20221125T000000,20221202T000000,20221209T000000,2022
1216T000000,20221223T000000,20221230T000000,20230106T000000,20230113T00000
0,20230120T000000,20230127T000000,20230203T000000
PRIORITY:5
DUE:20221120T100059
END:VTODO
END:VCALENDAR

**Expected behavior**
Positive integer values for INTERVAL to improve conformity with RFC2445.

**Device and version:**
 - Device: SHIFT6mq
 - Android version  Android 10
 - jtx Board version: 2.02.02-rc5.gplay (202020005)
 - Downloaded from: Google Play

**Comment by patrickunterwegs** [comment]
Hey @burningT ! 
Thanks, indeed that shouldn't happen. So you created this every in jtx Board and after some edits it ended up with a negative interval? Or did you deactivate the recurring rule at over point?

**Comment by burningT** [comment]
Hi Patrick,

The issue persists for quite a while now and it took some time to figure out where it comes from. Hence I cannot give you a precise use case that leads to it. However, the task was created as reoccurring with limited amount of occurrences right away. The issue possibly exists from day one of that task.



Am 20. Februar 2023 18:46:19 MEZ schrieb Patrick Lang ***@***.***>:

**Comment by patrickunterwegs** [comment]
Hey @burningT , 
Hm, I see, the entry was created in Nov. 2022. The recurrence handling was refactored and also the UI changed in the meantime. If this is the only entry (which appears to be a test entry anway - or did you change it for the post?) and it is not reproducible, I would rather say that this issue was already fixed. 
Theoretically I could add some check in the sync algorithm, but anyway the UI should not allow to create such an entry. 
Would you agree to just delete/recreate this entry and close this ticket as it is not reproducible?

**Comment by burningT** [comment]
Hi Patrick,

I tried to recreat the issue based on the peaces I recall. I could not reproduce the behaviour as well. 

Initially I expected the INTERVAL value to be set intentionally to a negative value. However, that's not the case and either it is fixed or I don't remember enough to reproduce the issue. 

I suggest considering this fixed already and I will come back at you if I recognise something else.

Am 21. Februar 2023 16:12:06 MEZ schrieb Patrick Lang ***@***.***>:

**Comment by patrickunterwegs** [comment]
Hey @burningT !
Alright, thanks! 🙂 
I believe there was a bug that could have caused this issue that I fixed many months ago. In any case the UI should not allow such a value and as it's not reproducible, let's close it for now! 🙂 
Thanks, Patrick
