### ISSUE TITLE
[BUG] Review performance with 200+ entries

### ISSUE THREAD

**Issue by patrickunterwegs** [TechbeeAT/jtxBoard#308]

**Comment by patrickunterwegs** [comment]
Reviewed with ~ 250 entries (especially recurring), no performance issues during scrolling detected

**Comment by rogercreagh** [comment]
Thanks.

**Comment by patrickunterwegs** [comment]
Hello @rogercreagh , I want sure anymore where this issue originated. Was it a remark from you?
How is the current performance for you?
