### ISSUE TITLE
[BUG] RC version requires future DAVx5 version

### ISSUE THREAD

**Issue by Tirpitz93** [TechbeeAT/jtxBoard#312]
**Describe the bug**
When installing the RC from github sync no longer works as it requires a newer version than I have been able to source.
**To Reproduce**
1. Install RC version from github (VIA Obtainium)
2. Open App
3. See red sync disabled icon

**Expected behavior**
I would like to know if this is expected/intetional and where to get the newer version of DAVx5

**Screenshots**

**Device and version:**
 - Device: Oneplus 7 Pro
 - Android version [e.g. Android 11]
 - jtx Board version: [v2.3.0-rc10](https://github.com/TechbeeAT/jtxBoard/releases/tag/v2.3.0-rc10)
 - Downloaded from: Github

**Comment by Tirpitz93** [comment]
Nevermind I have only just found the github repo for DAVx5.

**Comment by patrickunterwegs** [comment]
Hey @Tirpitz93 , 
yes, regrettably there is this hard dependency between jtx Board 2.3.0 and DAVx5 4.3.1, that couldn't be avoided. I expect that they will provide their version soon so I can finally get this release done. I expect it within the next days at least. Sorry for the inconvenience. If you consider downgrading please note that this would not be possible without destroying the database in the background. So it would be better to delete and re-install the previous version, just make sure to have a backup!

**Comment by Tirpitz93** [comment]
Okidoki, I'll wait till davx5 comes out with a new version. I dont want to build myself.

**Comment by patrickunterwegs** [comment]
Hey @Tirpitz93 , the first beta of DAVx5 4.3.1 is now available :-)
https://github.com/bitfireAT/davx5/releases

Please note that those are still beta-versions and I recommend a backup before upgrading!
