### ISSUE TITLE
[BUG] can't open app after update to v2.3.0-rc10

### ISSUE THREAD

**Issue by mojienjoyment** [TechbeeAT/jtxBoard#318]
can't open app after update to v2.3.0-rc10
Miui13 android 12 px3pro

**Comment by patrickunterwegs** [comment]
Hello @mojienjoyment , can you tell from which version you updated to 2.3.0-rc10?  
There was a change from one 2.3.0 pre-release to the next that in the worst case could cause a DB problem which might cause this crash on so start. If you updated the pre-release regularly, I'm afraid the only solution now is too re-install the app

**Comment by mojienjoyment** [comment]
I updated from 2.3.0-RC07 to Rc10.

**Comment by patrickunterwegs** [comment]
Yes, in fact the breaking change was from rc07 to rc08. 
Do you have any important data not synchronised that you might have lost? I could maybe provide an apk with a version that could make the data accessible again.

**Comment by mojienjoyment** [comment]
I have some data that not synced but I can write it again. I try to backup data via adb backup but it's result is 1kb file. "allowbackup" tag is true in manifest.Xml but I think it's because of "fullbackuponly" tag that I can't use adb backup!

**Comment by patrickunterwegs** [comment]
Hey @mojienjoyment , sorry once again for this issue, I'll take more care next time.
But also it's the pre-release channel where major problems cannot be fully excluded.
If you have any further issues that need to be solved after this, please let me know!
