### ISSUE TITLE
[Feature] Adding actual time by default when creating new log entry

### ISSUE THREAD

**Issue by ronane** [TechbeeAT/jtxBoard#32]
**Is your feature request related to a problem? Please describe.**
When I add an entry, it's already set to today's date which is nice for my use case, but I always need to set the time manually.
I usually log between 10 times and 15 times a day.

**Describe the solution you'd like**
I would need entries creation with actual time set by default, but I think it would be better if this is optional.

I imagine two solutions to enable this behavior :
- a parameter
- a specific button to create an entry with date and time

or something mixed, like a parameter which display a specific button

**Describe alternatives you've considered**
The alternative is actually setting the time manually each time I make a log entry, which is annoying

**Additional context**

**Comment by patrickunterwegs** [comment]
Hey @ronane , thanks for your request!
I would consider a new setting in the settings menu, there are already a couple of options for tasks with similar possibilities. 

So I would consider: 
- Set date automatically to today without time
- Set date and time automatically

But what do you think about other options? Like 
- Set the date and time automatically, but only the hour and set minutes always to 0
- Any other options?

**Comment by ronane** [comment]
Actually, your other proposition is very good, I thought of it myself but I wouldn't seem to be too demanding ^^

The only other option I thought was "round hours and minutes to closest quarter" like 
10h54 -> 11h00
11h10 -> 11h15

**Comment by patrickunterwegs** [comment]
Alright, thanks 😉 
I have added a few options now, as I was already on it, it was not a lot of additional effort: 
![Screenshot_20221211_194657](https://user-images.githubusercontent.com/72232737/206922699-e65f7b57-393e-4958-955d-32475d42a710.png)

If you'd like to check it out, you can either download the apk from GitHub or join the Google Play Beta channel (it should be there by tomorrow), otherwise you'll have to wait for the release 😉

**Comment by ronane** [comment]
Thank you, as I'm using f-droid and have not Google play on my phone, I'll wait for the release, if it comes in the next few weeks.
I'm not that on much in a hurry.
