### ISSUE TITLE
Indended lines not shown

### ISSUE THREAD

**Issue by dilyanpalauzov** [TechbeeAT/jtxBoard#320]
With jtxboard 2.02.02-rc5.ose (202020005) I open this file.

[test.ics.txt](https://github.com/TechbeeAT/jtxBoard/files/10865059/test.ics.txt)

In the View mode (not Edit) the texts:

>    EAP Methode : PEAP wählen (default)
>    Phase 2-Authenifizierung: MSCHAPV2

is not displayed, instead empty lines are shown.  I use dark mode.

The last section of indented lines is also not displayed, instead a lot of empty lines are shown.

**Comment by patrickunterwegs** [comment]
Indeed that's a bit weird. 
As a temporary workaround you could deactivate markdown, then you would see the missing text.

@ArnyminerZ do you have any idea why this could happen?

I will try to upload screenshots again, currently this has some issues.

**Comment by patrickunterwegs** [comment]
Without markdown:

![Screenshot_20230301_221436_jtx Board](https://user-images.githubusercontent.com/72232737/222267269-b0b29b81-b50c-40f5-b5d6-bf8543aded0f.jpg)

With markdown:

![Screenshot_20230301_221657_jtx Board](https://user-images.githubusercontent.com/72232737/222267371-ccf7524f-dda9-425e-8c0b-9a9de2d0a729.jpg)

**Comment by ArnyminerZ** [comment]
Mmmh... I'll investigate and keep you updated

**Comment by ArnyminerZ** [comment]
Looks like it's being detected as a code block, which is actually defined in [GitHub Flavored Markdown Spec](https://github.github.com/gfm/#indented-code-blocks). Code blocks are not supported right now, that's why it's not displaying anything. I'll try to find an implementation of code blocks, or rendering indented code otherwise.

**Comment by ArnyminerZ** [comment]
A quickfix has been released in MarkdownText 1.3.2. Since technically indenting content means creating a code block, it's being rendered as so. The current design is quite "ugly", but there's no way of improving it with the current approach of rendering stuff we have.

**Comment by patrickunterwegs** [comment]
Thank you for the quick fix 🙂

Yes, it doesn't look so great, but better than having the text disappear 😉 as a quick fix it's good. I'll update the version and close this ticket with it.
