### ISSUE TITLE
[Feature] Filter logs by precise date

### ISSUE THREAD

**Issue by ronane** [TechbeeAT/jtxBoard#33]
**Is your feature request related to a problem? Please describe.**
I write a lot of logs, between 10 and 15 a day. 
Filtering allow having only logs with date in past, today, tomorrow or future.

**Describe the solution you'd like**
I would like having the possibility to display only logs with a specific date.

For example, we are on 20221205, if we have these logs (with date YYYYMMDD): 

 - Log 1 | 20221201
 - Log 2 | 20221202
 - Log 3 | 20221202
 - Log 4 | 20221202
 - Log 5 | 20221203
 - Log 6 | 20221203
 - Log 7 | 20221205
 
 We set a filter to 20221202 so the list display :

 - Log 2 | 20221202
 - Log 3 | 20221202
 - Log 4 | 20221202
 
 
 Edit : 
 I have usually logged entries with date and time, so it would need to ignore time.

**Comment by patrickunterwegs** [comment]
Hey @ronane ! 
I'm not sure about this request. 
Basically you already have two alternatives: 
- in the journals list you have a option to open a calendar from the bottom menu which will allow you to scroll to a specific date (or the entry with the closest date). Just make sure you also order by date.
- in the filter bottom sheet you can activate the option to group by date - which already ignores the time.

I think adding such a filter would be a bit cumbersome in usage. You set the filter once, but you would usually not leave it and you need to update it all the time causing a lot of clicks. 
Don't you think the grouping already fits very well to your needs?

I also just checked it and it seems there is a bug in the list view for journals, the group by is actually not applied, I will take care of this now! (but you can still check the basic functionality in the tasks view)

**Comment by patrickunterwegs** [comment]
Ok, there's actually no bug, the group by date has 4 groups, "date in past", "today", "tomorrow", "date in future". But maybe anyway it makes more sense for journals to group by the actual date (and not to limit it to those 4)?

**Comment by ronane** [comment]
I agree with that, it could effectively be a bit too much and grouping would do it well enough but it would be better in my opinion with actual dates.

The automatic scroll to date is ok, only that if you set the sort on descending it doesn't go to the expected entry I think.
