### ISSUE TITLE
[Feature] Restrict visibility of edit elements to minimum

### ISSUE THREAD

**Issue by patrickunterwegs** [TechbeeAT/jtxBoard#335]
Especially for notes in order to not overwhelm the users

**Comment by rogercreagh** [comment]
What edit elements are you referring to here? Is there a prior discussion I've missed? Most of the fields are optional anyway and can be hidden if unwanted, is there something else?

**Comment by patrickunterwegs** [comment]
This came out of a discussion at FOSDEM. The point was especially when entering notes you might only want to see a minimum set of options in order not to overwhelm the user.
So here I'm thinking about making different presets for each module (journals, notes, tasks) where the notes should maybe only have a description field.
