### ISSUE TITLE
[BUG] can't sync because of davx5 version

### ISSUE THREAD

**Issue by mojienjoyment** [TechbeeAT/jtxBoard#338]
When I setup Davx5 and try to davx5 collection, a message show this message like this,
" cant sync because of your davx5 version, please use version 4.3.1 or later."
But latest version of davx5 on Google lay or github version is 4.3.0! 
Why this happend?

**Comment by patrickunterwegs** [comment]
Hello @mojienjoyment , 
as you have jtx Board 2.3.0 I assume that you have joined the beta-program on Google Play. You can get DAVx5 if you also join the beta program of the app there on Google Play!
