### ISSUE TITLE
[BUG] Deleting start date when an alarm at start date is set crashes the app

### ISSUE THREAD

**Issue by graue70** [TechbeeAT/jtxBoard#34]
**Describe the bug**
If an alarm is set at the start date and I remove the start date, the app crashes.

**To Reproduce**
1. Create or edit a task.
2. Set a start date.
3. Set an alarm at the start date.
4. Remove the Start date.
5. App crashes

**Expected behavior**
Alarm is automatically removed or something like that.

**Device and version:**
 - jtx Board version: 2.01.01-rc12.ose
 - Downloaded from: f-Droid

**Comment by patrickunterwegs** [comment]
Hey @graue70 , 
Thanks for your issue report!
The problem was already addressed in #15 and solved in 2.1.2. The update was already released and f-Droid should pick it up soon!
