### ISSUE TITLE
[Feature] Option to pass service token headers for Cloudflare Zero Trust Access

### ISSUE THREAD

**Issue by ratty222** [TechbeeAT/jtxBoard#361]
**Is your feature request related to a problem? Please describe.**
Cloudflare tunnels protected by zero trust access have made it simple for home hobbyists like me to set up pseudo reverse proxies with an extra layer of protection. I'm a hardware guy at heart who has been frustrated with nginx for years. And zero trust with tunnels works great for self-hosted web applications.

**Describe the solution you'd like**
Unless I am reading things wrong, android apps can have the same protection by passing headers for each request through cloudflare's zero trust service tokens. Not a dev, so I have no idea how easy, or even if, this is possible to implement.

**Describe alternatives you've considered**
I just connect to my caldav server like the old days with traditional auth. It works. But Cloudflare tunnels and their Zero Trust access settings are becoming an increasingly popular alternative to a traditional reverse proxy.

**Comment by patrickunterwegs** [comment]
Hey @ratty222 !
This is more a topic for DAVx5 as the communication with the CalDAV-Server is happening there.

@devvv4ever , @rfc2822 , have you maybe had this topic before? Can we move this issue to DAVx5?

**Comment by rfc2822** [comment]
I have never heard of Cloudflare Zero Trust. Is there some documentation? Are you sure that the problem it solves should be solved in application level and not on network level (like a VPN)?

We can move the discussion to DAVx5, it would probably better fit there.

**Comment by ratty222** [comment]
Right, right, right. I forgot that jtx doesn't handle the actual communication. Links to some documentation below, and if it sparks any interest, I am sure you can find other relevant info.

My use case for non-VPN is that I have a few lists that are shared and setting everyone up for VPN connection would confuse and complicate things for some of the group members.

I will go ahead and close this here and open an issue over at davx5 if you guys think there might be interest for others. Thanks to everyone involved in these projects.

https://developers.cloudflare.com/cloudflare-one/identity/authorization-cookie/application-token/

https://developers.cloudflare.com/cloudflare-one/examples/service-token/
