### ISSUE TITLE
[Feature] New "Yesterday" option for default date for new journal items

### ISSUE THREAD

**Issue by rogercreagh** [TechbeeAT/jtxBoard#364]
Usually I write yesterday's journal with a cup of tea in bed before getting up in the morning. So almost always I have to remember to quickly change the date from the default. I don't really care about the time, it is just the day I set. Very rarely I write an entry for today's date, sometimes I get a day or two behind

**Describe the solution you'd like**
An additional option for "Yesterday" in the list in settings (currently it has current minute, 5mns, 15mins, hour and day).

**Describe alternatives you've considered**
Continuing to be minorly irritated every time I make a new entry.

**Additional context**
I don't understand what differs between current hour, 15mins, 5mins or minute. Surely either you include a time or not. I guess current hour sets the minutes and seconds to zero, and current minute sets the seconds to zero which I suppose might make filtering easier or something? Wouldn't it make more sense to always set the full time if it is required and zero out the seconds and minutes on display if they are not needed. 
Anyway no need to change the current settings if they are of use to someone and not redundant. Just add Yesterday to the options.

**Comment by patrickunterwegs** [comment]
Hey @rogercreagh , adding 'yesterday' as an option shouldn't be a problem.

> Wouldn't it make more sense to always set the full time if it is required and zero out the seconds and minutes on display if they are not needed.

Yes and no. Why should anyone want an inconsistency between the data shown and the data stored in the database? 
But there's an additional thing: while the apps stores the date/time as a timestamp in milliseconds, the iCalendar-format uses a dedicated DATE or DATE-TIME format. So if you're synchronising your entries through DAVx5 and you use all-day entries, the time would get lost.
If you'd keep the time data on the one device (and just remove the time in the display) and then synchronise with another device, the other device wouldn't receive the time information (as it would get only the DATE format). Now you would have two inconsistent entries, one with the (invisible) time and one with no time at all. So it's better to keep things consistent and remove the time from the beginning!

**Comment by rogercreagh** [comment]
Of course, I see - DATE and DATE_TIME. That explains the reason for having the settings. Presumably the 15 and 5 minute options effectively just round the time to the previous quarter or twelfth of an hour.

Yesterday would be really useful as an option (for me at least!). 

Thanks again
