### ISSUE TITLE
[Feature] Group by category (and resource)

### ISSUE THREAD

**Issue by patrickunterwegs** [TechbeeAT/jtxBoard#389]
### Discussed in https://github.com/TechbeeAT/jtxBoard/discussions/387

<div type='discussions-op-text'>

<sup>Originally posted by **DickinsonSa** March 20, 2023</sup>
Notes seem to have little way to group when viewing other than status and classification (both marginally useful).

I have dozens of notes with various tags /categories - all of which appear in list view, and the only way to group at the moment is by filtering them individually (time consuming). 

Categories (tags) seem to be a more universally recognised way of grouping (other than notebooks) and yet both these methods are under-utilised for grouping.

Can I put forward for discussion/enhancement please the inclusion of  category in the grouping option for notes?

This would include a 'no category assigned' group also. 

</div>

**Comment by rogercreagh** [comment]
As I said in #387 I would rather see an enhancement to the category-tag filtering to allow options Any | All | None for filtering by multiple tags.
So you could select the tags Red and Apple and get only the red apples (ALL selected tags) where currently you get all red items (including things also tagged as Pears and Cars) and all Apples including the blue and yellow ones. (ANY of the selected tags - which is sometimes useful)

Would this go some way towards meeting your requirement @DickinsonSa? 

I think trying to group by tags when items can have multiple combinations of tags is confusing. Grouping only really works if items can belong to only one group, which is not the case here.

**Comment by DickinsonSa** [comment]
Patrick, it's a different enhancement not connected to what I was thinking of.

But, in light of the confusion that could be caused by grouping multiple tags, I'd just drop my enhancement to suit purity of sticking to the standards.

Forget what I was thinking - which was more akin to notebooks - some better way of displaying hundreds of notes without having to filter.

Enjoy your break.

**Comment by patrickunterwegs** [comment]
Thank you for the discussion, I will not work on that, I'll move the topic to discussion though.
