### ISSUE TITLE
[BUG] Can't add DAVx5 (NextCloud) collection - no account visible on jtx Board side

### ISSUE THREAD

**Issue by bugsyb** [TechbeeAT/jtxBoard#393]
Can't get DAVx5 account visible within jtx Board.
Account is already created on DAVx5 side. "Sync with DAVx5" doesn't show existing account, only option to add new.
To try to fix issue, I've even went ahead and added new account directly after hitting "Add account in DAVx5", removed the old one and still no juice.

It is all done on new phone, and previously yesterday with same software version, initially faced same problem though after going couple of times into DAVx5 and back to jtx Board, the existing account popped up on the list of DAVx5 accounts within jtx Board (not sure what did I do that it worked previously).

Collections wise, from DAVx5 calendars are visible, I could create new calendar with all NextCloud supported functionality - it worked. Also adding entries earlier worked as collection was visible.

I've also tried to "Add collection" and it takes me to list of accounts in DAVx5, after selecting account (single one exists, added after selecting add account within jtx Board), it goes into details of the account, with no place to select "Use this account" or something - this is probably where I'm failing - could be a noob element.

If this is not a software bug, please kindly advise how the account can be added to jtx Board, where DAVx5 account exist and after clicking add collection, it opens DAVx5 with list of accounts (single) - what next needs to be done?

Permission wise, all is set/enabled.

It's all on CalyxOS 4.7.4 (Android 13)
jtx Board: 2.0.3.00-rc22.gplay
DAVx5: 4.3-ose

**Comment by bugsyb** [comment]
Partially solved - upgrade required.

The ask to DAVx5 team (https://github.com/bitfireAT/davx5-ose/discussions/295) will be to update F-Droid repositories, as it shows older version 4.3-ose whilst Play Store shows 4.3.1 (with latest problem is fixed).

Error produced (logcat)
```
03-22 13:53:45.743  6994  9460 E DatabaseUtils: Writing exception to parcel
03-22 13:53:45.743  6994  9460 E DatabaseUtils: java.lang.IllegalArgumentException: Your current version of DAVx⁵ is not compatible with this version of jtx Board. Please update DAVx⁵ to 4.3.1 (403010000+) or later! The synchronization is currently suspended.
03-22 13:53:45.743  6994  9460 E DatabaseUtils: 	at at.techbee.jtx.SyncContentProvider.isSyncAdapter(SyncContentProvider.kt:609)
03-22 13:53:45.743  6994  9460 E DatabaseUtils: 	at at.techbee.jtx.SyncContentProvider.query(SyncContentProvider.kt:304)
03-22 13:53:45.743  6994  9460 E DatabaseUtils: 	at android.content.ContentProvider.query(ContentProvider.java:1455)
03-22 13:53:45.743  6994  9460 E DatabaseUtils: 	at android.content.ContentProvider.query(ContentProvider.java:1551)
03-22 13:53:45.743  6994  9460 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:285)
03-22 13:53:45.743  6994  9460 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:107)
03-22 13:53:45.743  6994  9460 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1280)
03-22 13:53:45.743  6994  9460 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1244)
03-22 13:53:45.744  8632  9661 E davx5   : [syncadapter.JtxSyncAdapterService] Couldn't sync jtx collections
03-22 13:53:45.744  8632  9661 E davx5   : EXCEPTION java.lang.IllegalArgumentException: Your current version of DAVx⁵ is not compatible with this version of jtx Board. Please update DAVx⁵ to 4.3.1 (403010000+) or later! The synchronization is currently suspended.
03-22 13:53:45.744  8632  9661 E davx5   : 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
03-22 13:53:45.744  8632  9661 E davx5   : 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
03-22 13:53:45.744  8632  9661 E davx5   : 	at android.content.ContentProviderProxy.query(ContentProviderNative.java:481)
03-22 13:53:45.744  8632  9661 E davx5   : 	at android.content.ContentProviderClient.query(ContentProviderClient.java:196)
03-22 13:53:45.744  8632  9661 E davx5   : 	at android.content.ContentProviderClient.query(ContentProviderClient.java:178)
03-22 13:53:45.744  8632  9661 E davx5   : 	at android.content.ContentProviderClient.query(ContentProviderClient.java:168)
03-22 13:53:45.744  8632  9661 E davx5   : 	at at.bitfire.ical4android.JtxCollection$Companion.find(JtxCollection.kt:71)
03-22 13:53:45.744  8632  9661 E davx5   : 	at at.bitfire.davdroid.syncadapter.JtxSyncAdapterService$JtxSyncAdapter.updateLocalCollections(JtxSyncAdapterService.kt:86)
03-22 13:53:45.744  8632  9661 E davx5   : 	at at.bitfire.davdroid.syncadapter.JtxSyncAdapterService$JtxSyncAdapter.sync(JtxSyncAdapterService.kt:120)
03-22 13:53:45.744  8632  9661 E davx5   : 	at at.bitfire.davdroid.syncadapter.SyncAdapterService$SyncAdapter$onPerformSync$1.invoke(SyncAdapterService.kt:5)
03-22 13:53:45.744  8632  9661 E davx5   : 	at at.bitfire.davdroid.syncadapter.SyncAdapterService$SyncAdapter$onPerformSync$1.invoke(SyncAdapterService.kt:1)
03-22 13:53:45.744  8632  9661 E davx5   : 	at at.bitfire.davdroid.util.ConcurrentUtils.runSingle(ConcurrentUtils.kt:21)
03-22 13:53:45.744  8632  9661 E davx5   : 	at at.bitfire.davdroid.syncadapter.SyncAdapterService$SyncAdapter.onPerformSync(SyncAdapterService.kt:108)
03-22 13:53:45.744  8632  9661 E davx5   : 	at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:354)
03-22 13:53:45.744  8632  9661 I davx5   : [syncadapter.JtxSyncAdapterService] jtx sync complete
03-22 13:53:45.744  8632  9661 I davx5   : [syncadapter.SyncAdapterService] Sync for (at.techbee.jtx.provider, Account {name=redacted, type=bitfire.at.davdroid}) finished
03-22 13:53:45.744  8632  9661 I davx5   : 	PARAMETER #0 = SyncResult: stats []

```

**Comment by patrickunterwegs** [comment]
Hey, yes, the upgrade is required, both apps have been provided on both stores, but f-Droid hasn't built the apps yet. This caused this conflict now. For now it would be better if you use either both apps from f-Droid or both from Google Play!

**Comment by patrickunterwegs** [comment]
Just for further info: 
f-Droid is aware of the issue: 
https://forum.f-droid.org/t/f-droid-update-repository-issue/21656/2

The apps on f-Droid weren't built since March, 11th: 
https://monitor.f-droid.org/builds/build

The new versions of jtx Board and DAVx5 were provided for f-Droid on March, 13th.

**Comment by patrickunterwegs** [comment]
As this issue is still not solved on f-Droid side, I have opened a new topic in their forums: 
https://forum.f-droid.org/t/f-droid-monitor-missing-builds/21758

**Comment by bugsyb** [comment]
Thank you! Got it working pushing the way manually.
Thanks for help!

**Comment by rogercreagh** [comment]
There have been two update cycles on Fdroid since this issue arose (apparently due to some other app crashing their updates.

The most recent update cycle just finished with 
`[Licaon_Kter](https://gitlab.com/licaon-kter)
[@licaon-kter](https://gitlab.com/licaon-kter)
· [6 hours ago](https://gitlab.com/fdroid/admin/-/issues/382#note_1341723090)
Author
Reporter
Current cycle hit 72h time out, so many apps were not even tried.

Next cycle... 🤷`
and still no update. Since my primary device doesn't have PlayStore (it runs a non Google version of Android) I'm stuffed. I understand that jtx 2.3.0 is not compatible with Davx previous version. So even getting the jtx apk wouldn't help.
Strangely Davx5 is no longer listed on the fdroid website and fdroid is no longer listed on the davx5 website.

Is there any end in sight to this empass

**Comment by patrickunterwegs** [comment]
Honestly with their latest reply I'm not so sure if this will get solved so soon... But I'm afraid there's nothing we can do...

**Comment by rogercreagh** [comment]
There is slightly morehopeful news from Fdroid today:

```
Last published cycle hit the 72h time limit, with many apps adding up (since the last delayed cycle) this is more probable unfortunately.

After the current emergency cycle: https://forum.f-droid.org/t/important-f-droid-broken-after-android-version-upgrade/21902/ a new one will start, hopefully it gets the chance to build all missing ones.
```

**Comment by rogercreagh** [comment]
Yay!!!! 2.03.00 has appeared on fDroid along with Davx5 4.3.1

You can close this issue I think

**Comment by patrickunterwegs** [comment]
Thanks @rogercreagh for the update 🙂 
Closing this issue now.
