### ISSUE TITLE
[BUG] FDroid Version too old

### ISSUE THREAD

**Issue by DhruvaSambrani** [TechbeeAT/jtxBoard#404]
**Describe the bug**
The Fdroid version is 2.02, where the latest is 2.3. Can this be updated from the project side?

**Comment by patrickunterwegs** [comment]
Hey @DhruvaSambrani , sorry, no, this is an issue on f-Droid side, please also have a look at my answer in 
https://github.com/TechbeeAT/jtxBoard/issues/393

**Comment by rogercreagh** [comment]
This can be closed - fDroid has caught up

**Comment by patrickunterwegs** [comment]
Thanks @rogercreagh for the update 🙂 
Closing this issue now.
