### ISSUE TITLE
[Feature] Allow filtering out of COMPLETED task even when PERCENT-COMPLETE < 100

### ISSUE THREAD

**Issue by OlegArenz** [TechbeeAT/jtxBoard#405]
**Is your feature request related to a problem? Please describe.**
Some e-mail providers (at least mine) do not seem to support the PERCENT-COMPLETE field. When setting this field, it will be reset to 0 the next time the calendar entry is synced by the app. As jtx Board only hides completed tasks if PERCENT-COMPLETE==100, completed tasks will show up again after every sync. This makes the app unfortunately completely unusable for me. Neither the option to sync status, progress and completed; nor any other option currently offered by the app can circumvent this problem.

**Describe the solution you'd like**
When setting the filter to "hide completed tasks" ("Fertiggestellte Aufgaben ausblenden" in the German app), all tasks that have the "COMPLETED" field set, should be hidden, irrespective of their PERCENT-COMPLETE field. This behavior is consistent with other apps, e.g. OpenTasks, which correctly hide completed tasks with PERCENT-COMPLETE=0.
I suggest to change the behavior of this filter to hide if (COMPLETED or PERCENT-COMPLETE==100).

**Describe alternatives you've considered**
- A new option could be added, to make it possible to keep the old behavior (I'm not sure if this is necessary).
- Instead of hiding tasks that are either COMPLETED or have a PERCENT-COMPLETE==100, one could only hide the COMPLETED tasks. However, from what I understood from the RFC, The PERCENT-COMPLETE field can be different for different users working on the same task,  and people who completed their parts of a task may want to hide the ToDo entry, even though other people have not completed it.

**Additional context**
I am using jtx Board with DAVx5 on a caldav server hosted by hetzner.com
The webinterface of hetzner does not allow setting the percentage, and when I set it via jtx Board, OpenTask or thunderbird, the field gets reset to 0 after the next sync. However, both thunderbird and OpenTask correctly hide the completed tasks anyways.

**Comment by patrickunterwegs** [comment]
Hey @OlegArenz !
Thank you for your request and thorough description! 
I see the point and I'll check that soon. I'm currently on vacation, so please be a bit patient 😉

**Comment by OlegArenz** [comment]
Sure. Thanks for considering the change!

**Comment by patrickunterwegs** [comment]
Hey!
So I've checked this and implemented it. I'll put it in 2.3.1. It's a bit more tricky than initially thought, because considering an entry as done also when the status is completed can lead to inconsistencies (e.g. having a progress < 100 but completed or the other way round). 
This is something that must be accepted in this case. But the UI would show an entry as checked (checkbox), when the progress is either 100 OR the status is completed. The same logic is then applied for the 'hide completed' filter. 

It would be great if you could also have a closer look and maybe give feedback once it's available 😉

**Comment by OlegArenz** [comment]
Awesome, thank you very much!
