### ISSUE TITLE
[BUG] Back button doesn't close filter bottom sheet

### ISSUE THREAD

**Issue by mueller-ma** [TechbeeAT/jtxBoard#436]
**Describe the bug**
Pressing the back button doesn't close the bottom sheet with the filter and group options for tasks.

**To Reproduce**
1. Go to tasks tab
2. Open the filter bottom sheet
3. Press back

**Expected behavior**
The bottom sheet is closed.

**Screenshots**
The app is closed.

**Device and version:**
 - Device: [e.g. Samsung Galaxy S22]
 - Android version [e.g. Android 11] 12
 - jtx Board version: [e.g. 2.1.0] 2.02.02-rc5.ose (latest on F-Droid)
 - Downloaded from: [e.g. Google Play, f-Droid, ...]

**Comment by patrickunterwegs** [comment]
Thanks! It's true that this is pretty bothering. 
I have tried out a few things and I couldn't make it work, the back handling was always ignored no matter what I did. So I searched for bugs, I think this might still be an issue in the library, so I commented here: 
https://issuetracker.google.com/issues/271303558

Let's see what comes out of this.

**Comment by patrickunterwegs** [comment]
Okay, so finally an update in the Google issue tracker brought me to the right track. I'll remove this optional enableOnBackInvokedCallback parameter as it seems to be the root cause of the problem.
