### ISSUE TITLE
[Feature] Quickly delete finished subtasks

### ISSUE THREAD

**Issue by mueller-ma** [TechbeeAT/jtxBoard#437]
**Is your feature request related to a problem? Please describe.**
I have one task that I use as a shopping list. Every item I want to buy is a subtask. When I'm done with shopping, I want to remove all checked subtasks.

**Describe the solution you'd like**
Add an entry to the overflow menu in the task detail view (next to 'share as mail', 'share as ics'...) that removed all checked subtasks.

**Describe alternatives you've considered**
I saw such a button in https://f-droid.org/de/packages/org.tasks/ and it was very convenient.

**Comment by patrickunterwegs** [comment]
Hi @mueller-ma , I will check this option. Basically I don't want to extend the top menu for such a functionality, it's already pretty long anyway. But I'm thinking maybe I'd add another button in the bottom app bar with vertical 3 dots that opens another menu where the done items can be purged.

**Comment by mueller-ma** [comment]
Yesterday I got the update with this button and when I pressed it, it removed all done tasks, but also all repeating tasks with at least one done occurrence.

**Comment by patrickunterwegs** [comment]
I will check in #532

**Comment by patrickunterwegs** [comment]
Thanks @mueller-ma , I found the issue and I'll provide a new version within the upcoming week!

**Comment by bmix** [comment]
Why not just add an option, to hide all finished subtasks?
