### ISSUE TITLE
[Feature] Add option to set notifications as ongoing

### ISSUE THREAD

**Issue by mueller-ma** [TechbeeAT/jtxBoard#442]
**Is your feature request related to a problem? Please describe.**
It's possible to swipe away alarm notifications which can happen by accident. Then I have no reminder for a task outside of the app anymore.

**Describe the solution you'd like**
Add an option that sets `setOngoing(true)` for notifications (https://developer.android.com/reference/kotlin/androidx/core/app/NotificationCompat.Builder?hl=en#setOngoing(boolean))

**Additional context**
If you agree that this feature is useful. I can implement it.

**Comment by patrickunterwegs** [comment]
Hey @mueller-ma !
Thanks and also for the offer to implement it! :)
I'm not sure if this is so good after all. But let's discuss it. The problem is that I think users are very used to just dismiss notifications.
I assume with this option you need an action button to dismiss the notification, but in order to appear, the notification needs to be expanded... 
I think this would be pretty bothering for many users. 

I was actually considering am option to make notifications appear again if they were dismissed (like a scheduled job every hour), also to cover the case that a notification got lost during restart of the phone...

What do you think?

**Comment by rogercreagh** [comment]
I, for one, would find sticky notifications a pain.

The problem of losing notifications, either by restart, or by simply clearing them from the splash screen and then forgetting you had them, is more of an Android system problem. I would like it if the system itself kept a log of the last (say) 50 notifications across all apps with datetime issued and cleared and which the user could access. (maybe this exists and I've simply never found it)

For a single app solution (eg within jtxBoard) perhaps making a notification history available would serve? But not an in-your-face one please!

**Comment by patrickunterwegs** [comment]
I agree with you, @rogercreagh 
To solve this I was also considering recurring notifications, but I'm afraid this will confuse people more than it would help, so I already wanted to reject this recurring notifications option...

**Comment by patrickunterwegs** [comment]
I thought about it again, maybe it's still worth considering setOngoing(true) as an optional setting. 
I am not a fan of adding another setting in the settings section, but if it is useful, let's consider it. @mueller-ma , do you know if the notification would automatically pop up again if the phone is restarted?

**Comment by mueller-ma** [comment]
> I assume with this option you need an action button to dismiss the notification, but in order to appear, the notification needs to be expanded...

I wouldn't add a button to dismiss the notification and only make it possible to dismiss it by finishing the task.


> I would like it if the system itself kept a log of the last (say) 50 notifications across all apps with datetime issued and cleared and which the user could access. (maybe this exists and I've simply never found it)

This is a feature in AOSP. You can try to create a widget of the settings app called "settings shortcut" and then select "notification history". At least for me this wouldn't help much as I need to have a look at this log.


> To solve this I was also considering recurring notifications

The issue with recurring notifications is that the might make a sound whenever they appear. However I don't need to be notified every hour or so that a task isn't finished yet.

> do you know if the notification would automatically pop up again if the phone is restarted?

AFAIK the Android framework isn't capable of showing notifications after restart. Maybe the app has to keep an internal list of shown notifications that is always updated when a notification is shown or dismissed. After restart this list can be read and the notifications can be shown again.
