### ISSUE TITLE
[BUG] Contact for Journal not being sync'd (Nextcloud)

### ISSUE THREAD

**Issue by rogercreagh** [TechbeeAT/jtxBoard#444]
**Describe the bug**
The contact element does not get written to the server, although it remains in the local copy.
**To Reproduce**
1. Create a Journal entry, add Contact details for the entry (text and/or email address)
2. Save and sync the entry through Davx5 to a Nextcloud server
3. Check the details on the server either by 
   a) examining the data field for the calendar object in phpmyadmin or by 
   b) downloading it to a different application
   c) sync'd with jtxBoard on a different device 
5. There is no CONTACT element for the entry
6. Shut down the original device and restart and reload jtxBoard - the contact information is still present so must have been cached locally and not cleared by the sync (obviously the etag hasn't changed), but if you edit the entry elsewhere and sync back then the etag has changed so the contact details should have been cleared on the local copy by a new sync but the original local copy is still persisting. 

**Expected behavior**
CONTACT information should be written to the server and available on other instances. 

Possibly subsidiary problem:
I haven't checked with other elements but is it expected behaviour that if a server copy is edited and sync'd back from another device so that an optional element is cleared and no longer exists in the journal data (ie the element is removed, rather than being set to an empty string) then when it is reloaded on the original device the original local data is kept?

**Device and version:**
 - Device:  Blackview 7100 and Boox NovaAir
 - Android version Android 12 and Android 11
 - jtx Board version:  2.03.00-ose
 - Downloaded from: f-Droid
 - Davx5 4.3.1

**Comment by patrickunterwegs** [comment]
Thanks, I will check what's wrong with the contact field!

**Comment by patrickunterwegs** [comment]
> Possibly subsidiary problem:
I haven't checked with other elements but is it expected behaviour that if a server copy is edited and sync'd back from another device so that an optional element is cleared and no longer exists in the journal data (ie the element is removed, rather than being set to an empty string) then when it is reloaded on the original device the original local data is kept?

I'm not sure if I can follow the explanation. But basically if you delete an entry on one device, it should be deleted on all devices.
Could it be that the sync on the original device just want done yet?

**Comment by rogercreagh** [comment]
Well this arose with the Contact element problem - so if the contact element is not being written back to the server then I guess it may also not be checked if it is read back from the server (or is absent for from the server copy) so the original value is stored locally and kept.

If you fix the problem with contact not being sync'd then there may be no further problem. Lets wait and see.

**Comment by patrickunterwegs** [comment]
> If you fix the problem with contact not being sync'd then there may be no further problem. Lets wait and see.

Alright, thanks, I'll have a closer look 👍

**Comment by patrickunterwegs** [comment]
The contacts field was indeed missing in the sync, it's fixed now in 
https://github.com/bitfireAT/ical4android/pull/91
and should be part of the next DAVx5 version!
Thanks for the issue report!
