### ISSUE TITLE
[Feature] Provide format hint for Location geolocation

### ISSUE THREAD

**Issue by rogercreagh** [TechbeeAT/jtxBoard#445]
I have no idea what format the location data is supposed to be in. I read somewhere that jtxBoard integrates with Google (playstore version) or OSM (fDroid version) to display locations - but how???? I expected to be able to enter Lat/Long in the format provided by dropping a pin on the location on the relevant map and copying the lat/long. But although it gets saved nothing happens when I click on it in jtxB. 
Shouldn't it open the map in the same way as clicking on a url opens the browser?

Even aside from that it would be helpful to provide some hint as to acceptable format (as with url's)

**Comment by patrickunterwegs** [comment]
Hello @rogercreagh, please always add which version of thx Board you are using.

Open street maps was added in 2.3.1 for the version on f-Droid and the GitHub apk, on f-Droid it is not available yet.

**Comment by rogercreagh** [comment]
Ah - I've just upgraded to 2.3.0 as fDroid has finally got that far. I thought it was in 2.3.0. Closing this issue pending 2.3.1 appearing - with some hint as to format??? (if there is no hint then I'll raise a new issue unless you do!

**Comment by patrickunterwegs** [comment]
Alright, yes, let's check again when 2.3.1 is picked up by f-Droid, I assume this cycle will be faster! :-)
