### ISSUE TITLE
[Feature] Use FMTTYPE to flag if description contains markdown codes

### ISSUE THREAD

**Issue by rogercreagh** [TechbeeAT/jtxBoard#446]
Earlier on there was a discussion about allowing/defaulting markdown codes in descriptions. Also the possible use of STYLED-DESCRIPTION ( [rfc9073)[https://www.rfc-editor.org/rfc/rfc9073#name-styled-description) ) to allow HTML versions.

Here is a simple non-breaking enhancement to flag the presence of markdown codes in the description text.
If markdown codes are present at a FMTTYPE=text/markdown parameter to the description.

eg DESCRIPTION;FMTTYPE=text/markdown:This is your description text

This shouldn't break any existing applications out there, but would allow me to tell when loading an entry from the server to determine whether to show a markdown editor or a plain text one for the description, and whether to bother to parse the description for markdown codes when displaying it (less of an issue since it is easy enough to always parse for markdown)
And correspondingly it would allow jtxBoard to be able to parse markdown and show the markdown editor according to the content fmttype rather than relying on a global setting.

I'm pretty sure that other applications will simply ignore, but preserve, the format type parameter if they don't know what to do with it (that's how I read the spec, but I could be wrong)

**Comment by patrickunterwegs** [comment]
But how would the app determine whether there is markdown text or not?
Jest because markdown is enabled doesn't mean that there's markdown text and the other way round...

**Comment by rogercreagh** [comment]
With a new item if the markdown editor is in use (app setting) then set `FMTTYPE=text/markdown`, otherwise don't

- Subsequent display on any app respecting the format type parameter uses it to parse markdown or not
- Subsequent display on any app not respecting the fmttype parameter displays as plain text
- Subsequent editing using an app which respects the fmttype parameter uses the appropriate editor but **may** allow the user to toggle the editor. When the edit is saved (or autosaved) the FMTTYPE is updated to reflect the current status
- Subsequent editing on an app that doesn't respect or recognise the parameter will edit as plain text and not change the parameter when saving. So markdown text on that app would be edited as plain text but the original app would still recognise it as markdown

Of course an app might be created to always assume markdown in which case it should always set  `FMTTYPE=text/markdown`

Perhaps we should go one step further and also use `FMTTYPE=text/plain` rather than omitting the fmttype. This would allow an item to be explicitly locked to plain text unless the user changed it while editing - either by changing an app setting or by some other mechanism - I'd quite like the setting to only apply to the current item, which using fmttype would allow.

**Comment by patrickunterwegs** [comment]
Personally I frequently use the options to switch between plain text and markdown formatted text, depending on the context and what is faster for editing. I want to keep this idea.
The idea of adding markdown was to allow a minimum of formatting options that wouldn't break the standard and ensures compatibility with other apps. 

I don't see the need and the use of that additional field. Either it would restrict the user to stick to the initial setting after saving once, or it would give the user the full flexibility, but then we would end up in the same situation as now, just that there might be an FMTTYPE that in reality doesn't say anything about the content as again it could just be plain text without tags or text with tags shown as plain text. 

But we can keep this in the discussions.
