### ISSUE TITLE
[Feature] Generalize DAVx5 references to also handle other sync apps correctly (esp. kSync)

### ISSUE THREAD

**Issue by patrickunterwegs** [TechbeeAT/jtxBoard#469]

**Comment by patrickunterwegs** [comment]
Hello @JorisBodin !
I hope this message reaches you! I found your user as developer (or at least commit responsible) for kSync.
First of all thank you for setting jtx Board as the recommended default app for tasks sync in kSync!

So far jtx Board has some places in the code that are specific for DAVx5. I am working on making it more general, so that any reference to a sync app refers the correct app (currently DAVx5 or kSync). 

But there are two issues that I would like to address on your side: 
- jtx Board 2.3.0 requires DAVx5 4.3.1. As the sync adapter still allows unknown apps to add new entries (and kSync is currently still an unknon app for jtx Board), the sync works with kSync 4.3.0. BUT: There is a major issue when people use recurring entries which could cause a mess when people use kSync 4.3.0 with the jtx Board 2.3.0 and later. On the one hand I would ask you to update your kSync to 4.3.1 from DAVx5, on the other hand I want to add a version check also for kSync to avoid users continue using an incompatible combination of kSync and jtx Board. So I also want to align with you as the updated version of kSync should be released before I release jtx Board 2.4.0 (which will contain the version check). So when would you plan to update to 4.3.1?
- It's great that you recommend jtx Board in kSync, but I couldn't create a collection with VJOURNAL support as it was rejected by the server from DAVx5 and online I could only create a new calendar with VTODO and VEVENT support. I think it would be great for your users if you could also enable VJOURNAL support on your server, otherwise users can only use parts of the capabilities of jtx Board!

That's it for now and thank you 😉 
Patrick

**Comment by dalecooper** [comment]
@patrickunterwegs stumbled upon this issue while trying to sync jtx Board journals & notes with Infomaniak, to no available.
Not sure if you ever had any reply with @JorisBodin , so I'm wondering if you have any info on the possible support of VJOURNAL by Infomaniak ?
Cheers

**Comment by patrickunterwegs** [comment]
Hey @dalecooper !
I have been in contact with Joris via E-Mail, bis reply on this topic was:

> The back team has to implement the VJOURNAL, it is not planned. But I can make sure we discuss it internally :)

But then we didn't follow up on this. 
@JorisBodin do you have an update on this topic?

**Comment by JorisBodin** [comment]
@patrickunterwegs we haven't had any requests for VJOURNAL support (apart from yours)
But if we do, it will be considered and planned for implementation

@dalecooper uses the "feedback" button in calendar.infomaniak.com

**Comment by dalecooper** [comment]
@JorisBodin Thanks for your input. Did it yesterday already, not sure your "average user" (no offense) will even know what I'm talking about so I'm not really expecting any upvote on this one, but well, you never know...

**Comment by patrickunterwegs** [comment]
Thanks @JorisBodin for your reply!

@dalecooper , could you please also paste a link to your request on infomaniak here?

**Comment by dalecooper** [comment]
@patrickunterwegs here you go : https://feedback.userreport.com/42a58130-f8ec-4d45-9fbb-163466a297fe#idea/424730
