### ISSUE TITLE
[Feature] Dark mode for the widget

### ISSUE THREAD

**Issue by tiptruck** [TechbeeAT/jtxBoard#470]
As above.  Dark mode widgets look great with some backgrounds when the transparency is set high.

**Comment by patrickunterwegs** [comment]
Hello @tiptruck ,
please use the template for feature requests to get some context. Which app and android versions are you using?
The widget already supports dark mode, but when you set a transparency, the update of the widget is delayed due to technical constraints in Android!

**Comment by tiptruck** [comment]
Sorry.  Details below.  I'll have another look.

Regards Craig

Device and version:

    Device: [e.g. Samsung Galaxy S22] Samsung Tab S7
    Android version [e.g. Android 11] 13
    jtx Board version: [e.g. 2.1.0] 2.03.01-rc04.ose (203010004)
    Downloaded from: [e.g. Google Play, f-Droid, ...] F-droid

**Comment by tiptruck** [comment]
Thanks.

The widget does support dark mode when the system is set to dark mode.

I was trying to change the text colour on the widget to white and said things awkwardly.

Regards Craig

**Comment by patrickunterwegs** [comment]
Alright, thanks!
But I'm not sure if I can follow. Does that mean the issue is not relevant anymore or were you just thinking of a setting in for the widget to override the system setting?

**Comment by tiptruck** [comment]
A setting in the widget to override the system setting.  A cute tweak that if it much of your time is not worth doing.

Regards Craig

**Comment by patrickunterwegs** [comment]
Alright, thanks, generally colors in the widget are a bit complex if you consider all options like dark/light themes, dynamic colors and its combinations - and also with different android versions (regrettably older versions need special considerations). But I'll have a look what could be done 👍

**Comment by patrickunterwegs** [comment]
Hey @tiptruck , in v2.4.0 there will be the option to choose a color for the widget background and the widget cards (each entry). There you can set any color. I would say this would make a dedicated dark option for the widget kind of obsolete. What do you think?

**Comment by tiptruck** [comment]
That sounds great.  Thank you

**Comment by Flavelius** [comment]
Would it be possible to allow the text to be white? I have a darker wallpaper and with transparent widget background the text becomes very hard to read

**Comment by patrickunterwegs** [comment]
> Would it be possible to allow the text to be white? I have a darker wallpaper and with transparent widget background the text becomes very hard to read

Hi @Flavelius !
Currently the text color depends on the dark mode setting. So currently when yo change to dark mode, the text would become bright. 
But I understand that this is not very good, like in your case. I will change this behavior and let the widget calculate if the text should be shown in white or black (to maximize the contrast).

**Comment by patrickunterwegs** [comment]
Sorry @Flavelius , I need to correct myself, the implementation was already done in a way to calculate a contrast color, but I made a small mistake that caused it to not work as expected, so actually it's a bug. 
I have corrected the mistake, it will be in the next version. 
Just one thing to keep in mind: The widget will calculate the best contrast for the selected color (independent of the transparency). So if you would like the text to be white while the widget background is fully transparent, you would still need to select a black background. 
I know, it's a little workaround, but I still prefer it to adding another config option. I hope that's okay for you as well.

**Comment by Flavelius** [comment]
If it results in the expected outcome then it's perfectly fine. Thanks!

**Comment by Flavelius** [comment]
Thanks for the improvement. There's a tiny issue, text looks as desired now, but the checkboxes still change color depending on actual system night mode, and are dark at daytime

**Comment by patrickunterwegs** [comment]
> Thanks for the improvement. There's a tiny issue, text looks as desired now, but the checkboxes still change color depending on actual system night mode, and are dark at daytime

Thanks, I'll have a look in. the new issue!

**Comment by patrickunterwegs** [comment]
@Flavelius I have done the change and put it in the next beta. The checkbox should take the color of the text in the future. 
I'm not sure if that works on all devices though, I can also see that Samsung does a special thing here with checkboxes, but let's see.
