### ISSUE TITLE
[BUG] Filter "Start In Future" only counts days not time

### ISSUE THREAD

**Issue by tiptruck** [TechbeeAT/jtxBoard#479]
**Describe the bug**
"Start In Future" filter will only hide tasks that are for future days but will show tasks that are set for the same day but a future time.

**To Reproduce**

1. From board view
2. Select all special filters and unselect Start In Future
3. Create a task that has a start date of the current day and a start time set to later in the same day.
4. Go back to board view.  The new task still shows even though it has not yet started.

**Expected behavior**
The task set with a future time should be hidden until that time is reached.

**Screenshots**

**Device and version:**
 - Device: [e.g. Samsung Galaxy S22] Samsung Tab S7
 - Android version [e.g. Android 11] 13
 - jtx Board version: [e.g. 2.1.0] 2.03.01-rc04.ose (203010004)
 - Downloaded from: [e.g. Google Play, f-Droid, ...] F-Droid

**Comment by patrickunterwegs** [comment]
Hey @tiptruck , thanks, I'll check. May I ask to which timezone you have set your phone? (There were some issues in the past related to the timezone, so it would be good to know when I check)

**Comment by patrickunterwegs** [comment]
I just tried to reproduce the issue and I read it more carefully. 
You say you have all filters activated except start in future. But this means also that you have activated "Start today", which would include the task, right?

**Comment by tiptruck** [comment]
Good morning.  I'm in Bangkok (+7).  I must admit to getting quite mixed up with the filters.  If I deselect all or select all (except for the hide completed option), it seems to be the same result, so I'm a little confused.

I created two tasks to test.  One started two hours ago and one starts two hours in the future.  I then went through the options that deal with the start date/time (4 options) and systematically switched them to cover all combinations (I think).

There were no selections or combinations that had one of the test tasks filtered and the other unfiltered.

To look at the timezone, I did the same as above but started one task 8 hours in the past and the other 8 hours in the future.  No change.

**Comment by patrickunterwegs** [comment]
Hey @tiptruck , I can't reproduce this problem. For me it always works. I also had a look at the code and couldn't find anything suspicious.

Could you please make a specific, reproducible example with screenshots of the entries and your filter settings?

**Comment by tiptruck** [comment]
Dear Patrick,

My error through not understanding the logic behind the filters.  I apologise for wasting your time.  

Is this correct?
When a filter is selected only tasks matching the criteria will be shown.  If another filter is selected then there is an OR between them so items that match filter 1 OR filter 2 will be shown

I'm looking forward to the 2.4.0 release.

Regards Craig

**Comment by patrickunterwegs** [comment]
Hey Craig, no worries, I'm glad we got it sorted out! 😉

Yes, the filter options within one block are all with OR conditions whereas the blocks (special filters, collections, status,...) are processed with AND conditions! 
In other words, if you have a special filters and a filter by status, this means in order for an entry to appear, ANY conditions of a special filter must be fulfilled AND any of the status filters! (Behind the scenes there's basically an SQL that is constructed)
