### ISSUE TITLE
[Feature] Add "Sub-task of" chip to sub-task cards

### ISSUE THREAD

**Issue by tiptruck** [TechbeeAT/jtxBoard#480]
When selecting flat view, it is confusing which subtask belongs to which task.  

For example.
Create a task "Trip to Australia" with the sub-tasks "Book flights" and "Book rooms"
Create another task "Trip to Malaysia" with the sub-tasks "Book flights" and "Book rooms"
Select "Flat view" from the three dots menu.
There are two entries for "Book rooms" and two entries for "Book flights".  
This is an extreme example but it requires careful naming of sub-tasks to stop confusion.

**Describe the solution you'd like**
Add a "Sub-task of" chip to the card of the sub-task 

Device and version:
Device: [e.g. Samsung Galaxy S22] Samsung Tab S7
Android version [e.g. Android 11] 13
jtx Board version: [e.g. 2.1.0] 2.03.01-rc04.ose (203010004)
Downloaded from: [e.g. Google Play, f-Droid, ...] F-Droid

**Comment by patrickunterwegs** [comment]
Hey @tiptruck , thanks, understood and makes sense, I'll check that soon!
