### ISSUE TITLE
[BUG] Orphan EXDATE property on some Journal items

### ISSUE THREAD

**Issue by rogercreagh** [TechbeeAT/jtxBoard#490]
**Describe the bug**
When I collect Journal items from the server I find that a few of them have an EXDATE property although no RRULE is specified.

**To Reproduce**
I am unclear how this is happening as I never knowingly use recurrence on Journal items (it seems an odd thing, but there must be a use case since it is specified in rfc5535 for vjournal items as well as the obvious use for vevent)

I _think_ it might happen if while editing an item I show all options and accidentally fat-finger the recurrence button.

In any event no recurrence is saved - either because I never specified dates or more likely because the accidental fat-finger was a double and it got turned off straight away.

**Expected behaviour**
If an item is saved with no recurrence, or the recurrence is deleted then the EXDATE should also be cleared

**Screenshots**
n/a

**Device and version:**
 - Device: Blackview 7100
 - Android version Android 12
 - jtx Board version: 2.3.1 and earlier
 - Downloaded from: f-Droid

**Comment by patrickunterwegs** [comment]
Thanks, I'll check. 
As announced the recurrence-handling was changed in jtx Board 2.3.0, but still, such an orphaned EXDATE should not happen. I'll make sure it gets properly removed when the recurrence is deactivated.
