### ISSUE TITLE
[Feature] Check location picker for ose

### ISSUE THREAD

**Issue by patrickunterwegs** [TechbeeAT/jtxBoard#498]

**Comment by rogercreagh** [comment]
For me using 2.3.1-rc04 ose on android12 with OSMAnd+ installed it allows me to enter any text in the Location field but it doesn't attempt to look up that address (eg if it is a postcode) - the spot next to the lat/long boxes just pulls the current location from the device - which is ok.
A location picker would be something different - spawning OSM and tking the location clicked on the map. It doesn't seem to do that.
If I open osm and click a location and share then copy coords to clipboard it pastes as 50.63044&deg;N, 4.36086&deg;W for example (not my current location) which I then have to paste into the location text and copy/paste the numbers only into lat & long.

**Comment by patrickunterwegs** [comment]
Yes, I haven't added the location picker before, I'm just finalizing it! It will be a new icon with a map in the same section.
