### ISSUE TITLE
[Feature] Allow conversion between Note and Journal by adding/removing the date

### ISSUE THREAD

**Issue by StefanoWoerner** [TechbeeAT/jtxBoard#504]
**Problem**
I sometimes want to add dates to notes to make them a journal, e.g. when I want to "archive" them to some specific past date. On the other hand, I sometimes want to convert a journal to a note, e.g. when I thought something would only relate to a certain date, but it later turns out that it is useful as a general note.

**Proposed solution**
Allow conversion between Note and Journal by adding/removing the date. Since both are VJOURNALs anyway, this could be easily achieved. Since other applications do not differentiate between journals and notes as strictly as jtxBoard, this would also lead to better integration with these other applications.

**Alternatives**
The option to have a joint UI for Notes and Journals, without differentiating between them. (Adding/removing dates should still be allowed.)

**Current workaround**
Use Evolution to remove/add dates on desktop.

**Additional context**
Probably it would be nice to have the option of a joint view in any case. Again, since other applications (e.g. Evolution) do not differentiate between Journals and Notes, this could lead to a nicer integration with other applications.

**Comment by rogercreagh** [comment]
I like the idea of being able to convert by adding/removing date. Useful.

But **not** the joint view and common UI though, I think that gets confusing as it means Notes would appear in the default list  on their created date (or modified) or possibly all appearing at the beginning or end of the list whereas you probably want them sorted by default by title or category or status.

I really like the fact that jtxB distinguishes between Notebooks and Journals and I would prefer that other apps did the same.

**Comment by patrickunterwegs** [comment]
Hey, thanks @StefanoWoerner  for the structured proposal!
Sure, I have thinking about this anyway, somehow I have been waiting until somebody requests it 😉 
You can already copy an entry to another type, so transforming it would probably be easy to achieve.

I'm just thinking where there could be an appropriate place. I'm thinking about extending the copy menu (if you go to a single entry without editing, at the bottom there's the copy symbol) - and just add options to convert the entry to another type. Or do you have a better idea?

**Comment by StefanoWoerner** [comment]
Hey, thanks for considering it!

I did actually not know about the option to copy an entry to another type. It seems I just learned about a cool feature!

Until now, I had never actually clicked the copy icon, so I always assumed that entries can only be copied within a type.

I personally think a second icon next to the copy icon for "moving"/converting the entry would be a bit more intuitive than extending the menu. But in any case, I also think that it would fit right in with the copy menu. Unlike the copy menu, the conversion menu should also be available while editing and not disappear when in edit mode.

**Comment by StefanoWoerner** [comment]
Actually, now that I think about it: could/should the copy menu maybe also be available while editing?

Another option would be for the copy menu to be replaced by the conversion/moving menu when in edit mode. But I think that wouldn't be intuitive.

**Comment by patrickunterwegs** [comment]
Hey @StefanoWoerner , @rogercreagh ,
the convert function is now available in the beta on Google Play. 
I have put it in the menu on top for some reasons: 
- I didn't want to add another icon at the bottom bar while editing, it's already pretty full and the action to convert is not so common
- I didn't want to mix it with the copy functionality. The copy functionality would create a new entry and bring you there (with a visual transition so it's clear that you are editing something new). This is also the reason, why I don't want to allow the copy-functionality while editing, I'm afraid it gets confusing for the user when an entry is edited and then copied (e.g. what would you expect to happen for changes that have not been saved yet? Copy only to the new or also save the changes in the old entry?) Like that, it avoids the problem and it's always clear that the entry is saved before.
