### ISSUE TITLE
[BUG] Many meta infos for a task block out title and description in Kanban view

### ISSUE THREAD

**Issue by duncan-blues** [TechbeeAT/jtxBoard#507]
**Describe the bug**
Many meta infos for a task block out title and description in Kanban view.

**To Reproduce**
1. Create an element with many individual meta data items like start date, due date, tags, priority et al
2. Switch to Kanban view
3. Only the meta information at the top of the entry is visible and the title and description is pushed out of view

**Expected behavior**
At least the title of the entry should always be visible and with space constraints should be prioritized over displaying of meta information

**Device and version:**
- Device: Samsung Galaxy S10e
- Android 12
- jtx Board version: 2.04.00.beta07.gplay

**Comment by patrickunterwegs** [comment]
Hey @duncan-blues !
Thanks for the beta-feedback and issue report :-)
Indeed that's a problem. I have adapted the view now to always show all badges, max. 4 lines of summary and max. 4 lines of description. I hope that's a good compromise. 
I didn't want to cut on the meta data badges as it would be very difficult to decide where to make the cut. I'll upload a new beta soon!

**Comment by patrickunterwegs** [comment]
Hey @duncan-blues , the new beta is available now on Google Play! :-)

**Comment by mmind** [comment]
Since the last update (to 2.04.00-rc12.gplay), all category badges are displayed in the list view. 

Depending on the number of badges the title and summary become barely visible. Especially in the compact view this is visually very, very distracting and unnecessary because the categories should only be there for filtering.

Can there at least be an option to hide these badges?

**Comment by patrickunterwegs** [comment]
Hi @mmind , I have adapted the row with the badges here: #537 
Basically it will always be one line that can be scrolled (if needed). It wil be in the upcoming version 2.4.1!
