### ISSUE TITLE
[Feature] Alarm based on geographical location

### ISSUE THREAD

**Issue by khao-soi** [TechbeeAT/jtxBoard#511]
**Is your feature request related to a problem? Please describe.**
Trigger an alarm (just like time based) when a pre-defined location is approached.

**Describe the solution you'd like**
Just like the time based alarms, a location based alarm could be triggered when approaching / reaching a pre-defined geolocation. It could come in handy when you want to be reminded to do something at a certain place, but you're not sure when you're going there next. Since the predefined location is probably never met exact, its needs to be defined by a radius of a few 10m or so.

**Describe alternatives you've considered**
Its an alternative to the time based alarm.

**Additional context**
I don't know enough about Android's location API to tell if it would work properly without accesssing the location all the time and disable battery optimization, which could be unwanted.

**Comment by patrickunterwegs** [comment]
Hey @khao-soi !
Thanks for the feature request :-)
I've been thinking about this a longer time ago (https://gitlab.com/techbeeat1/jtx/-/issues/53) but I was hesistating as on the one hand it's not a killer feature, on the other hand there were just other priorities. But also the iCalendar standard doesn't specifically support it. But I'll check it out and see what I can do!

This is for my own reference about the implementation: https://developer.android.com/training/location/geofencing

**Comment by khao-soi** [comment]
Thank you for the reference. That looks well implemented and documented.

**Comment by basings** [comment]
For anyone stumbling over this, it's only available for the google play store version, not ose.

**Comment by patrickunterwegs** [comment]
Sorry for not mentioning this also here. But yes, Geofencing is only available on the Google play version. The library is not open source - in general location based services are basically commercial on Google (there is just a free quota). That's why it's only available on the Google play version.
