### ISSUE TITLE
[BUG] Summary box missing when adding a note

### ISSUE THREAD

**Issue by tiptruck** [TechbeeAT/jtxBoard#533]
**Describe the bug**
From the notes screen, if a note is added using the icon on the right, there is no Summary box.

**To Reproduce**
Open JTX
Select Notes to view notes
Select icon on right side to add a note (looks like a sheet of paper with a +).
Entry screen is displayed but no  @summary box is not displayed.

The shortcut icon (pencil and lightening) works as expected.

**Expected behavior**
There should be a summary box to add the heading

**Device and version:**
 - Device: [e.g. Samsung Galaxy S22] Samsung Tab S7 and Samsung A71 5G
 - Android version [e.g. Android 11] 13
 - jtx Board version: [e.g. 2.1.0] 2.4.0
 - Downloaded from: [e.g. Google Play, f-Droid, ...] F-Droid

**Comment by patrickunterwegs** [comment]
Hi @tiptruck , 
was this maybe a new installation? In order to simplify the UI for notes, the summary block is hidden by default. You can just show it by clicking on the settings icon for the screen when editing an element!

**Comment by tiptruck** [comment]
Doh.  Thanks.  Not a new installation, it just upgraded tp 2.4.0.  Sorry to waste your time

**Comment by patrickunterwegs** [comment]
No worries, I'm glad it was only that 😉
