### ISSUE TITLE
[BUG] Subtasks in Markdown Task lists miss brackets in detail view

### ISSUE THREAD

**Issue by q-wertz** [TechbeeAT/jtxBoard#54]
**Describe the bug**
In the detail view sub-tasked markdown task lists in the Description field are kind of messed up.

**To Reproduce**
1. Create a new task with task subitems
2. After saving compare the Description field in the Task overview, Detail view and Edit view
3. In the Detail view the first brackets of the indented tasks are missing

**Expected behavior**
The brackets are there.

**Screenshots**

*Edit view:*
<img src="https://user-images.githubusercontent.com/20948931/207612757-2d982e61-e478-4efc-81bb-84fdbded4ddb.png " width="40%">

*Task list view:*
<img src="https://user-images.githubusercontent.com/20948931/207612783-85342b62-5929-4e02-84b1-ea90f163e0cc.png" width="40%">

*Detail view*
<img src="https://user-images.githubusercontent.com/20948931/207612768-8d903198-803e-4779-befc-eb81db1d9e0d.png" width="40%">

**Device and version:**
 - Device: Nokia X20
 - jtx Board version: `2.01.02-rc07.ose`
 - Downloaded from: f-Droid

**Comment by patrickunterwegs** [comment]
Hey @q-wertz  thanks!
@ArnyminerZ would you mind checking this out if you have some time?

**Comment by ArnyminerZ** [comment]
Yup, will take a look. Checkboxes are currently not supported, but they surely can be. It's quite strange that the first brackets are removed, it might have something to do with them being interpreted as links... Please, @patrickunterwegs can you transfer the issue to [MarkdownText](https://github.com/ArnyminerZ/MarkdownText)?

**Comment by patrickunterwegs** [comment]
Thank you 🙂 
I would only focus on the unwanted bracket removal here, I am very sceptical regarding a basic checkboxes support within the text for jtx Board 😉

**Comment by patrickunterwegs** [comment]
It seems like I can't transfer the issue, I will give you the permission for jtx Board, so you will probably be able to do it as the owner of the markdown library 😉

**Comment by ArnyminerZ** [comment]
> Thank you slightly_smiling_face I would only focus on the unwanted bracket removal here, I am very sceptical regarding a basic checkboxes support within the text for jtx Board wink

It would implicate having some kind of callback that updates the description and adds the crosses whenever a checkbox is marked.

The other option is having read-only checkboxes, which only work as a display.

**Comment by patrickunterwegs** [comment]
Hm, I would vote for the read only checkbox or to keep the tags. I'm just afraid that actual checkboxes might get very confusing when users start working with markdown tasks AND structured subtasks...

**Comment by ArnyminerZ** [comment]
This will be fixed in version `1.2.0` of MarkdownText. Already implemented, I'll release asap.

![screenshot1](https://user-images.githubusercontent.com/12086466/207863667-f92b6f61-db48-4680-b5cf-375905c40b9f.png)

Edit: `1.2.0` has been released, it's being processed by Maven Central 😄

**Comment by q-wertz** [comment]
Thanks for the quick fix :blush: 

As I understand it, basic markdown is supported and are rendered (un-/ordered Lists, horizontal line, bold, italic, images, …) and checkboxes are shown as raw text. What (currently) does not work are subitems of lists, but they are just not rendered, I can still use them as "plain text". Correct?

**Comment by ArnyminerZ** [comment]
> What (currently) does not work are subitems of lists, but they are just not rendered, I can still use them as "plain text".

They are rendered just like another list item, for example, this:
```markdown
- Test 1
- Test 2
  - Test 2.1
  - Test 2.2
- Test 3
```
would be the same as this
```markdown
- Test 1
- Test 2
- Test 2.1
- Test 2.2
- Test 3
```
which displays as this:
- Test 1
- Test 2
- Test 2.1
- Test 2.2
- Test 3

instead of what would be supposed:
- Test 1
- Test 2
  - Test 2.1
  - Test 2.2
- Test 3

Basically (if I'm not wrong), everything in CommonMark is supported, taking into account the [limitations](https://github.com/ArnyminerZ/MarkdownText#current-limitations) from the MarkdownText library.

**Comment by q-wertz** [comment]
Ok, thanks for the clarification. I read about the indent issue on your MarkdownText commit but was not sure how to interpret 
> Nested lists are not supported. 

:)

**Comment by ArnyminerZ** [comment]
I have also just released [`1.2.1`](https://github.com/ArnyminerZ/MarkdownText/releases/tag/1.2.1), which adds the Github flavour support, which provides functionalities such as strikethrough, checkboxes and automatic links.

Take a look at the checkboxes @patrickunterwegs. They are not editable, but quite cute 😄 

![photo_2022-12-15_16-51-06](https://user-images.githubusercontent.com/12086466/207906181-f2a37cd4-2204-477f-876f-0f74b1fbd33b.jpg)

**Comment by patrickunterwegs** [comment]
> I have also just released [`1.2.1`](https://github.com/ArnyminerZ/MarkdownText/releases/tag/1.2.1), which adds the Github flavour support, which provides functionalities such as strikethrough, checkboxes and automatic links.

Thanks, it looks very nice 🙂 
I also checked the code a bit, it seems really much more complex than before, at least at first sight 😅 

jtx Board 2.1.3 is ready to be released, so I will put that update here in 2.1.4!

**Comment by ArnyminerZ** [comment]
> I also checked the code a bit, it seems really much more complex than before, at least at first sight 😅 

It's a bit stranger, because it's using the new library, but also more adaptable, extensible, and the code looks cleaner to me tbh

**Comment by patrickunterwegs** [comment]
I just wanted to upgrade, but there's a small problem with the call: 

`                                MarkdownText(
                                    markdown = description.text.trim(),
                                    modifier = Modifier.padding(8.dp),
                                    bodyStyle = TextStyle(textDirection = TextDirection.Content)
                                )`

I was using the bodyStyle for the text direction because a user was complaining, that Persian was not shown correctly from right to left. (In my eyes the TextDeirection.Content should be the default anyway, but regrettably it is not for compose...) So maybe we can just add this as a default for all MarkdownTexts? Or add the parameter somehow again? What do you think?

**Comment by ArnyminerZ** [comment]
Can you try wrapping the composable with a composition local provider of LocalTextStyle overridden with the text direction? 🤔

**Comment by patrickunterwegs** [comment]
you mean like that?
`                                ProvideTextStyle(value = TextStyle(textDirection = TextDirection.Rtl)) {
                                    MarkdownText(
                                        markdown = description.text.trim(),
                                        modifier = Modifier.padding(8.dp),
                                        //bodyStyle = TextStyle(textDirection = TextDirection.Content)
                                    )
                                }`

I tried it now with RTL, but it didn't work...
I will play around a bit more tomorrow!


But by the way thanks for the tip with composition local, I haven't been using this before, I don't know how I had missed that, but it's absolutely useful :-)

**Comment by ArnyminerZ** [comment]
> I tried it now with RTL, but it didn't work...
> I will play around a bit more tomorrow!

Mmmh... That's strange... I'll take a look at it tomorrow as well.

> But by the way thanks for the tip with composition local, I haven't been using this before, I don't know how I had missed that, but it's absolutely useful :-)

Jetpack Compose is full of secrets! 🤪

**Comment by ArnyminerZ** [comment]
I've just released [`1.2.2`](https://github.com/ArnyminerZ/MarkdownText/releases/tag/1.2.2).

It provides more default properties. This has worked perfectly for me:
```kotlin
MarkdownText(
    markdown = src,
    modifier = Modifier
        .padding(horizontal = 8.dp)
        .fillMaxWidth(),
    flavour = flavourDescriptor,
    style = TextStyle(textDirection = TextDirection.Rtl)
)
```

**Comment by patrickunterwegs** [comment]
Thanks! I just updated it!
But actually I have to say sorry, it was also my stupidity... But your sample brought me on the right path. I forgot to add the .fillMaxWidth() modifier for the description field 🤦 
Now it works 🙃

**Comment by ArnyminerZ** [comment]
😅 Don't worry, the new parameters might also be useful to someone.

**Comment by patrickunterwegs** [comment]
Yes, in fact it was necessary to pass the style, so I think that change would have been necessary anyway 😉 

Anyway, thanks a lot, also to @q-wertz for reporting the issue! I'll close this issue now as the library is changed and jtx Board will use the updated library in 2.1.4 🙂
