### ISSUE TITLE
Map Icon not Horizontally aligned

### ISSUE THREAD

**Issue by dilyanpalauzov** [TechbeeAT/jtxBoard#544]
The map icon at the top, between the location and the read-only icon, is not horizontally aligned to its neighbours.

jtx BoardVersion: 2.04.00-rc12.ose (204000012)

![Screenshot_20230508_194406_at techbee jtx](https://user-images.githubusercontent.com/4992947/236911475-6ff741f9-8f97-48e3-adaa-6e7dde47f8c7.jpg)

**Comment by patrickunterwegs** [comment]
Thanks @dilyanpalauzov !
I fixed it, and I'll also remove the link text in the meta-badges (and keep only the link icon - the link itself is a bit useless there anyway).
