### ISSUE TITLE
[Feature] Quick clear of filters

### ISSUE THREAD

**Issue by rogercreagh** [TechbeeAT/jtxBoard#556]
**Is your feature request related to a problem? Please describe.**
If you have a filter on a list then it would be nice to have a quick way of clearing the filter and getting back to the unfiltered list without having to click the filter icon at the bottom, scroll down the filter pane to the bottom of that, tap [Reset], and then scroll back to the top and tap on the list area to refresh it.

**Describe the solution you'd like**
Three options - 
1.  (my favourite) in the filter status row at the top of the list have a [X] button on the right hand end which would clear the filters
2.  in the icon row at the bottom have an additional icon to clear filter which is only active/shown if a filter is set
3. (least favourite on its own, but a useful addition anyway ) replicate or or move the reset button to the top of the filter pane with Special Filters

**Describe alternatives you've considered**
Manually clearing all the filters - not good.

**Comment by patrickunterwegs** [comment]
Hey @rogercreagh !
Thanks for the proposal, I already had a similar thought, but I was hesitating a bit. 
I agree that

> (my favourite) in the filter status row at the top of the list have a [X] button on the right hand end which would clear the filters

is the nicest solution. I will try it. I just have second thoughts about the size of the button to clear the filters. Usually the clickable elements should have a minimum size (I think 48 dp), I believe that would at least double the height of the row where the active filter criteria is visible... I'll try and post a screenshot!

**Comment by patrickunterwegs** [comment]
![Screenshot_1683809352](https://github.com/TechbeeAT/jtxBoard/assets/72232737/6ab9741b-8345-40c5-aba3-c3eff9ba0d84)

Ok, so this is what I meant, it doesn't really look good... And making it smaller will make it hard for thick fingers to touch it...

**Comment by patrickunterwegs** [comment]
@rogercreagh What do you think about putting it in the top overflow menu instead?

**Comment by rogercreagh** [comment]
Yes that is not good (in the screenshot). I was envisaging a small X at the end of the row, but I take the point about fat fingers If it is at the end (edge of screen) its not so bad small as if you miss you don't do anything bad and you can put half your fingertip on the bezel and lean it onto the screen - but I guess that is not  good practice (although I've seen apps that do use smaller icons).

What is the top over flow menu? Do you mean the three dots? Not so good as it is hidden, I think I'd prefer the bottom row (option 2) where that icon would make sense.

**Comment by patrickunterwegs** [comment]
Alright, so I think I found a nice compromise. I'll use the overflow menu at the bottom of the screen that so far I had only shown for tasks. If a filter is active also for journals or notes, the menu will get visible and you can easily reset the filters!

![Screenshot_1683834326](https://github.com/TechbeeAT/jtxBoard/assets/72232737/d0adebdd-0b85-4297-84bc-26477a0d0f86)

**Comment by rogercreagh** [comment]
Good, that works

**Comment by patrickunterwegs** [comment]
Just a quick sidenote: I didn't want to add a new icon in the row because there might already be too many. With the selector, filter, quick-add, unlock biometric protected, version-too-old-warning as a sixth icon I would only add it to the overflow menu as it's also not the most important action to do.
