### ISSUE TITLE
[Feature] Adding/changing/removing parent by editing the an item or sub-item

### ISSUE THREAD

**Issue by rogercreagh** [TechbeeAT/jtxBoard#558]
**Is your feature request related to a problem? Please describe.**

If you have created a sub item it is hidden by default until you select flat view.You can then select and edit the item without touching the parent item. 

What you can't do is detach or change the parent while editing the sub-item, or select a parent for an item while to make it a child while editing the item. 
To change a parent you have to edit the parent item and unlink the child, then go to the new parent and search for and add a link to the child there.
To set a parent for an item you have to find and go to the new parent and then search for and link the child there. 

In both cases it would be simpler to have the option to simply set or change a parent from within an item.

**Comment by rogercreagh** [comment]
Any thoughts on this? Being able to select or change the parent from within an item to make it a sub-item.

**Comment by patrickunterwegs** [comment]
Hey @rogercreagh , sorry that this took a while. 
Basically you can already see the parents of a sub-entry in the view mode.
What I could immagine is to make it also available in the edit-mode (similar to the block where you add a new sub-task. This would need
- an option to show/hide the parents-block through the bottom sheet (like all other blocks) in edit mode
- showing the parents in edit mode with an option to unlink the current entry from its parent
- adding an opiton to search for a new parent and link it from there (like linking a new sub-entry)

Would you agree with that?
