### ISSUE TITLE
[BUG] Attachments with same filename for different files generated by share

### ISSUE THREAD

**Issue by rogercreagh** [TechbeeAT/jtxBoard#559]
**Describe the bug**
Attachments created by sharing from another app will have the same filename - `name-of-app.png`.

This causes problems on another system that saves attachment files locally as they overwrite each other

In general the same name should not be used for a different file attachment

**To Reproduce**
Steps to reproduce the behaviour:
1. Open a drawing app and create a new file
2. Click the 'share-with' button and select jtxB
3. In the dialog enter a title/summary and save or save/close or save/edit
4. The new attachment will have picked up the default share filename `name-of-app.png`
5. Do it again making a different drawing - the new one will have the same filename

**Expected behavior**
Filenames should be unique. Suggest appending a date & time to the generated filename `name-of-app_YYYY-MM-DD_HHMMSS.png` would work unless someone else on another device using jtxB on the same server happened to import a file from the same app in the same second. But the meaningful name is worth the extremely small risk 

**Device and version:**
 - Device: Blackview 7100 phone
 - Android version Android 12
 - jtx Board version: 2.4.0 (2.4.1 notyeton frdroid)
 - Downloaded from: Fdroid
 - Drawing app in use Simple Draw from Fdroid

**Comment by patrickunterwegs** [comment]
Hi @rogercreagh , basically jtx Board has internal unique filenames but keeps the original filename in the database (this was actually another bug where a user reported that the actual filename got overwritten by the jtx Board internal one). The app cannot know if the file you share comes from another app (like a drawing app that always gives the same filename) or the file browser (that takes the actual filename). I think it's more important that jtx Board keeps the orignal filename and I'd say in this case it should be the exporting app that gives a more unique filename when sharing a file with another app!

**Comment by rogercreagh** [comment]
Yes I see your problem and agree that it should be the responsibility of the sending app to provide a filename- some do,some don't. In the case of Simple Draw (the clue is in the name!) it doesn't  even supply a filename if you have saved the sketch and given it a filename from within the app. I've raised it at [SimpleDraw](https://github.com/SimpleMobileTools/Simple-Draw/issues/)

Because  I have the option to automatically always save attachments as local files (embedded or uri) I have to implement a check that a filename doesn't already exist from a different journal item and add a cyclenuber to the name if it does, but that is not necessary for jtxB
