### ISSUE TITLE
[BUG] Sound note doesn't have summary/title

### ISSUE THREAD

**Issue by rogercreagh** [TechbeeAT/jtxBoard#560]
**Describe the bug**
Create an audio note - there is no summary created, If you edit the note you can only add the description

**To Reproduce**
Steps to reproduce the behaviour:

Create an audio note - there is no summary or option to create one, If you edit the note you can only add the description

**Expected behaviour**
There should be a summary/title box shown when you create the audio note (consistent with other notes).
If you don't want to have a summary entered then create a default one "Audio Note MM:SS" where MM:SS is the duration.
Showing the duration would be useful in any event

When you edit the audio note you should be able to edit both summary and description

**Device and version:**
 - Device: Blackview 7100phone
 - Android version 12
 - jtx Board version: 2.4.0
 - Downloaded from:  f-Droid

**Comment by patrickunterwegs** [comment]
Hi @rogercreagh , in one of the last releases I have set different default visibilities for each tab while I also introduced the option to hide the summary or description (if not set). For the notes I made the summary by default invisible, giving a more note-like feeling. But you can still make it visible through the settings icon at the bottom of the page. I think this makes this bug obsolete?

**Comment by rogercreagh** [comment]
Good grief, I didn't know that. Well done - ever ready with an answer :-)

Having said that an alternative would be to act like it does in some other places and have a single input box that takes the first line as the title, and anything subsequent as description.

(really must RTFM if I can remember where that is!)
