### ISSUE TITLE
[Feature] Meaningful filename for audio attachments/notes

### ISSUE THREAD

**Issue by rogercreagh** [TechbeeAT/jtxBoard#561]
Currently the filename for an audio attachment is of the form:
`1683824594803.3gp`  and `1683835352198.3gp`

Looks like these are Unix Epoch Timestampvalues when the files were created. Can we have them in human readable form please
`YYYY-MM-DD_HHMSS.3gp` or to improve uniqueness `YYYY-MM-DD_HHMMSS_[duration].3gp` where [duration] is the length of the recording in MMSS.

**Comment by patrickunterwegs** [comment]
Hi @rogercreagh , 
thanks, sure we can do that. I was checking some default conversions of the unix timestamp, the best seems to be the iso format. It's not too beautiful, but clear and standardized: 

![Screenshot_1684097050](https://github.com/TechbeeAT/jtxBoard/assets/72232737/de0a9bce-37ea-408d-90ed-6624e7300eb1)

**Comment by rogercreagh** [comment]
shame about the centi-seconds but hey ho, its a lot lot better. Thanks

**Comment by patrickunterwegs** [comment]
I think what you mean comes from the file ending .3gp 😉

**Comment by rogercreagh** [comment]
![image](https://github.com/TechbeeAT/jtxBoard/assets/44980188/b9834c86-1ac1-4f07-b792-a0bf933a4c59)

**Comment by patrickunterwegs** [comment]
Aaah, sorry, yes 😉
But I think it's still better to use some standard format than making a custom format just to remove those centiseconds...

**Comment by rogercreagh** [comment]
Yes, its ok. All begs the question of why using .3gp format (which is a mobile multimedia format used for video - and audio) rather than the simpler mp3. It just so happens that my Ubuntu laptop wont natively play .3gp although it does with VLC.

I guess its an Android thing and .3gp is what you get back from the sound recorder because its an android device.
(I'm told windows media player does natively play .3gp files for those still using windows so maybe its a niche requirement to prefer mp3).

It is what it is.

**Comment by patrickunterwegs** [comment]
The 3gp format is specialized on speech and allows a clearer recording (as I think it cuts away frequencies that are not used in common speech) and a very small filesize.

However, because of the format problem on other devices I have added a setting a longer time ago, so you can also change to AAC or OGG 😉

**Comment by patrickunterwegs** [comment]
By the way there is no default mp3 encoder in Android:
https://developer.android.com/guide/topics/media/media-formats

But if you think any other format of the defaults could still be interesting, I can have a look!

**Comment by rogercreagh** [comment]
OGG works fine for me for voice. I had forgotten, or probably never seen, the option to set a default for sound format. 

With the expanding number of default options it might be worth considering whether they should actually be flagged in the UI when they are being applied so that the user is reminded that there is a default that can be set.
Or in some instances even allowing the option to be set in the UI on the page where it is used - eg a drop-down to select sound format when creating a sound note.

Interesting doc on the android media formats, thanks for that. 3gp audio is indeed optimised for voice - 8bit and 8kHz  bandwidth with probably a custom equalisation curve.

I see from the file info on a sample recording it presents as  `Ogg data, Opus audio, version 0.1, mono, 8000 Hz (Input Sample Rate)` . So the OGG is also using 8kHz sampling which is less than ideal for anything other than voice. 

**It might be worth adding a FLAC option** with 44.1kHz/16bit sampling to provide a higher sound quality option (and of course larger files)

Incidentally the aac option comes up as `ISO Media, MP4 v2 [ISO 14496-14]` and the 3gp as `ISO Media, MPEG v4 system, 3GPP`  (using Ubuntu `file -b [filename]` command)

**Comment by patrickunterwegs** [comment]
We can give it a try, but then I'd rather use the mp4 container, or do you see any advantages in flac?
Maybe you can also comment directly here: #575

**Comment by rogercreagh** [comment]
Sorry,been away for a couple of weeks and missed this. The important  thing is to have a higher audio quality option available. Plus something that will play with a default audio player on any system. I think most systems interpret mp4 as being video so will default to using a video player even if the stream only contains audio, which is less than optimum for the user?
