### ISSUE TITLE
[Feature] Toggle DAVx5 collections

### ISSUE THREAD

**Issue by Dagda47** [TechbeeAT/jtxBoard#570]
**Is your feature request related to a problem? Please describe.**
I have multiple caldav servers synchronised vía DAVx5 on my smartphone. But i only want specific collections and not all of them show up in jtxBoard.

**Describe the solution you'd like**
Under collections i want the option to toggle specific collections on and off for usage in jtxboard.

**Describe alternatives you've considered**
Removing caldav servers from DAVx5 is not an option because i need all the data for my calendar.

**Comment by patrickunterwegs** [comment]
Hey@Dagda47 ,
Thanks, I'll have a look at this soon!

**Comment by patrickunterwegs** [comment]
Hello @Dagda47 , 
I thought about this again, the consequence of such a flag would be that the entries don't show in the list. 
But you could as well just filter the relevant collections in the list and keep the filter. Is there a reason why this is not an option?

**Comment by Dagda47** [comment]
> Hello @Dagda47 , I thought about this again, the consequence of such a flag would be that the entries don't show in the list. But you could as well just filter the relevant collections in the list and keep the filter. Is there a reason why this is not an option?

That is actually what i tried. Sorry, that i didn't mention it before. Unfortunatly the filter doesn't effect notifications so i get them unfiltered and many unwanted ones.
In fact i want that unflagged collections wouldn't show up in my lists without any filters. So this consequence would be fine for my use case.

**Comment by patrickunterwegs** [comment]
I thought about this again and in fact it doesn't make a lot of sense to implement this in jtx Board. If the goal is to not show the entries and to not apply any logic, there is no point in having the entries at all. So this is something that should be solved in DAVx5. 
Maybe it would be interesting to replace the global selector for the tasks app by a per-collection-preference - ie an option per collection to choose to which app a collection should be synchronized? What do you think @rfc2822 @devvv4ever

**Comment by patrickunterwegs** [comment]
As I don't see this as an implementation in jtx Board, I'll move it to discussions, maybe @rfc2822  and @devvv4ever  still would like to give their opinion on this.
