### ISSUE TITLE
[BUG] Previously completed tasks (part of series) return as uncompleted

### ISSUE THREAD

**Issue by AbelLykens** [TechbeeAT/jtxBoard#571]
**Describe the bug**
I have a few series of recurring tasks. I do these diligently, then check in the widget if they are done. They then disappear from the widget.
I now added some new tasks (also recurring), and oddly some task instances of old series came back.

I never used the "Detach from series" button. Backend is davx5 & Nextcloud Hub 3 (25.0.6).

**To Reproduce**
1. Add task with recurrence ("Task A")
2. Complete some of Task A
3. Add recurring "Task B"
4. See previously completed instances of Task A return

**Device and version:**
 - Device: Google Pixel 6 Pro
 - Android version: Android 13
 - jtx Board version: 2.04.02.ose 
 - Downloaded from:  f-Droid

**Comment by patrickunterwegs** [comment]
Hey @AbelLykens ! Thanks, I'll have a look at it soon!

**Comment by patrickunterwegs** [comment]
Hey @AbelLykens , I think this is basically a display problem in the widget, isn't it? When you open such an entry that reappears unchecked, is it marked as completed correctly?

**Comment by AbelLykens** [comment]
Hm I have now mark-completed them in the widget. Next time/if it happens I will open the actual app and see what the status is. Thus far it has happened 2 times. Let's wait some days. We should close this if/when I don't report back in a while ;)

**Comment by AbelLykens** [comment]
Okay I added a single (regular) new event and now others are again marked as incomplete. 
Not sure how I can debug. Events starting 12 May have returned for example. If I open the series, I can see the very first event in that series (10 May) is checked completed. But 12 and 14 May are not checked.

No idea how/why... what to do to dig further?

**Comment by patrickunterwegs** [comment]
Hey @AbelLykens !
Thanks, I will try to reproduce and debug the issue. 
The whole widget will also get an update soon, so maybe I'll check directly with the new version. 

But one more thing: Do you use any other methods to update your tasks (e.g. the NC web frontend or Thunderbird)?

**Comment by AbelLykens** [comment]
Cheers Patrick -- I did use NC tasks in the past. But not this time (when it did it again). Weird, huh?

**Comment by patrickunterwegs** [comment]
Hm, okay, thanks! 
I'm anyway doing this version upgrade of the widget library (where things will work a bit differently and hopefully more smoothly). I already observed such a behavior and try to fix it on the way 👍

**Comment by patrickunterwegs** [comment]
Hey @AbelLykens !
I think I found the issue, those recurrent entries can really be a pain implementing... But I hope I got it sorted out now, the upcoming version should solve the issue (hopefully for good) :-)
