### ISSUE TITLE
[BUG] Journal: Deleting an attachment duplicates it

### ISSUE THREAD

**Issue by khao-soi** [TechbeeAT/jtxBoard#587]
**Describe the bug**
Images / Attachments of a journal entry get duplicated instead of deleted by clicking the bin icon

**To Reproduce**
1. Go to Journals
2. Create a new entry (button on bottom right)
3. Fill in Summary and Description
4. Upload any image as an attatchment
5. Try to delete that image
6. Every time you click the little bin it duplicates it instead of deleting the image

**Expected behavior**
Clicking the bin would delete the image instead of duplicting it

**Screenshots**
![2023-05-21_15-40](https://github.com/TechbeeAT/jtxBoard/assets/2349590/f47f696f-3cbc-4a2a-92e2-069c7d680d47)

**Device and version:**
 - Device: OnePlus 8T
 - Android version: Android 13
 - jtx Board version: 2.04.02.ose
 - Downloaded from: f-Droid

**Comment by patrickunterwegs** [comment]
Thanks @khao-soi , 
indeed I made a stupid mistake there, the problem only occurs when there's a preview. I'm fixing this now.

**Comment by khao-soi** [comment]
Glad I could help. 

Danke für den schnellen Fix.
