### ISSUE TITLE
[BUG] Complete tasks, which are part of an recurrence task, don't get synchronized

### ISSUE THREAD

**Issue by BaumiCoder** [TechbeeAT/jtxBoard#601]
**Describe the bug**

When I mark a occurrence of an recurrence task as completed, it isn't synchronized with my CalDav Account via DAVx5 (server posteo.de).
(I am not sure if that is a bug in jtx or DAVx5.)

**To Reproduce**
1. Create an recurrents tasks (for example which occurs every week)
2. Mark the occurrence as complete (at the day where it occurs, if that matters) 
3. Wait till DAVx5 makes a synchronization or start on by hand
4. Switch to another client with an task application (Thunderbird, "Getting Things GNOME", ...) that is synchronized with the same account.
5. There occurence of the recurrents task is still uncompleted, after performing a sync at the other client.

**Expected behavior**
There occurence of the recurrents task is completed on other clients.

**Device and version:**
 - Device: Fairphone 4
 - Android version: Android 12 (/e/OS 1.11-s)
 - jtx Board version: 2.04.02.ose (204020005)
 - Downloaded from: F-Droid (via App Lounge)

**Comment by BaumiCoder** [comment]
If you know any other desktop linux task application with CalDav support, I can also test with them. Maybe the other clients also part of the problem.

**Comment by patrickunterwegs** [comment]
Hey @BaumiCoder !
Thank you for your issue report!

I have just released v2.4.3, f-Droid may take a few days more. There I have fixed a significant bug that occurs when using jtx Board with other apps especially with recurring entries. May I ask you to check this issue again once the new version is available?

**Comment by BaumiCoder** [comment]
> Hey @BaumiCoder ! Thank you for your issue report!
> 
> I have just released v2.4.3, f-Droid may take a few days more. There I have fixed a significant bug that occurs when using jtx Board with other apps especially with recurring entries. May I ask you to check this issue again once the new version is available?

Thanks for the quick response. Yes, I can check it, when the new version is available. (The recurrence task will be my reminder :wink: )

**Comment by BaumiCoder** [comment]
Today I have tested it with the newest app version (2.04.03.ose). Now the synchronization works corretly. :+1:

**Comment by patrickunterwegs** [comment]
Thanks for the update :-)
