### ISSUE TITLE
[BUG] Screen filled with category name

### ISSUE THREAD

**Issue by tiptruck** [TechbeeAT/jtxBoard#604]
**Describe the bug**
When clicking a category tag in a task, the screen clears and the name of the tag fills the screen 

**To Reproduce**
1. Go to Create a task and enter a summary
2. Click on categories and add a category
3. Save the task
4. View the task and click the category
5. Screen fills with the name of the category

**Expected behavior**
I'm not sure.  I guess a search of the category should occur

**Device and version:**
 - Device: [e.g. Samsung Galaxy S22] Samsung tab s7 & Samsung A715G
 - Android version [e.g. Android 11] 13
 - jtx Board version: [e.g. 2.1.0] 2.04.03.ose (204030010)
 - Downloaded from: [e.g. Google Play, f-Droid, ...] F-Droid

**Comment by patrickunterwegs** [comment]
Hey, thanks, indeed that's all ugly bug, I'll fix it as soon as possible!

**Comment by tiptruck** [comment]
Minor bug fixes for a great product! Thank you for your work

--
Craig Tipping,
When you stop learning, stop listening, stop looking and asking questions, always new questions, then it is time to die. - Lillian Eugenia Smith

-------- Original Message --------
