### ISSUE TITLE
[BUG] Upgrade doesn't check for required version of Davx5

### ISSUE THREAD

**Issue by rogercreagh** [TechbeeAT/jtxBoard#609]
**Describe the bug**
If an update to JtxB requires a specific version of DavX5 then it should check what version is currently installed BEFORE allowing the update to proceed. 

On Fdroid there is no information available about dependencies before upgrading, it is only when you check the release notes inside JtxB that you find that it requires a version of DavX5 that is not yet available.

If this is not technically possible with Android, then an upgrade that potentially breaks core functionality like sync (eg by havng the wrong version of DavX5 installed) should change the MAJOR version number, not just the patch/revision number so that the user is prompted to check before updating.

**Comment by patrickunterwegs** [comment]
There is no way to prevent an app from being upgraded through the app itself. 
I will consider upgrading the major version in the future, but for that it's too late now.
