### ISSUE TITLE
[BUG] Selecting item from widget loads 'empty' screen

### ISSUE THREAD

**Issue by amonrid** [TechbeeAT/jtxBoard#610]
**Describe the bug**
When selecting an item on the widget list (1) it loads the GUI but the content is almost always 'empty' (see attached screenshot). It seems to be related to a drawing event being stalled somehow as e.g. pressing the 'back' arrow on the 'add subtask' at the top 'flashes' the actual content of the tasks before closing the app (as is expected from the back action). 

Closing the 'empty' app and loading directly (i.e. not via widget) the exact same task GUI elements are rendered (but required to close the app first)

Removing and re-adding the widget did not resolve the issue.

(1) Widget settings: Task section, with filter to hide completed tasks + only show due today, tomorrow future and grouping by due

**To Reproduce**
1. Have widget active with task view (untested with journal or notes)
2. Select any item in the list of tasks in the widget
3. App opens 'empty'

**Expected behavior**
The tasks opens in the app with all GUI elements/content present.

**Screenshots**
![Screenshot_jtx Board](https://github.com/TechbeeAT/jtxBoard/assets/133982280/ff5ca7de-629f-4e11-9a12-abcd61c2061c)

**Device and version:**
 - Device: Samsung Galaxy S22
 - Android: version Android 13
 - jtx Board version: 2.04.03.gplay (but was also present in previous version)
 - Downloaded from: Google Play

**Comment by patrickunterwegs** [comment]
Thank you for the issue report. I think it's also related to #613, I'll have a look soon.

**Comment by patrickunterwegs** [comment]
Should hopefully be solved for good with 4b32f7ec1887aa543a3032527665316e23704aeb
