### ISSUE TITLE
[Feature] Re-Order subtasks via drag&drop

### ISSUE THREAD

**Issue by csarn** [TechbeeAT/jtxBoard#619]
**Is your feature request related to a problem? Please describe.**
I would like to have the ability to re-order subtasks (and maybe also tasks), like in google keep.

**Describe the solution you'd like**
When I tap and hold a subtask item in the task edit dialog, I can drag the subtask up or down, resulting in the order of subtasks being changed accordingly.
Nice to have: this same behaviour but in the widget view.

**Describe alternatives you've considered**
I did not find any way to re-order subtasks in jtxBoard currently. Different solutions for re-ordering would also be acceptable, the easier, the better. 
Displaying Up/Down arrows for reordering might work, but seem more complicated to use (many clicks necessary to move some item from bottom to top), and even more complicated to implement (new display widgets to draw).

Having an option to insert new subtasks not at the bottom, but any other position might work, too.

**Additional context**
My use case: I'll add all items I need to buy as sub-tasks to a shopping list task, and re-order them to be in the same order I'll find them in the supermarket. This saves a lot of time searching the list all over again. I used that a lot in google keep, but I want to move to self-hosted versions of google services due to privacy concerns.

I understand that this might be a niche use case, but it also doesn't seem too complicated to implement.

**Comment by patrickunterwegs** [comment]
Hi @csarn , this was requested already a few times (see also #150). The biggest problem is that there is no library that solves the problem in satisfying way. I have done something custom for the kanban-board which works okay, but for re-ordering things this doesn't really fit... So I can only review again if in the meantime a library came up that can be used and works well...

**Comment by patrickunterwegs** [comment]
I am doing a cleanup so I'm closing this issue here as it's basically the same as in #150
