### ISSUE TITLE
[BUG] Date Selector in Task Selects the Previous Day when selecting Time

### ISSUE THREAD

**Issue by AIndoria** [TechbeeAT/jtxBoard#630]
**Describe the bug**

Currently the date selector selects the due date as previous day when also selecting the time. It 'seems' to work fine when you only select the date. When you add time, things go bonkers.

**To Reproduce**

* Edit a task (currently synced to Nextcloud), 
* set Due Date to say, 29th of June, 2023. Then add Time of say, 1900.
* When you're back on the main task edit screen, you'll see 28th of June instead of 29th of June.
* However, if you only select the date, it works fine.

**Expected behavior**
...It should let me pick the correct date lol.

**Device and version:**
 - Device:  Samsung Galaxy S22
 - Android version  Android 13
 - jtx Board version: latest beta v2.4.5-beta02. (Tried 2.04.04 from f-droid first, then tried beta, problem persists)
 - Downloaded from: f-droid, direct from github(beta)

**Comment by patrickunterwegs** [comment]
Hey @AIndoria !
Thanks for the bug report. In fact I realised the issue in 2.4.3, fixing this was driving me a bit crazy because those date things can get so complex. So thought I had found a fix and build 2.4.4, but obiously it is still there... I'll have a look soon to hopefully get this fixed for good!

**Comment by patrickunterwegs** [comment]
Hey @AIndoria , would you mind checking if beta-03 fixed the problem? It's just being uploaded.

**Comment by AIndoria** [comment]
Works perfectly. Thank you for absolutely quick update!
