### ISSUE TITLE
[BUG] Chips are annoyingly small

### ISSUE THREAD

**Issue by ivan-avalos** [TechbeeAT/jtxBoard#644]
**Describe the bug**

The filter/tag chips in the list are too small, like, annoyingly small. It is probably far below the levels usually dictated in design and accessibility guidelines, it hurts my eyes sometimes. Besides, the layout has a lot of vertical padding (but little horizontal padding) and overall it looks off. You're not Frito Lay! I think you can give us a better air-to-chips ratio.

**To Reproduce**
1. Open jtxBoard.
2. Watch the horror.

**Expected behavior**
Have bigger and more usable chips.

**Screenshots**
![Screenshot_20230621-180403_1](https://github.com/TechbeeAT/jtxBoard/assets/16617314/812af27a-2b34-416b-ab30-48653b513db2)

**Device and version:**
 - Google Pixel 6a.
 - Android 13.
 - jtx Board version 2.04.05.ose.
 - F-Droid.

**Comment by patrickunterwegs** [comment]
Hello @ivan-avalos , 
Those elements are actually "badges" with the default font size for badges.
The badges are not clickable, so the small font size is more a problem of accessibility, but you can still set a bigger font size in your system settings.
I chose the "horror" with the "annoyingly small" badges consciously because they contain just meta information that should not get too much focus in this overview.

I will not change that. You can have a look at OpenTasks or Tasks.org for alternatives that work with DAVx5

**Comment by ivan-avalos** [comment]
I think you are misusing badges. They weren't meant for labels or tags; they are usually reserved for counts and numbers, or at least that's what it seems according to the official MD3 guidelines on [badges](https://m3.material.io/components/badges/overview). At least for the “active filters,” I think [filter chips](https://m3.material.io/components/chips/specs#e900592f-75a4-4298-853c-bedd8f462f83) would be a better fit.

> I chose the "horror" with the "annoyingly small" badges consciously because they contain just meta information that should not get too much focus in this overview.

In my opinion, wanting something to not get too much focus in the UI does not justify decreasing font sizes that much; there's a limit. There are better and more accessible approaches, such as hiding the badges by default and only showing them selectively, or maybe using the outlined variants over the filled ones, so as to make them stand out less. Besides, such “meta information” can be useful for some people: maybe someone might actually want to read it, and having such small font sizes makes the overall experience less pleasant.

> I will not change that. You can have a look at OpenTasks or Tasks.org for alternatives that work with DAVx5

I'm sorry if I was too aggressive with this bug report; but I have mostly no complaints with jtxBoard. I think it's an excellent and functional app, and it does everything that I want it to do. Among CalDAV syncing apps, it is unmatched in terms of functionality. It is only this small detail that really makes me not want to use the app too often anymore.

**Comment by patrickunterwegs** [comment]
Filter chips would be huge compared to the other elements. Then would would happen if you click on a filter chip?  Filter the whole list by the given date/category/collection...? I don't see the necessity of this functionality. Additionally this would look really ugly and completely mess with the focus on the important things in the card. 
If you like you can start a discussion on this topic and if the idea finds a lot of supporters, I will reconsider it.
