### ISSUE TITLE
[BUG] Setting a completed task "unconpleted" using the checkbox does not change anything

### ISSUE THREAD

**Issue by joostdekeijzer** [TechbeeAT/jtxBoard#646]
**Describe the bug**
Where I previously could set a completed task "uncompleted" using the checkbox in the list view this currently (since v2.04.05?) does not work.

The interface does indicate a sync is needed but the status stays the same.

**To Reproduce**
1. Create a task
2. Mark it "completed" (eg. using the checkbox in the list view)
3. Try to mark it "uncompleted" using the checkbox in the list view or any other view
4. See the status does *not* change.

**Expected behavior**
I expect the status to change when I click the checked checkbox to "unchecked".

**Screenshots**

**Device and version:**
 - Device: Samsung XCover 5
 - Android 13 OneUI 5.1
 - jtx Board version: 2.04.05.gplay
 - Downloaded from: Google Play

**Comment by joostdekeijzer** [comment]
Going into Task > Edit task > set status from "completed" to eg. "Action needed" does change the status and unchecks the "completed" checkbox. But this is very cumbersome.

I use a todo list for groceries, so I tend to check/uncheck items a lot :)

**Comment by patrickunterwegs** [comment]
Hey, thanks, indeed, that's a side effect of another change, I'll have a look soon and provide a new version!
