### ISSUE TITLE
[BUG] Setting Start Date on Tasks Impairs Due Date Options

### ISSUE THREAD

**Issue by ftbliss** [TechbeeAT/jtxBoard#647]
**Describe the bug**
When creating a new task, if a start date is selected, then due date options are restricted to the same day in the month or later. For example, if I create a task with start date 06/23/2023, then due date options in July are restricted to 07/24/2023 through the end of the month. This is true for August and any subsequent months as well. 

**To Reproduce**
1. Go to create task
2. Set start date to today (or any date other than the 1st of the month) -> set due date -> calendar selector will be grayed out for all days of the month prior to the selected due date
3. Note that manually attempting to enter the due date also does not work and results in the date entry field collapsing

**Expected behavior**
I would like to be able to set due date for any day in the following months, irrespective of the start date.

As an aside, why does there have to be a start date selected in order to create recurring events? If it weren't for this requirement I personally would not use the start date feature at all.

**Device and version:**
 - Device: Google Pixel 4a 5G
 - Android version: Android 13
 - jtx Board version: 2.04.05
 - Downloaded from: Google Play

Thanks so much for your help! This is a fantastic project

**Comment by patrickunterwegs** [comment]
Hey @ftbliss ! 
Thank you for your feedback and bug report! 
I have made a fix and provide a new version as soon as possible! :)
