### ISSUE TITLE
[BUG] Can't un-tick subtasks anymore with 2.04.05.ose from F-Droid

### ISSUE THREAD

**Issue by csarn** [TechbeeAT/jtxBoard#651]
**Describe the bug**
I used to un-tick "completed" subtasks when they became relevant again (shopping list).
With the latest version this is not possible anymore.

**To Reproduce**
1. Create a task 
2. Click on the "completed" checkbox
3. Save it
4. Try to remove the "completed" checkmark
5. Nothing happens, it stays completed

**Expected behavior**
I can remove the "completed" checkmark as in older versions

**Device and version:**
 - Device: Pixel 6a
 - Android version: 13
 - jtx Board version: 2.04.05.ose
 - Downloaded from: F-Droid

**Comment by patrickunterwegs** [comment]
Hey @csarn , sorry for that, a new version is already on the way and should be published on f-Droid soon!

**Comment by csarn** [comment]
Wow cool that was fast! After some playing around, it seems it had to do with "keep status, progress and completed in sync" setting. If i disabled that and mamually removed the status "completed", I could uncheck an item again.

**Comment by patrickunterwegs** [comment]
Thanks for the update :-) Yes, it is related to this setting, but it should work also with the setting activated 😉 
So I'm closing this one now with a reference to #646
