### ISSUE TITLE
[BUG] Adding Alarm to new task: Can only select any 31st of any month

### ISSUE THREAD

**Issue by csarn** [TechbeeAT/jtxBoard#658]
**Describe the bug**
See title. This just happened on July 1st, 14:14 CEST (maybe relevant... Today would be the 31st of June if June had 31 days?).

**To Reproduce**
1. Click + sign in home screen widget to create new task.
2. Add a title and click "Save & Edit"
3. Click the "add alarm" button.
4. See the date picker for month of July with all days except the 31st grayed out.
5. Select other month in the future.
6. See every day except for the 31st also grayed out. On 30-day month no day can be selected.

**Expected behavior**
Only days that are in the past are grayed out. I can select the current day or any future day.

**Screenshots**
![Screenshot_20230701-141200](https://github.com/TechbeeAT/jtxBoard/assets/4563314/4f4c358a-feda-4e29-85da-e443bc93aabb)

**Device and version:**
 - Device: Pixel 6a
 - Android version 13
 - jtx Board version: 2.04.05.ose
 - Downloaded from: F-Droid

**Comment by patrickunterwegs** [comment]
Hey @csarn , 
Can you please update to 2.04.07.ose and try again? The problem should be solved there!

**Comment by csarn** [comment]
Yes it is fixed, sorry! I thought I checked for updates, but somehow missed it.
