### ISSUE TITLE
[BUG] Improve/remove meta badges in Kanban-Cards

### ISSUE THREAD

**Issue by patrickunterwegs** [TechbeeAT/jtxBoard#662]
Each task box in the Kanban view has a little top bar that shows the task's general info( the collection, status, the unsynced icon, etc) that you can side swipe through them, i believe its a nice new feature, unfortunately when i try to swipe the tasks between the columns sometimes (specially outdoors) i swipe through the top bar instead of moving the task to the other columns it becomes frustrating at times trying to swipe the tasks several times to get it moved instead of going through the top bar, if you can add the option to either remove the top bar entirely or choose what type of info get shown there, it would fix the issue, for example a task that is in the Needs Action column doesn't need to state that it needs action in the task's top bar, some people might prefer it as a small reminder when they are focusing on a task, but i for example don't need it.

See https://gitlab.com/techbeeat1/jtx/-/issues/615

**Comment by Ahmet-Ch** [comment]
Thank you for staying on top of it Patrick, i appreciate your effort <3

**Comment by patrickunterwegs** [comment]
Thank you too for the improvement suggestion =)
