### ISSUE TITLE
[BUG] sorting by `Due` shows Overdue, Completed, Due Next

### ISSUE THREAD

**Issue by foss-** [TechbeeAT/jtxBoard#667]
Android 13.0
jtx Board 2.04.07.ose

**Describe the bug**
When sorting Tasks by `Due` the sorting order is unexpected.
The order is `Overdue, Completed, Due tomorrow, day after, etc, Without due date`

**To Reproduce**
1. set `Tasks > Sort > Group/Sort` to `Due`

**Expected behavior**
Would expect to see completed items at the end of that sort order. They are not actionable and unactional items should not be presented at such a prominent place.
`Overdue, Due tomorrow, day after, etc, Without due date, Completed`

**Comment by patrickunterwegs** [comment]
Hello @foss- , 
I'm not sure if this is such a good idea. Basically I understand what you mean, but for now the ordering is just a primitive sort order, you still have some filter option like the option to show only uncompleted entries. So I'm thinking if you want to have a sort order by due date, why wouldn*t you activate the filter to show only uncompleted entries?

**Comment by foss-** [comment]
That works indeed. I still consider the current behavior unexpected. Are you aware of other task apps using this sorting order when sorting by Due Date?
However feel free to close the issue, if you are not planning to work on this. The filter workaround of course does the trick.

**Comment by patrickunterwegs** [comment]
> Are you aware of other task apps using this sorting order when sorting by Due Date?

The discussion should not be what other apps are doing, but what makes most sense in the context.

**Comment by foss-** [comment]
As explained in the other issue, I believe that looking at different implementations can be useful to learn how others solved a problem.

2.05.02.ose just hit F-Droid and the new sorting is very helpful in keeping a focus. Also knowing that completed tasks will be found at the end of the list (as opposed to somewhere in between) is helpful in quickly reviewing those.

Thanks for this change.
