### ISSUE TITLE
[Feature] allow editing Due date by tapping it

### ISSUE THREAD

**Issue by foss-** [TechbeeAT/jtxBoard#672]
Android 13.0
jtxBoard 2.04.07.ose

**Reproduce**

1. open Tasks
2. tap on a single task to go to task details
3. tap due date

**Currently**

Due date is highlighted and nothing else happens.

**Expected**

Tapping should open a view where the due date can be modified. But this is not possible currently. Either the pen icon at the bottom has to be tapped or interestingly when tapping the item description, jtxBoard switches to editing view. Identical problematic behavior for started date.

**Comment by patrickunterwegs** [comment]
Indeed the edit mode opens when you click on the description. 
When you click on a category, you would return to a list with all elements having the selected category.

I'm a bit unsure what to do there. A user could expect to return to a list of entries that take place on the same day. Or that the edit mode opens. Just allowing to change the date would be an additional logic... Now it's also clear that you can change details of the entry, save or revert the change. Allowing the date to be changed from the view mode would also mean that it's saved immediately. 

Are there any other opinions on that?

**Comment by foss-** [comment]
Can you name apps that use tapping the date to not edit it, but go to a category, like show all items for this specific day?
I think allowing to edit the date on tap is the most immediate and expected action. Opening full edit mode just to change the date seems a bit too much and results in additional taps needed for the same action. But lets wait if more feedback / thoughts on this are shared.

**Comment by patrickunterwegs** [comment]
> Can you name apps that use tapping the date to not edit it, but go to a category, like show all items for this specific day?

I don't know what you would like to achieve with such comments, but I'm not happy about them. If you think other apps make it better, then go for them.

**Comment by foss-** [comment]
Asking about other apps behavior may reveal other thought processes about UX flows. And also if no other behavior can be found that could be an indicator of established best practices.

Thanks for tackling this. Confirming the new behavior in 2.5.1 and hope it benefits your users.
