### ISSUE TITLE
[BUG] High energy consumption

### ISSUE THREAD

**Issue by electrix7** [TechbeeAT/jtxBoard#678]
**Describe the bug**
High energy consumption during usage of app -> device gets very hot. Problem exists since started using the app (approx. 2 months ago)

**To Reproduce**
- Monitor battery draw by using e.g. Wattz
- In idle mode approx. 0.4-0.6W
- Open jtx board -> battery draw between toggling 1.5W and 4.5W without doing anything
- Close jtx board -> back to 0.5W

**Expected behavior**
- High battery draw only for a short moment (e.g. during synchronization or applying a new filter)

**Device and version:**
 - Device: Samsung Galaxy S10e
 - Android version: LineageOS 20 (Android 13)
 - jtx Board version: 2.4.7
 - Downloaded from: f-Droid

**Comment by patrickunterwegs** [comment]
Hello @electrix7 , I haven't found any issue with power consumption or a device getting warm because of jtx Board. 
The emulator stays pretty calm in the profiler, energy consumption stays very low. 

Can you tell a bit about your entries? How many entries do you usually have in your list? Do you work a lot with recurring entries?

**Comment by electrix7** [comment]
I have about 80 recurring tasks with in summary approx. 500 items. On top of that there are 600 "normal" tasks.
Is this number already a problem?
I switched over from tasks.org and never noticed problems regarding energy consumption.

**Comment by patrickunterwegs** [comment]
Theoretically there shouldn't be an issue even with much higher numbers. But as I can't reproduce the issue, I can try to find something with your number of entries...

**Comment by patrickunterwegs** [comment]
So I had a closer look at this also checking the power consumption on different actions. Basically there is nothing suspicious. 
jtx Board has some peaks in CPU usage and battery consumption when the sync is triggered. By default jtx Board requests a sync when the app is brought to the foreground (ie. started or selected from the background apps). If you switch a lot between apps, this might cause some unnecessary synchronizations and could be a cause for the problem. 

There is a setting in the settings menu where you can switch off the sync on start of the app. 
@electrix7 could you please deactivate this setting and check if it makes a difference?

**Comment by electrix7** [comment]
Thanks for taking a close look at the problem. Indeed, the setting to disable syncing on app startup improves the behavior.

My expectation of how it works had been that syncing only starts when the app is launched for the first time, not when switching between apps for a short time.

In my case, a synchronization takes an estimated 2-3 minutes. As a result, I am virtually in permanent synchronization.
Conclusion: this is no problem of jtx Board.

However, I was surprised by this relatively long time of synchronization of davx5. With Thunderbird at the desktop synchronization was finished within a few seconds during testing, which was way faster than on normal usage.

Turns out: the amount of syncs per second varies a lot (for posteo?). When it's good, 40 entries are checked (finished all within 32 sec). When it's bad, partly only 4 entries are checked (finished all within 163s).

**Comment by patrickunterwegs** [comment]
Thanks @electrix7 !
I reopened it, now that I see your case, probably it's not the best thing to do to trigger a sync on every "resume". 
I will put the sync on start into the block where it only would get triggered if the app is started ("on create") - when the option is activated. 
That would have been your expectation and I also think now it's better to do it that way!

The long sync is still a bit curious... I will also investigate there a bit if I find improvements. But as you say, the actual code for the sync is in DAVx5 and should maybe better be discussed there.
