### ISSUE TITLE
[BUG] App is extremely sluggish at times (UI hangs)

### ISSUE THREAD

**Issue by graue70** [TechbeeAT/jtxBoard#685]
**Describe the bug**
Sometimes, the UI hangs or reacts extremely sluggish. After multiple seconds, the problem usually goes away.

**To Reproduce**
1. Make sure that you have at least two task notifications about due tasks.
2. Click on one of the notifications. Open the edit mode. Change the due date to some date in the future. Save the task. Do a 'back' gesture. (This closes jtx.)
3. Click on a second notification. jtx will open but it will not show any task data for a few seconds. The edit button doesn't do anything.

Note that this is a way to reproducibly trigger the problem. However, the problem also appears at seemingly random times when I use the app.

**Expected behavior**
The app should not hang and doing simple things like mentioned above should not lead to sluggish app behavior.

**Device and version:**
 - Device: Samsung Galaxy S10
 - Android version: Android 13
 - jtx Board version: 2.4.7
 - Downloaded from: f-Droid

**Comment by graue70** [comment]
Might be related to https://github.com/TechbeeAT/jtxBoard/issues/678 because I think the device gets warm when the problem happens.

**Comment by patrickunterwegs** [comment]
jtx Board 2.5.0 is on the way, may I ask you to check again in this version n if you still have this problem?
(It might still take a few days until f-Droid picks it up)

**Comment by patrickunterwegs** [comment]
@graue70 jtx Board 2.5.0 should now be available on f-Droid

**Comment by patrickunterwegs** [comment]
Additional question @graue70 , do you also have a lot of entries and maybe a lot of recurring entries?

**Comment by graue70** [comment]
> jtx Board 2.5.0 is on the way, may I ask you to check again in this version n if you still have this problem?

It might have gotten a little better and a little less reproducible but it's definitely not fixed.

> Additional question @graue70 , do you also have a lot of entries and maybe a lot of recurring entries?

What constitutes 'a lot'? 😅 I have quite some tasks but not a lot of recurring ones (only one in fact I think).

**Comment by patrickunterwegs** [comment]
I mean do you have dozens, hundreds or even thousands of entries, just to get done dimension.

Could you maybe make a video of the problem to see where exactly is hangs?

**Comment by graue70** [comment]
> I mean do you have dozens, hundreds or even thousands of entries, just to get done dimension.

There are 351 `VTODO`s, 740 `VEVENT`s,  601 `VALARM`s, 821 `VTIMEZONE`s and 88 lines starting with `RECURRENCE-ID`. All in all, the full exported ics file has 32k lines.

**Comment by patrickunterwegs** [comment]
Thank you!
As stated in #678 the problem might be that too many syncs are triggered. I've made an improvement there. 2.5.1 will be ready soon.
In the meantime can you maybe also turn off the sync on start and observe if the issue still occurs?

**Comment by patrickunterwegs** [comment]
@graue70 did you have the chance to observe if the issue still occurs?

**Comment by graue70** [comment]
With the 'sync on start' setting disabled, the problem is basically gone. I had only one hang in total since changing the setting.

I switched the setting back on just now but haven't had a chance to observe the behavior. Anyway, I'll assume it's fixed. If I observe the issue again, I will re-open this issue.

Thank you!

**Comment by patrickunterwegs** [comment]
Ok, thank you for the update!
#678 was anyway necessary, that should also have made a significant improvement. 
I'll take a special look again on performance when I come across the sync and list views again.
