### ISSUE TITLE
[Feature] Show due time in addition to due date and show actual date for due date.

### ISSUE THREAD

**Issue by Pesky6359** [TechbeeAT/jtxBoard#690]
Hello there,
Thank you for your app.  My feature request is in relation to the Tasks functions. I have two requests:

1. Currently, in the "List" and "Compact" views, you can group your tasks by the due date.  That's great. 
However, I would also like to be able to see the due time as well.  Is there a way to already do that?  
If not, could that feature be added where the due time is visible within a certain day?  

2. When you group your tasks in "List" and "Compact" views by the due date, you only see the due date presented as "Due on Monday" or "Due on Thursday" even if the task is a few months away from today's date.  
Is it possible to have tasks in the future (i.e. after this week) show the actual date instead of a day?  

Please advise.
Thank you.

**Comment by patrickunterwegs** [comment]
Hey @Pesky6359 , 

thank you for your feature request. 

> Currently, in the "List" and "Compact" views, you can group your tasks by the due date. That's great.
> However, I would also like to be able to see the due time as well. Is there a way to already do that?
> If not, could that feature be added where the due time is visible within a certain day?

Do you mean here that if it's the same day to group by hour? (Like to group by the same information that is shown in the badge e.g. Due in 2 hours)?

**Comment by patrickunterwegs** [comment]
> When you group your tasks in "List" and "Compact" views by the due date, you only see the due date presented as "Due on Monday" or "Due on Thursday" even if the task is a few months away from today's date.
Is it possible to have tasks in the future (i.e. after this week) show the actual date instead of a day?

Hmm, basically the app should only show the grouping as a weekday for entries that are due within the next 7 days. All other entries with a due date further in the future would show the date. I just checked it and it works fine for me. 
Can you maybe double-check this as well? And if it still happens that an entry is in a group of a weekday, could you attach a screenshow of the list and the detail of the entry?

**Comment by Pesky6359** [comment]
Thank you for coming back to me.  I see what you mean.  I have checked on my phone and it is working as you described.  I am new to the app so I think it is a question of me getting used to how the app presents information.

Thanks for your help.

**Comment by Pesky6359** [comment]
I'll close the issue now.

**Comment by patrickunterwegs** [comment]
Alright, thanks for the update 😉
