### ISSUE TITLE
[BUG] Trapped in Journal item detail pages

### ISSUE THREAD

**Issue by rogercreagh** [TechbeeAT/jtxBoard#703]
**Describe the bug**

1. Open a journal list with several items in it.
2. Click on an item to view the details
3. Click  on left or right arrow at bottom to view next or previous item
4. repeat step 3 several times (say 50+)
5. Try to get back to the list view - you cant without using the back arrow at the top (or the Android back arrow) 50+ times to go back through all the items you  have viewed and eventually get to the list.

**Expected behaviour**
There should be a control somewhere to take you back directly to the list from any item, ignoring the history.
 
I would expect either the top back arrow to do this, or there to be an up arrow together with the page controls underneath the item detail to take you to the list, or it to be available *somewhere*

I thought this was discussed and fixed some several versions ago, but either it has reverted or  it was never  implemented.

Having just paged through about 70 entries it was incredibly frustrating to discover that jtxB was now stuck on item details view with no way out apart from making 70 keystrokes!!!!

**Device and version:**
 - Device: Blackview BV7100
 - Android version Android 12
 - jtx Board version: 2,05.00 - Downloaded from: f-Droid

**Comment by patrickunterwegs** [comment]
Hi @rogercreagh , 
Well, I don't see this as a bug. I would say the back behavior in this case is logical. The back button on top and the back gesture should have the same functionality in my opinion. 

Another back behavior was not implemented. 

I can check a button close to the pagination to go back to the list and clear the backstack.

PS: in your case you could also have just killed the app and restart it to avoid the problem. I know it's not a solution, but a temporary workaround 😉

**Comment by rogercreagh** [comment]
> I can check a button close to the pagination to go back to the list and clear the backstack.

That's what's needed. Thanks. I agree the behaviour is  logical for the buttons provided, although it seems redundant to have the top left arrow replicate the bottom smaller left arrow.

My preference would be to have the top arrow (at the left of the search list) become an Up arrow when viewing an item to indicate it takes you back up to the list. But I don't  think you like that idea so a Close button on the pagination would also work. Not sure how best to position it though. Perhaps a Close icon should  replace the redundant top left (back) arrow when viewing an item?

(an up arrow is pretty widely used to go up a level to a less detailed view and for me at least completely logical)

**Comment by patrickunterwegs** [comment]
Hi @rogercreagh ,
I thought about this again, in fact, keeping entries in the back steak when going from one entry to the next is not that useful (I think it's still very relevant when going deeper in the hierarchy or opening a related every).
But when using the pagination, I could just remove the leaving every from the back stack, so the back action would just really go "up" (which then it's either the list or a related every where you're coming from). 

What do you think?

**Comment by rogercreagh** [comment]
Yes, I agree. If you are moving through the entries you are using the left/right arrows  at the bottom anyway.
