### ISSUE TITLE
[BUG] Unable to set Czech language

### ISSUE THREAD

**Issue by kri164** [TechbeeAT/jtxBoard#74]
**Describe**
Application is translated to Czech, but list of selectable languages dosnt show it

**To Reproduce**
1. Go to 'Setings.'
2. Click on 'Language.'
3. Scroll down to 'list.'
4. There is no Czech

**Expected behavior**
There should be Czech on list

**Screenshots**
![Screenshot_20221222-162533_jtx_Board](https://user-images.githubusercontent.com/52274164/209168494-3e347174-76d1-47b9-9ba6-f4fa61a76a33.png)

**Device and version:**
 - Device: Xiaomi
 - jtx Board version: up-to-date
 - Downloaded from: F-Droid

**Comment by patrickunterwegs** [comment]
Hey @kri164 , sorry for that, indeed I have overlooked that the status for the check translation is done. Currently this I need to check those things manually. I will also check how I can better automate this!
Cheers, Patrick

**Comment by kri164** [comment]
Amazing respond time.
Great Thank You
