### ISSUE TITLE
Jtx Board Journals/Nites/Tasks[BUG] 

### ISSUE THREAD

**Issue by Evol23** [TechbeeAT/jtxBoard#740]
Hi, app that seems interesting however it's impossible to download that app on android. For other apps it works fine, but for that one it takes ages to download, to end up with the message "not installed".
What could be the problem to get it installed on my device ? Thank you. 
 - Device: Samsung Galaxy A12
 - Android version 11
 - jtx Board version: 2.04.00-rc12.ose
 - Downloaded from f-Droid

**Comment by patrickunterwegs** [comment]
Hi @Evol23 , 
the app, that should be installed, usually can't have an influence on the installation process, this is all done by the system.
It is strange that you are trying to download 2.04.00-rc12.ose while there is already 2.05.01.ose available. I assume your f-Droid client is outdated and that 2.4.0 is not available anymore on f-Droid servers. Can you please update and try again?

**Comment by patrickunterwegs** [comment]
Closing this issue as it's anyway not a jtx Board problem.
