### ISSUE TITLE
[Feature] Add Filter "Start next 7 days"

### ISSUE THREAD

**Issue by jonathanathe** [TechbeeAT/jtxBoard#757]
**Is your feature request related to a problem? Please describe.**
Currently only options for displaying tasks starting with: today, tomorrow and future are presented.

Making it so that only a very short term or very long term is displayed on the task screen.

**Describe the solution you'd like**
I think there should be a middle ground as I would like to see those for the entire week (Today with the next 6 days).

This should be added in my opinion in "Special Filters".

**Comment by patrickunterwegs** [comment]
Hi @jonathanathe , thank you for your proposal, I will think about a solution. Basically it's not a big thing, I'm just afraid that the list of options will get too long. Maybe it's better to add an option to let the user choose the days in the future...

**Comment by jonathanathe** [comment]
> Hi @jonathanathe , thank you for your proposal, I will think about a solution. Basically it's not a big thing, I'm just afraid that the list of options will get too long. Maybe it's better to add an option to let the user choose the days in the future...

Hi, thanks for your response. Yes, your idea of indicating the days in the future that you want to see to avoid that the filter list ends up being very long seems very good to me. So I look forward to changes in the future! Thank you

**Comment by patrickunterwegs** [comment]
Okay, so I went for the simple solution and added an explicit filter for that for now! I'll add it in 2.5.4!
