### ISSUE TITLE
[Feature] Minor UI improvement compact list view (journal)

### ISSUE THREAD

**Issue by rogercreagh** [TechbeeAT/jtxBoard#759]
**Is your feature request related to a problem? Please describe.**
In compact list view the date is very small text on a green coloured label (same as categories) - can be hard to read, 

**Describe the solution you'd like**
Two suggestions - either do away with the coloured label background and make the date text bold and 1 or 2 pts larger keeping it in the same place in the line (after collection label, before categories)
0r move the date to immediately before the title on the second line. separated from title by hyphen. Could be not bold but same font size as title to clearly delineate it.

For both tablet and phone screen I would slightly prefer the second option because my titles tend to be short (very occasionally fill the screen width on phone), but I think the first would also work

A very minimal change would be to change the colour for the date label to distinguish it from categories - but that wouldn't work for eink screens where the category labels aren't displayed anyway

**Describe alternatives you've considered**
Using Group-by date, but there is no way of making that a default for the view so you would also have always do several taps.And in addition the date then takes up way too much space being centred on a line on its own (but the font size is plenty big enough! :-) 

**Additional context**
none

**Comment by patrickunterwegs** [comment]
Hey @rogercreagh !
I wouldn't consider removing the color from the badges. The color actually cones from the system and adapts to the dynamic color settings (from Android 13). The text color is either (dark greyish) or white - which is calculated with some logic too get the best contrast color. 

Additionally you can define preset categories with a defined color. So it's another reason why the color cannot be removed. 

I don't like the idea of moving the date before the title (or do you mean that they could look like journals?)

But I can try to make the text in the badges a little larger to make them more readable.

**Comment by rogercreagh** [comment]
Its only the date badge I want to see changed - as a minimum to make it a different colour to the categories. Obviously it is up to the user to choose a colour for the collection so that the badge isn't the same as the date.

If you need to keep the badge format for the date then how about making the badge background colour white for the date?

I guess increasing the font size will increase the height of the badge as the padding will remain the same -that might look odd in the line or might be an advantage from my pov to have the date badge stand out.

just to stress I have no problem with the current size of the collection badge or thecategory badges- I just think the date should separated since it is a primary attribute for a journal (or a task)
  
my preferred option of moving the date to the title line would look like this (line 2 is in a larger font size)

[MyCollection]   [Category1]  [Badges]  [With Small Font]
8 Aug 2023 - **This is the Title of the Item which might get truncated if it is too lon...**
Here is a fragment of the description also truncated if it gets too long for the line...

**Comment by patrickunterwegs** [comment]
Hi @rogercreagh , 

I've been checking this, so I am really not a fan of moving the date before the summary (unless I create a card similar to the journals cards). But for now I would try the option to use another container color for the badges for the dates. Instead of using the "primaryContainer", I would use the "secondaryContainer" color for the date badges. This color is usually a bit more discreet and might be better readable. (The color itself will be defined by the dynamic colors of the Android (13+) system.

What do you think?

![grafik](https://github.com/TechbeeAT/jtxBoard/assets/72232737/22c3eee9-bec7-435b-b32a-2eccbe2a9d42)

**Comment by patrickunterwegs** [comment]
This is how it would look like on a device with Android 12 and before: 

![grafik](https://github.com/TechbeeAT/jtxBoard/assets/72232737/1f985d3a-4640-4b49-9542-b6c87ca21193)

**Comment by rogercreagh** [comment]
Hi, I can't really comment on the Tasks view as I don't use tasks. If it is similar on the Journals view (but obvs with just the start date) then it is an improvement on colour screens. 

The problem remains that on an e-ink screen with the e-ink jtxB option I think that all badges you show in the Android <= 12 version will simply not show the badge background as the contrast from the white overall background is not enough. The user can set the background for the collection badge, but there will still be no difference between the date badge and the categories badges.

Any chance of making the background for the date badge configurable, or having a darker background for the categories (or the date) as you have on the Android 13+ version.

**Comment by rogercreagh** [comment]
> Instead of using the "primaryContainer", I would use the "secondaryContainer" color for the date badges. This color is usually a bit more discreet and might be better readable

If there are only two badge colours available (primary or secondary) and both are low contrast (on Android < 13)  then we have a problem on e-ink display.

**Comment by patrickunterwegs** [comment]
> > Instead of using the "primaryContainer", I would use the "secondaryContainer" color for the date badges. This color is usually a bit more discreet and might be better readable
> 
> If there are only two badge colours available (primary or secondary) and both are low contrast (on Android < 13)  then we have a problem on e-ink display.

For the eInk theme I have set the colors explicitly. I will check this later. But would you then prefer no background or a very light gray?

**Comment by patrickunterwegs** [comment]
@rogercreagh So you can just tell me what color/shade would be best for you and I'll just set it for the eInk-Theme ;-)
Currently the primaryContainer color is set to white, the secondary container to very dark gray.
I could either set both to white or the secondary container to a very light gray.

**Comment by patrickunterwegs** [comment]
Here's how it could look like: 
![Screenshot_20230727_1644292](https://github.com/TechbeeAT/jtxBoard/assets/72232737/65680080-f390-4eb3-a4c2-ebddb86bb09b)

**Comment by rogercreagh** [comment]
Sorry for delay, been away for a couple of days.
Light grey is good.
So in journal list view whiite or user set for collection, light grey for date and dark grey for categories.
On a phone with eink (contrast) display setting it currently looks like this
<img src="https://user-images.githubusercontent.com/44980188/261089947-7b8afb43-fb1c-4698-8ebb-db9147134338.png" width="400" />
with the collection name on a mid green badge, the date and categories on white, and a custon x-status on a light green badge

On my enk tablet screen currently all show as white (except where I have selected a strong colour for collection, on this device 
<img src="https://user-images.githubusercontent.com/44980188/261090923-576f5d25-71e3-4f89-973e-db99dc9ac043.png" width="600" />
I hadn't set a custom colour for that custom x-status - it was created on the phone and the colour property is not carried across- perhaps it should be?)

**Comment by patrickunterwegs** [comment]
Alright, thanks! 
So let's go for the light grey, if any other colours/shades are not fitting on the e-Ink display, just let me know and I can probably easily adjust!

The color for the x-status is basically not synchronised, it's only a local setting that stays on the device. Those settings cannot be synchronised with single entries as it might get inconsistent (like two different colours for the same x-status in different entries).
But I will add an option to import/export the presets in version 2.4.5 (which means it's done already, but just needs also a bit of time in beta).
