### ISSUE TITLE
[BUG] Not sufficient contrast when showing task’s colour

### ISSUE THREAD

**Issue by dilyanpalauzov** [TechbeeAT/jtxBoard#767]
In jtx Board 2.05.02 the color of a task can be hardly visible, if it has low contrast to the backgroud.

Please fill the whole surrounded area with the task colour and use as text colour either white or black, depending on what has higher contrast to the background.
  
![Screenshot_20230811_184229_at techbee jtx](https://github.com/TechbeeAT/jtxBoard/assets/4992947/eff26752-adac-43b2-9177-7b1d83684661)

**Comment by patrickunterwegs** [comment]
I see, I don't want to fill the whole element with the color, but I'll try making the border thicker
