### ISSUE TITLE
[BUG] Timezone ignored when calculating overdue moment

### ISSUE THREAD

**Issue by dilyanpalauzov** [TechbeeAT/jtxBoard#769]
**Describe the bug**

I set the timezone on my phone to Singapur.  Now is 08:05 UTC or 16:05 Signapur.  I create a task with

> DUE:20230812T180000Z

It is due after 9h hour and  55minutes, but jtxBoard 2.05.02 shows in the List view “Due in 1 hours”.

For displaying the overdue moment jtxBoard apparently compares the time of the system with the due time of the task, ignoring any timezone discrepancies between both.

**Comment by patrickunterwegs** [comment]
Thanks @dilyanpalauzov , I'll check
