### ISSUE TITLE
[Feature] Remove superflous whitespace from the tasklist.

### ISSUE THREAD

**Issue by Ceaus** [TechbeeAT/jtxBoard#800]
**Is your feature request related to a problem? Please describe.**
The task list uses an insane amount of whitespace. If you have a number of tasks with subtasks, then there's only room on the canvas for a few tasks, simply because there's too much whitespace. 

**Describe the solution you'd like**
I'd like to see the list more condensed and compacted. I think that each task doesn't need more than two lines, and still show status and category.

As an example I've added two screenshots of the task list:
1. The list as it's displayed now. I've indicated all the superfluous whitespace with blue squiggly lines.
2. The same list but with a more compact relocation (bodged Paint job). Note how the whole screen fits in just a half a screen. And I did not remove any information!

![tasklist_current](https://github.com/TechbeeAT/jtxBoard/assets/13982083/7c2d3d57-096a-4d9f-a20e-819da5d84959)
![tasklist_new](https://github.com/TechbeeAT/jtxBoard/assets/13982083/847e6d91-b6c4-4719-acf1-356e4bbedaf9)

**Comment by patrickunterwegs** [comment]
Hi @Ceaus , 
I understand, but the problem is the component and the usability. 
The checkbox is a default element of Googles Material3 components. While the checkbox itself has a size of 20 dp (density pixels), the clickable area around it is 48 dp. This comes from a standard definition of the component to ensure that the clickable area is big enough to not frustrate users. 

See also here in the code documentation: 

![grafik](https://github.com/TechbeeAT/jtxBoard/assets/72232737/fb79d614-e07f-4832-8860-f5d8cc0f8ad9)

Even though I agree with you, this shouldn't be changed. So the checkbox will always take it's (clickable) space.

Other alternatives wouldn't look very good, I think the checkbox should still stay aligned with the summary.

Still I reviewed the code and spaces and found a few pixels that could be saved. I think this will improve it at least a little bit!

**Comment by Ceaus** [comment]
Thanks for the feedback. I appreciate it.  From a standards perspective I see where you're coming from, but I'm not sure I agree. Agreed, I'm not an Android developer, heck not a developer at all, so I might be talking nonsense. But let me try to give you some options to get the creative juices flowing.

**Scaling**
According to [StackOverflow](https://stackoverflow.com/questions/2151241/android-how-to-change-checkbox-size), you might be able to apply scaling to manage the checkbox. This is an old thread, so this might not be applicable to current Android versions.

**Layout**
1. From the first screenschot, notice how the checked (11) from the first task can be removed as this is already a badge at the top bar, next to the green, red and blue badges. That line is unnecessarily duplicated.
2. Your choice of words suggest the checkbox is an integral part of the same display area where you type the text. It might possible to isolate the checkbox into a separate panel (?) giving you more options for vertical placement of the various bits and pieces without breaking natural reading flow.

**Choice of selection mechanism**
The checkbox is used to indicate if a task a finished. It might be possible to replace the checkbox with a long press, showing a number of context dependent actions. Or in different words: if a checkbox yields usability problems in the display domain, it might not be the right tool for the job as it seems to be a limiting factor.

**Comment by patrickunterwegs** [comment]
Hey @Ceaus ,

Well, yes, I understand what you mean, there are ways to work around the checkbox by scaling it or also by replacing it e.g. by an image that is replaced on click. But any such solution would go against the usability guidelines and might cause frustration for users. 

Replacing the checkbox by a menu and displaying the information elsewhere sounds like a good idea, but I believe that when users have a task list, it's just exactly that what they expect, a list of entries with a checkbox. It's intuitive and clear.

So I think that changing the checkbox with another element would decrease clarity and usability and accessibility of the app.

Best would be the possibility to reduce the padding of the checkbox while keeping the clickable area big enough to fulfill the guidelines. But this is currently not supported...
