### ISSUE TITLE
[Feature] In filter selection sort categories alphabetically

### ISSUE THREAD

**Issue by rogercreagh** [TechbeeAT/jtxBoard#802]
**Is your feature request related to a problem? Please describe.**
The ordering of categories in the filter selection area is seemingly random (?date each category created). Ordering alphabetically would make it easier to find the category/categories you want to filter by when you have 20+ of them

**Describe the solution you'd like**
Sort them alphabetically

**Describe alternatives you've considered**
Not adding too many categories!!!!

**Additional context**
Would also be good if the categories were sorted alphabetically in the Active filters section at the top of the list view

**Comment by patrickunterwegs** [comment]
Currently I'm limiting the categories to 5, the user can then click on "more" to see all categories. 
The idea was that the first 5 are the 5 last used categories and it might be likely that the user wants one of them again. I'm afraid that if I order the categories by name, that the first 5 would then be random just because they happen to be the first ones because of the sort order...

**Comment by rogercreagh** [comment]
My experience is that I see no correlation between the recency with which a category is used and my need to filter by it. It would make more sense (for me) if you showed the 5 most used (ie attached to the most items)  categories.

Most recently used makes a bit of sense in the order of categories when selecting ones to apply - but since I typically am applying 3 or 4 categories to each new item that means that the first 5 (and the rightmost ones in the selection list for a new item if that is how they are sorted) will at best be those used in the previous item and one or 2 from the one before that. Not actually very helpful either (in my case - there are seldom more than 2 categories the same in successive items, and usually one or none)

In both cases (filter list, and apply list)I would find alphabetical more useful. Only showing the first 5 and 'more...' is fine 'cos it saves space. I'd find it quicker to always expand the list and know where to find the ones I want quickly. Also the ability to start typing in the box and have the matches pop up is better than relying on the recent or most used order - both of which change all the time so there is no consistency between sessions.

With the new filter arrangement of only showing 5 and 'more...' is there also the ability to type in a selection box as when adding categories to an item? That would be perfect, and very economical in space terms

**Comment by patrickunterwegs** [comment]
Ok, I understand the problem.

What do you think about showing the top 5 (most used) categories and when clocking on "more" to show all but alphabetically?

**Comment by rogercreagh** [comment]
> What do you think about showing the top 5 (most used) categories and when clocking on "more" to show all but alphabetically?

YES! Very good, I like it.

**Comment by rogercreagh** [comment]
@patrickunterwegs 
Slight problem with showing categories by most used or recently used - on my system (v2.05.03) it is now sometimes taking about 30 secs after opening the filter dialogue for the categories section to stop jumping around. It is obviously doing this as it trawls through all of the items updating the recent/most used counts and changing the display as it progresses. It doesn't always do this, but about one time in three - possibly when there are new items since the filter dialogue was last opened, or when the app has been closed and re-opened.

This makes the filter dialogue category selection very unstable as the order continually flashes around so you can select. 30secs is too long to wait.

With 400+ items in the list and 30+ categories in use this is taking over 30secs which is not really usable - could it do it in the background and simply change the order next time the filter dialogue is opened rather than messing on the live screen?

(or switch to a static user selected 5 most wanted categories which would then never change - actually I would find this most helpful, to be able to choose 5 categories which would stick to the top of the list and the rest (more...) alphabetical. Then you'd never need to trawl through re-counting.)
