### ISSUE TITLE
[BUG] Clear filter not refreshing list

### ISSUE THREAD

**Issue by rogercreagh** [TechbeeAT/jtxBoard#805]
**Describe the bug**
When a filter is active the three dots menu at the bottom of the list Clear Filter option doesn't refresh the list - it should.

**To Reproduce**
1. Apply a filter to a list
2. Click on three dots and Clear Filter
3. Nothing changes until you switch to a different view and back again - makes the menu option a bit pointless

**Expected behavior**
The list refreshes with no filter applied when Clear Filter is pressed.

**Screenshots**
n/a
**Device and version:**
 - Device: phone and tablet
 - Android version 11 and 12
 - jtx Board version:2.05.02
 - Downloaded from:  f-Droid

**Comment by patrickunterwegs** [comment]
Hi @rogercreagh ,
Thanks for the bug report.
This also has changed a bit in 2.5.3.
I have removed the buttons from below, the reset option is now a fixed preset called "no filters". It made more sense to have it on the top and I think it's still very clear.

f-Droid seems to be a bit delayed again with the new version, I hope.they will pick it up soon...

It you still encounter and issue with the functionality in the new version, please let me know. In my check it worked properly.

**Comment by rogercreagh** [comment]
At the top of the filter dialog is good cos at present there is no feedback when you press reset at the bottom of the dialogue that anything has changed unless there happens to be a selected button in view which then clears.

**Comment by patrickunterwegs** [comment]
Yes, indeed. This additional "no filter" chip will be marked as active when you click (or remove all filters manually), so it should be much clearer for the user.

**Comment by patrickunterwegs** [comment]
Hi @rogercreagh , would you also consider this issue as resolved?

**Comment by patrickunterwegs** [comment]
@rogercreagh , I'm closing this one now, if you still have an issue with it, please let me know.

**Comment by rogercreagh** [comment]
Sorry, missed this yesterday - yes the NoFilter button is much better where it is and it does always refresh the list.
