### ISSUE TITLE
[Feature] Bad contrast on https://jtx.techbee.at

### ISSUE THREAD

**Issue by dilyanpalauzov** [TechbeeAT/jtxBoard#819]
The bottom of https://jtx.techbee.at uses white text on yellow background.  This has low contrast and low contrast is hard to read.

**Comment by patrickunterwegs** [comment]
Thx, but this is only an issue when you use the website in dark mode, right? (It might have automatically been activated with the system settings, you can change it on top with this contrast Symbol)

**Comment by dilyanpalauzov** [comment]
> This is only an issue when you use the website in dark mode

Yes

**Comment by patrickunterwegs** [comment]
Ok, I'll fix it soon

**Comment by patrickunterwegs** [comment]
Fixed 👍
