### ISSUE TITLE
[BUG] Compact list date display colours and filter select colours

### ISSUE THREAD

**Issue by rogercreagh** [TechbeeAT/jtxBoard#826]
**Describe the bug**
Good news and bad news:
First the good news, in v2.05.03 the light grey background colour on the compact date list renders ok on monochrome eink screen - thank you.
Secondly the bad news, in the filter selection dialog the selected filters are now almost invisible on both monochrome eink screens and colour screens with eink (contrast) display settings.
See image

white text on very light background almost invsible

**To Reproduce**
Install v2.05.03 and set eink (contrast) display and go to filter list

**Expected behavior**
Selected badges should be readable - in previous version white text on black background worked ok, on very pale grey white text is nbg

**Screenshots**
![Screenshot_2023-08-25_08-07-56](https://github.com/TechbeeAT/jtxBoard/assets/44980188/76cd46e8-2484-4233-b1c0-a55d7c931ccc)

**Device and version:**
 - Device: Boox tablet and Blackview phone
 - Android version Android 10 & 11 respectively
 - jtx Board version: 2.05.03
 - Downloaded from: fDroid

**Comment by patrickunterwegs** [comment]
Especially in this eInk theme you can just let me know and I will correct whatever ;-)
Indeed the selected chip takes the secondary container color and the "onSecondaryContainer" color was set to white. I set it now to DarkGray which has a good contrast on the phone. I hope it will also look well readable on the eInk display!
