### ISSUE TITLE
[BUG] show all option should also show the summary and description (if hidden)

### ISSUE THREAD

**Issue by rogercreagh** [TechbeeAT/jtxBoard#838]
**Describe the bug**
When creating a new Note there is no summary box. It shows up ok if editing an existing note with a summary, but there is no way to create a summary/title for a new note, or to add one an existing note which has no summary.

In addition sometimes when you tap in the description box to bring up the keyboard the display jumps off the top of the screen.You have to then close the keyboard (android down arrow at the bottom) and reopen it by taping again in the box to get it back  

**To Reproduce**
1. Create a new note
2. Observe the non-existent Summary box

**Expected behavior**
A Summary text box visible above description by default for new note as in v2.5.3

**Device and version:**
 - Device: Blackview Tab 6
 - Android version . Android 11
 - jtx Board version: 2.5.5beta2/3
 - Downloaded from: gitHub

**Comment by rogercreagh** [comment]
BTW i've reactivated an old tablet (not that old!) so I can install beta versions from here. Should beta bugs be raised here as an issue, or by DM?

**Comment by patrickunterwegs** [comment]
Some users have criticised that taking a note is too overwhelming with many option, so I made the summary and description fields also fields, that can be shown/hidden through the options menu at the bottom of the screen 😉 

About beta-issues, please also open them here. I prefer having something traceable, in a DM I would also just open an issue here just hiding the author (or personal information)...

The keyboard issue has been raised before (#539 ), but I guess as it wasn't solved yet, I should maybe raise an issue at Google...

**Comment by rogercreagh** [comment]
Funnily enough I looked in the bottom options menu but it isn't there when you show all options, but I now see it does appear as an option if you press the cogwheel bottom left.

Has the default changed - or was I just confused because this is a fresh install. If it has always been like that, or if a normal upgrade would preserve the existing setting, then this is a non-issue and can be closed. with my apology for raising it
 (personally I think summary/title and description are the only two fields that should be there by default on a fresh install - but with the option to hide them)

Incidentally I'm using OpenBoard keyboard

**Comment by patrickunterwegs** [comment]
In fact, if the summary doesn't show with the show all option, this is a bug... I'll fix that! So let's keep this issue open.

The default setting after a fresh install has been like this for many months, but yes, I specifically took care that an upgrade wouldn't change the UI for existing installations!

Anyway, better have a short discussion about a non-issue than missing one 😉
