### ISSUE TITLE
[BUG] Widget does not display tasks according to the filter properly

### ISSUE THREAD

**Issue by jonathanathe** [TechbeeAT/jtxBoard#841]
**Describe the bug**
When trying to use the new filter "Start within 7 days" it does not respect the filter and shows you all future events.

This error does not occur within the app and the tasks are displayed correctly as check marks in the filter.

**To Reproduce**
1. We enter the widget configuration.
2. In my case I check two options which are: Hide Completed Tasks and Start within 7 Days.
3. Click on save.

**Expected behavior**
The widget is expected to respect the indicated filters and not to display tasks that are not in the date range.

**Screenshots**
![photo_2023-08-30_16-51-18](https://github.com/TechbeeAT/jtxBoard/assets/34164094/cdfb8cb9-c7a7-43f9-afe4-9801741c5031)

![photo_2023-08-30_16-51-15](https://github.com/TechbeeAT/jtxBoard/assets/34164094/dac26ee7-1c15-49c0-a079-b878648abcd1)

**Device and version:**
 - Device: Samsung Galaxy S23 Ultra
 - Android version: Android 13
 - jtx Board version: 2.05.04.gplay (These problems are also shown in the latest betas.)
 - Downloaded from: Google Play

**Comment by patrickunterwegs** [comment]
Thanks @jonathanathe , I'll check soon

**Comment by patrickunterwegs** [comment]
Hey @jonathanathe , thanks again and sorry for the issue report!
I found the cause and fixed it (specifically for the widget I forgot to pass on the new filter information to the filter config).
I'm just updating the new version 2.5.5-beta05. As you also use beta versions, it would be great if you could update and confirm that it's also solved for you! =)

**Comment by jonathanathe** [comment]
Thank you! I am waiting for the update to come out to test it and tell you things. 

@patrickunterwegs

**Comment by patrickunterwegs** [comment]
Quick update: the new version is available now! =)

**Comment by jonathanathe** [comment]
It works! Thanks a lot
