### ISSUE TITLE
[BUG] sorting by start date not working

### ISSUE THREAD

**Issue by bepolymathe** [TechbeeAT/jtxBoard#846]
**Describe the bug**

When I sort by start date, it returns odd results. Tasks starting in 4 days or more are shown first, but those starting today or in the following days are displayed at the end of the list. And tasks with no start date are in the middle of the list. 

**To Reproduce**
1. only apply "hide completed tasks" and "sort by ascending start date"

**Expected behavior**

That the chronological order of the start date is correctly displayed.

**Device and version:**
 - Device: [Samsung A 22]
 - Android version [ Android 13]
 - jtx Board version: [2.05.03.ose]
 - Downloaded from: [f-Droid]

**Comment by patrickunterwegs** [comment]
Hey @bepolymathe !
This should be solved through #814 !
Regrettably f-Droid is super slow in picking up the latest builds lately. But once 2.5.4 is available, please check it again and let me know if it is also solved for you! Thank you! =)

**Comment by bepolymathe** [comment]
OK, i have installed the play store version. It works like a charm. 😃

**Comment by patrickunterwegs** [comment]
Great, thanks for the update 🙂👍
