### ISSUE TITLE
[Feature] Scroll to top for list

### ISSUE THREAD

**Issue by patrickunterwegs** [TechbeeAT/jtxBoard#860]
I thought today that it would be cool to have a button in the bottom menu bar to go to the top of the list. 

https://framapiaf.org/@0_0/111036750195543808

**Comment by rogercreagh** [comment]
especially when you remove a filter and the view stays at the current item which may be a long way down the unfiltered list.

Staying in the same place in the list when removing a filter is okay, but a quick way to get back to top of list would be very good.

While you were about it perhaps a second one to jump to the end of the current list - eg useful if applying a filter to the current list and wanting to jump down to the oldest item in the new list) - Of course you could achieve that by going to the top and reversing the sort order - but you might want to keep the current order.

**Comment by patrickunterwegs** [comment]
Hi @rogercreagh , 
for now I will only do the scroll to top button. If you feel like a scroll to bottom button is really needed, please let us open this is another feature and discuss.
