### ISSUE TITLE
[Feature] Remove redundant information about attachments, subtasks, subnotes in list view

### ISSUE THREAD

**Issue by dilyanpalauzov** [TechbeeAT/jtxBoard#876]
Below a task shows twice, that it has an attachment, and it shows twice, that there is a parent task.

This information shall be displayed only once.

![Screenshot_20230916_081132](https://github.com/TechbeeAT/jtxBoard/assets/4992947/0bd2a9b7-6edb-47c1-8e71-a81aa17c23eb)

**Comment by patrickunterwegs** [comment]
Hi @dilyanpalauzov , you mean the redundant info at the top of the card, right?

**Comment by dilyanpalauzov** [comment]
Yes, this is what I mean.
