### ISSUE TITLE
[BUG] Misleading presenting the due moment as day of week

### ISSUE THREAD

**Issue by dilyanpalauzov** [TechbeeAT/jtxBoard#877]
**Describe the bug**
Now is Saturday September 2023 08:23 UTC.

I create two tasks:

> DUE:20230923T040000Z

> DUE:20230924T040000Z

In the List view jtx Board shows

> Due on Saturday

> Due on Sunday

If today is Saturday, and a task is due on Sunday, this means, that the task is due tomorrow.  But in this case it is due in eight days.  Likewise, if today is Saturday and a task is due on Saturday then this usually means that the task is due today, while here it is due in one week.

* Render the due moment as day of week, only if between now and the due moment there are less than seven midnights.
* If longer period shall be converted to days of week, precede the day of week with “next”: “Next Saturday”, “Next Sunday”.

**Device and version:**
 - jtx Board version: 2.05.04.ose (205040010)

**Comment by patrickunterwegs** [comment]
Ok, thx, I'll do the first part: 
- Render the due moment as day of week, only if between now and the due moment there are less than seven midnights.

For the second part 
- If longer period shall be converted to days of week, precede the day of week with “next”: “Next Saturday”, “Next Sunday”.
I would keep the date
