### ISSUE TITLE
[BUG] UI might freeze while editing when sync is running at the same time

### ISSUE THREAD

**Issue by patrickunterwegs** [TechbeeAT/jtxBoard#884]
Feedback Christoph W (Nextcloud)

**Comment by rogercreagh** [comment]
I have this problem with 2.06.0 I saw it occasionally with 2.05 but 2.06 is nearly unusable.  How do I downgrade to 2.05? @patrickunterwegs

**Comment by patrickunterwegs** [comment]
Hi @rogercreagh , sorry, somehow my answer seems to be lost. I was sure I replied. But the only way to downgrade is to delete the app and install an old .apk (from f-Droid or from the versions here on GitHub).
But in 2.6.3 I have brought back an older behavior (which might not be so clean from architecture perspective, but seems to be better for performance), so it's likely that the latest version works again as older ones (or better). But let me know if you still encounter such performance issues.

**Comment by rogercreagh** [comment]
see new comment in #758 and also #867
