### ISSUE TITLE
[Feature] Show DUE in View mode without spelling the UTC offset

### ISSUE THREAD

**Issue by dilyanpalauzov** [TechbeeAT/jtxBoard#894]
JtxBoard 2.05.05ose does show as DUE now the time only in local timezone.  But it shows also the UTC offset of this local time zone, like GMT+02:00.  As users know the timezone of their device, the UTC offset shall not be shown.

At the botton the Created and Last-modified fields are shown correctly in local timezone without UTC offset.

![Screenshot_20230921_223402](https://github.com/TechbeeAT/jtxBoard/assets/4992947/b1f3b689-ecd9-4f35-99dc-a32d60751ac8)

**Comment by patrickunterwegs** [comment]
This is now covered in #971
