### ISSUE TITLE
[BUG] Duplicate due date line in edit view if timezone is set

### ISSUE THREAD

**Issue by graue70** [TechbeeAT/jtxBoard#901]
**Describe the bug**
See Screenshot. The due date appears duplicated in the edit view if a timezone is set.

**To Reproduce**
1. Create a task
2. Put a due date without a timezone
3. When confirming the due date, the date appears once (which is correct)
4. Edit the due date and add a timezone
5. Confirm the due date
6. See error

**Expected behavior**
No duplicated line

**Screenshots**
![Screenshot_20230923-005648_jtx Board](https://github.com/TechbeeAT/jtxBoard/assets/23035329/b2c05a43-9b4a-41b9-afd0-659e487a0515)

**Device and version:**
 - Device: Samsung Galaxy S10
 - Android version: Android 13 (LineageOS 20)
 - jtx Board version: 2.5.5.ose
 - Downloaded from: f-Droid

**Comment by patrickunterwegs** [comment]
Thx @graue70 , I will cover this in #913

**Comment by patrickunterwegs** [comment]
Hi @graue70 , this is now covered in #971 and will come in 2.6.2!
