### ISSUE TITLE
[Feature] Option to show specific matches for search in sub-entries

### ISSUE THREAD

**Issue by nomorsug** [TechbeeAT/jtxBoard#914]
**Is your feature request related to a problem? Please describe.**
If you search a term with multiple matches in subtasks for tasks for e.g. with 10+ subtasks, there is no way to quickly narrow down for which subtask the match is found in

**Describe the solution you'd like**
From #155 `If a matching sub-entry is found, the main entry is shown with all its sub-entries.`

- Instead, it will be more useful to have an option to show only the sub-etries that match the search, reducing the visual clutter in compact view, and giving exact matches in all other views
- In the case the main entry is shown with all its sub-entries marking the matching sub-etnries with a different color to make it visible

**Comment by patrickunterwegs** [comment]
Hi @nomorsug , 
thanks for your proposal. 
I will add an option in the menu to also limit the subentry search results. 

The second bullet point you mentioned is problematic, because the search term might be in a line that is not visible in the list. So won't do that.
