### ISSUE TITLE
[Feature] Explore Kotlin Multiplatform for desktop app

### ISSUE THREAD

**Issue by nomorsug** [TechbeeAT/jtxBoard#915]
Currently, there isn't any good desktop CalDAV implementation. [Kotlin Multiplatform](https://kotlinlang.org/docs/multiplatform.html) could allow porting jtxBoard to desktop/iOS without having to rewrite the app from scratch.

https://github.com/simplex-chat/simplex-chat is a good example of Android app ported to desktop from a single codebase (this is still WIP but proves its feasible)

**Comment by patrickunterwegs** [comment]
For sure this is an interesting topic. I would really like to dig deeper into KMM, but for now I had to take a new full-time job and I'm more limited in time for the next months, so this won't happen any time soon. I'll keep this topic in discussions though.
