### ISSUE TITLE
[Feature] Consider switching to Weblate for translations

### ISSUE THREAD

**Issue by nomorsug** [TechbeeAT/jtxBoard#917]
Weblate is free and opensource localization tool. The hosted version https://hosted.weblate.org/ is free for libre projects. It can also be selfhosted.

Compared to Crowdin it has larger pool of translators, it's easier to use and is used by the majority of FOSS android projects including F-Droid.

**Comment by patrickunterwegs** [comment]
Hi @nomorsug , thank you for your suggestion, actually I'm pretty happy with Crowdin, not sure if it's so much worth another change now...
I'll move this topic to discussion.
