### ISSUE TITLE
[BUG] Widget shows an error - GlanceAppWidget

### ISSUE THREAD

**Issue by rk-sTEk** [TechbeeAT/jtxBoard#932]
**Describe the bug**
The Startpage-Widget shows an error after updating to Android 14 in Pixel 7pro. Happens on all, journal, notice, task.

**Expected behavior**
No data displayed, only the error message based on GlanceAppWidget.

**Screenshots**
![Screenshot_20231005-104029](https://github.com/TechbeeAT/jtxBoard/assets/147046123/c6209722-bb60-4d74-b72d-90e683a99ef8)

**Device and version:**
Pixel 7pro
Android 14
Oct '23 security patch
jtx Board version 2.05.06.ose (205060008)
downloaded from f-Droid (20231005)

**Comment by patrickunterwegs** [comment]
As said in #931 this is solved in the latest version 2.6.0. If f-Droid is delayed, you can either take the version from Google Play or directly the APK from GitHub
