### ISSUE TITLE
[BUG]  "Please purchase the Pro package to enable editing capabilities of remote c..."

### ISSUE THREAD

**Issue by zzyzx-dc** [TechbeeAT/jtxBoard#947]
**Describe the bug**
When trying to save an existing recurring task I receive the toast popup: "Please purchase the Pro package to enable editing capabilities of remote c..."

It does not give the full message. I am not sure what the Pro package is.

**Comment by patrickunterwegs** [comment]
Hi @zzyzx-dc , from where did you download the app and which version are you using? Basically you can find the Buy Pro menu entry in the main menu.
