### ISSUE TITLE
[BUG] Inconsistent behavior of the enter key when adding subtasks to a task

### ISSUE THREAD

**Issue by alexjung** [TechbeeAT/jtxBoard#976]
**Describe the bug**
The behavior of the enter key when adding subtasks to a task is inconsistent. When adding a subtask with the "enter key" the subtask gets added, but when there is a space character at the end of the subtask to be added, the text remains in the entry field without the trailing whitespace character. When there is no trailing whitespace character, the task gets added but disappears from the entry field. 

When using the "add subtask" button to the right of the text field, the task gets added and the text disappears, even when there is a trailing whitespace character.

**To Reproduce**
1. Go to Tasks, open an existing task or add a new one.
2. Open the detailed view of a task, where subtasks can be added.
3. Enter some text in the "add subtask" field.
4. Depending on whether there is a trailing whitespace, the text either disappears from the text field when pressing "enter" on the on-screen keyboard (expected behavior) or it stays in the field (without the trailing whitespace), even though the task was added correctly.

**Expected behavior**
The text should disappear from the subtask text field when the task is added, independent of using the UI button or the "enter" key of the on-screen keyboard.

**Screenshots**
Trailing whitespace character at the end of the subtask string, use the enter key on the on-screen keyboard to add the task:
<img src="https://github.com/TechbeeAT/jtxBoard/assets/13679015/564d6f66-ec16-4277-a5ec-34b64b9592ed" alt="screenshot01" width="50%"/>

Task was added but the string remains in the text field, now without the trailing whitespace:
<img src="https://github.com/TechbeeAT/jtxBoard/assets/13679015/f462dcc1-59d2-4807-b2c8-916c3ca510dc" alt="screenshot01" width="50%"/>

**Device and version:**
 - Device: Samsung Galaxy S10
 - Android 12, Samsung One UI 4.1
 - jtx Board version: 2.06.01.ose
 - Downloaded from: f-Droid

**Comment by patrickunterwegs** [comment]
Hi @alexjung , 
Basically the keyboard action and the button click is doing the same thing. So functional there is no difference. 
But already some months ago I investigated a similar issue, the only solution was to change the keyboard provider (and it worked after). It seems like some keyboard providers have a problem with the UI-framework (which is Jetpack Compose, the latest and most modern one in Android) - this might also be the reason why you might not have this issue in other apps that use older UI frameworks. I also couldn't find a workaround to avoid the issue, but in any case it should be solved by the keyboard provider... Sorry that I can't give you better news on this issue!

**Comment by alexjung** [comment]
Thanks for the explanation!

You should think that Microsoft can implement a keyboard correctly for the up-to-date UI-framework. But then there's Windows... Never mind 😂
