### ISSUE TITLE
[BUG]  present view left when screen turns

### ISSUE THREAD

**Issue by burningT** [TechbeeAT/jtxBoard#979]
**Describe the bug**
No matter if I am editing a note or task, when the screen turns e.g. from portrait to landscape, the view is left to e.g. the task overview. Juat typed data might get lost during this transition. However, I am under the impression, this happens on almost any possible view and I always and up in the task overview.

**To Reproduce**
1. Switch the screen turning feature on and have the phone in portrait mode
2. Enter the notes overview
3. Create a new note
4. Turn the phone 90 °
5. See the view jump to tasks overview

**Expected behavior**
The view only changes into landscape mode but the content remains unchanged.

**Device and version:**
- Device: SHIFT6mq
- Android version Android 10
- jtx Board version: 2.06.01.gplay (206010008)
- Downloaded from: Google Play

**Comment by patrickunterwegs** [comment]
Hi @burningT , 
basically I took your ticket as a chance to review all textfields to make sure texts get preserved when the rotation changes, this is done in #981 . 

However, your specific issue I couldn't reproduce. I now tried it with an emulator with Android 10 with the specific version 2.6.1, but every time I rotate the screen, the edit view just stays open as expected. So as I can't reproduce the issue, it's a bit hard to change anything. Besides the handling of the back stack is done by a navigation library. 
Would you mind making a short video so I can check if I see something suspicious?

**Comment by burningT** [comment]
Hi Patrick,

The video is appended to this message. I just noticed some consistency with #980: it seems like jtx applies the filter settings present in the widget and possibily turns to tasks as tasks are shown in the widget.


https://github.com/TechbeeAT/jtxBoard/assets/5808054/8d1199b6-6605-468a-b4e0-d8b4ea8c16fa

**Comment by patrickunterwegs** [comment]
Thanks @burningT ! I found the issue, it would only occur when you open the app from the widget (in this limited screen), then go back to the normal list and then add an entry and then make the screen rotation 😉  It's really pretty specific, but sure it needs to be fixed. I'll add the fix to the next version.
