### ISSUE TITLE
[Feature] Handle entries with DUE=DTSTART

### ISSUE THREAD

**Issue by rfc2822** [TechbeeAT/jtxBoard#98]
See bitfireAT/ical4android#70

**Comment by patrickunterwegs** [comment]
@rfc2822 Instead of a setting I would add a prominent message if DUE==DTSTART. What do you think?

![Screenshot_20221229_191215](https://user-images.githubusercontent.com/72232737/209993427-8f761748-3a8a-4c53-9619-0d8a5626e699.png)

**Comment by rfc2822** [comment]
Looks good :) Maybe offer a "drop start" button in the message that resets the start date, too? And maybe you can omit the "with DAVx5", otherwise users could think its a DAVx5 problem.

**Comment by patrickunterwegs** [comment]
I would like to avoid such a button, the solution for the user might be (1) accept it, (2) change the date or (3) clear the date. But I think if a user explicitly sets the date, (3) might not be the preferred action, so I think it's more likely that a user would change the date. Anyway, users should know what to do after they have seen the message a few times 😉 

About the text: I can remove it, but the idea was just to make the user aware, that DAVx5 might throw the error, but the origin is the server! 😉

**Comment by patrickunterwegs** [comment]
Closed, no change necessary
