### ISSUE TITLE
[BUG] manipulated filter settings and disappearing bottom panel

### ISSUE THREAD

**Issue by burningT** [TechbeeAT/jtxBoard#980]
**Describe the bug**
When I open the board via the widget, funny things happen lately. The filter settings that were active when last using the board are reverted. Additionally, the entire bottom panel is gone. Adjusting filters is impossible this way and creating entries becomes challenging. The filter settings and the bottom panel can be restored by selecting the board in the menu.

**To Reproduce**
1. Set some funny filters that make e.g. all notes disappear by selecting only annulated notes
2. Exit the board
3. Open the board via the top left corner of the widget
4. See the bottom panel being vanished and the filter settings being reverted

**Expected behavior**
Everything is behaves the same, no matter how the app is opened.

**Device and version:**
- Device: SHIFT6mq
- Android version Android 10
- jtx Board version: 2.06.01.gplay (206010008)
- Downloaded from: Google Play

**Comment by patrickunterwegs** [comment]
Well, that's not really a bug, it's a feature ;-)

The thing is it was requested, that when you open the app from the widget, it would be good to see exactly the filter settings applied that you had in the widget. 
But then the question was if this is really always intentional? What if you wanted to keep the setting that you had previously in the app but just wanted to have the full view of the widget in the app?

That's why the app first opens in that view where you can't change the filter settings. You can still go back to the original list screen with the original filter settings. By the way the same screen (without the option to filter further) opens when you open an entry and click on one of its categories, you'd get back to the list screen with all entries of this category.

I still believe that this is a good approach, even though it might be confusing for some users...

**Comment by burningT** [comment]
Well that's a twist :-D

As you said, some find this irritating and hard to handle. I am definitely one of those. Why not make this configurable?

**Comment by patrickunterwegs** [comment]
Well, configurable... I really don't want to add another configuration for something like that...
What I was thinking is to link the jtx logo on the left differently. 
So the jtx logo would just open the app normally while clicking on the widget header (with the text) the app would open the filtered list (according to the widget filters). 
What do you think, would that be a compromise?

**Comment by burningT** [comment]
Hm I see your point. However, separating the fields to click on comes with its own difficulties, I assume. If you are not specifically aware of this feature, it would appear to be an inconsistency as the app would behave differently for apparently no reason. Or am I missing something?

**Comment by rogercreagh** [comment]
Well I don't use the widget (any widgets actuall cos I find them a pain) but if I did want to try it I would expect to have two ways of jumping to the full app - either jump to the app with the same view (filters) as in the widget, or open the app normally as from the icon.

If I had to have only one it would be to make the widget open the app with the view it was presenting, and use the normal icon to open the normal front screen. 

But if there is a jtx logo/icon on the widget then making that open the vanilla view would make sense.

**Comment by burningT** [comment]
@rogercreagh I appreciate that we agree on the need for two ways of opening the app from the widget. However, do you really think that the invisible difference in spots to click at would not lead to frustration without further axplaining it to the user?

**Comment by rogercreagh** [comment]
> @rogercreagh I appreciate that we agree on the need for two ways of opening the app from the widget. However, do you really think that the invisible difference in spots to click at would not lead to frustration without further axplaining it to the user?

only the first time(s). Its a shame Android screens are so small and don't really have mouseover tooltips and I don't suppose there is room for any hint text (eg 'Home' under the icon and 'Click to expand' on the header.

In a sense it is self documenting - clicking an icon you expect an app to open in its default state, clicking on anything else in the app or widget you expect to open a specific view. I think this would be enough once you knew that was what it did.

Is there room on the widget for a small help icon (?) to pop up help text?
