### ISSUE TITLE
[Feature] Filter Journals by date range

### ISSUE THREAD

**Issue by rogercreagh** [TechbeeAT/jtxBoard#988]
**Is your feature request related to a problem? Please describe.**
For journals specifically (and to a lesser extent perhaps for Notes and Tasks) it would be nice to be able to filter by date range.

**Describe the solution you'd like**
Currently the date filtering is targeted at Tasks - the options are under Special Filters - ideally that section would not show if you are viewing journals - or move it to the bottom of the filter section so that more useful filters are nearer the top.

Instead of Special Filters I'd like a new section Date Filters. This would provide entry for a start date and an end date. If only start was entered then the list would show everything since that date, if only end date was entered it would show everything before that date. If both dates were entered it would show everything between the dates. (the dates should be inclusive - the list would include items on the start and end date) 

**Describe alternatives you've considered**
The current jump to date icon in the bottom is some help as obviously you can scroll up or down from there, but with a very large list it is less than ideal.

**Additional context**
Now we've had jtxB in daily use for over a year the lists are getting pretty long. One use case is to see what I was doing last September. Another is to find an entry when I know roughly when it happened - sometime after that trip in October but before the Christmas holiday. It may well be that having a default filter to only show the last four weeks entries might speed up things on slow devices.

**Comment by patrickunterwegs** [comment]
Hi @rogercreagh , thanks, I'll check that soon, I'm just pretty low on energy right now. 

But basically I guess this would need a more comprehensive approach. 
On the one hand it would need absolute date filters with from-to as absolute dates for start, due and completed. 
But then the same with relative dates, like from x days in the past to y days to the future. 
The query itself is trivial, the question will be how to put all this in the UI...

**Comment by rogercreagh** [comment]
Something like this?  With an android appropriate layout. The date type option only need to show when filtering tasks, for Journals it is always start date, for notes it is always created date.
The number and date entry fields toggle visible depending on the state of the relative/absolute radio selection.
Two screenshots (on a webpage, not a android page, but I assume similar form field types are available)
**Relative** selected:
![image](https://github.com/TechbeeAT/jtxBoard/assets/44980188/b68d13ec-d0a2-4c13-9a8f-b3f77f094ab2)

**Absolute** selected:
![image](https://github.com/TechbeeAT/jtxBoard/assets/44980188/bfb96c88-d95a-43d8-8a68-154f34557b73)
