### ISSUE TITLE
[Feature]  Is there a way to make tasks stick to notification?

### ISSUE THREAD

**Issue by C8opmBM** [TechbeeAT/jtxBoard#989]
It would be nice to be able to have task/s shown on notification bar (even option to make them sticky).
In Google Calendar, you can add a task and it only stops appearing when you mark it completed.

Could it be implemented?

**Comment by patrickunterwegs** [comment]
Hey @C8opmBM ,
Basically you can already set an alarm for tasks that will trigger a notification!

Additionally you can activate the setting "sticky alarms" which will keep the notification until it's marked as done.

I think that's exactly what you requested, isn't it?

**Comment by C8opmBM** [comment]
I tried but it's too complicated :)
I just need to have a notification as soon as I enter a task in say the widget.
However, it's not that easy, since I can select the same day as template, but I still need to add the time etc, setup alarm.
Can we also have a default time - when started, same as the day? 

So we can have a simple way to scribble a note and have it directly visible as a notification until marked as done?

Thanks.

**Comment by patrickunterwegs** [comment]
Hi @C8opmBM ,
Hm, I'm not sure if this is such an interesting use case. Basically I could add a new option in the automatic alarms seeing to always trigger am alarm on creation, but what's the added value if you have a notification immediately when you see the open task in the widget anyway?

**Comment by C8opmBM** [comment]
Thanks, and you do have a point.
However, I assume most of us don't have the widget on the first screen.
This is only like a sticky reminder and I am sure this would come in handy for others.

You would not put this the default behaviour, but only as an option, similar to the the date.
Hope you could justify it :)

Have a great weekend!
